### ISSUE TITLE
Xiaomi Mi 10T Lite / Xiaomi Mi 10i / Redmi Note 9 Pro 5G (gauguin) - Apply to be new maintainer

### ISSUE THREAD

**Issue by KaguraRinko** [PixelExperience/official_devices#2202]
## Device you want to apply for
Xiaomi Mi 10T Lite / Xiaomi Mi 10i / Redmi Note 9 Pro 5G (gauguin)

## Device tree sources
Device tree: [https://github.com/baolong24/android_device_xiaomi_gauguin](https://github.com/baolong24/android_device_xiaomi_gauguin)

Vendor tree: [https://github.com/baolong24/proprietary_vendor_xiaomi_gauguin](https://github.com/baolong24/proprietary_vendor_xiaomi_gauguin)

Gauguin is using prebuilt kernel, so don't have kernel source

## Number of ROM's you maintain officially
Only [Havoc-OS](https://download.havoc-os.com/?dir=gauguin) I maintain officially (for gauguin)

## Any Exceptions/special concern?
Hi PixelExperience Team.
I'm so sorry to application again.

I been rejected yesterday because 
- Using Custom Build Fingerprint
- Commits do not have proper authorship or commit messages.
- Using a custom build type set as baolong24
- Shipping MIUI apn configs

At the email end, it said "apply once again after a period of 3 months."

But fix these issues which is not that hard, no need to take 3 months to fix these.
So today I take some time to fix these issues, then I checked one more time with my device tree again against the Maintainers conduct notes and Device Requirements.

For now my device tree are much better than yesterday.

### Telegram username
[@baolong24](https://t.me/baolong24)

### Github username
[baolong24](https://github.com/baolong24)

### XDA username
[wubaolong](https://forum.xda-developers.com/m/wubaolong.7074033/)

### Your email
[wuxiaofei31@gmail.com](mailto:wuxiaofei31@gmail.com)

**Comment by Hasaber8** [comment]
@baolong24 you must have received an email, please check it

**Comment by KakatkarAkshay** [comment]
all required strings for any custom packages should be used from https://github.com/PixelExperience/packages_resources_devicesettings-custom. If there are any missing you can add them and push to gerrit.

**Comment by KakatkarAkshay** [comment]
The only needed in https://github.com/baolong24/android_device_xiaomi_gauguin/blob/eleven/init/init_gauguin.cpp is the model and brand in case of note 9 pro. Rest should not be touched. As for the safetynet you don't need to worry about it, it's all handled source side

**Comment by Hasaber8** [comment]
@baolong24 please respond, or we will have to close the issue

**Comment by KaguraRinko** [comment]
> all required strings for any custom packages should be used from https://github.com/PixelExperience/packages_resources_devicesettings-custom. If there are any missing you can add them and push to gerrit.

Got it, i'll push to gerrit later

**Comment by baolong24** [comment]
> all required strings for any custom packages should be used from https://github.com/PixelExperience/packages_resources_devicesettings-custom. If there are any missing you can add them and push to gerrit.

Sir, I have removed all commits related to safetynet

**Comment by KaguraRinko** [comment]
> The only needed in https://github.com/baolong24/android_device_xiaomi_gauguin/blob/eleven/init/init_gauguin.cpp is the model and brand in case of note 9 pro. Rest should not be touched. As for the safetynet you don't need to worry about it, it's all handled source side

Sir, I have removed all commits related to safetynet

**Comment by jhenrique09** [comment]
#2206
