### ISSUE TITLE
pixel experience not installing in redmi note 7s

### ISSUE THREAD

**Issue by harikrishnankh** [PixelExperience/official_devices#2204]
I tried installing pixel experience 10 and 10 plus in my **redmi note 7s** using **orangefox** but failed. Please help. Is it compatible with **note 7** only

**Comment by KakatkarAkshay** [comment]
10 and 10 plus are deprecated

**Comment by harikrishnankh** [comment]
what about 11 and 11 plus

**Comment by harikrishnankh** [comment]
I also tried 11 but also failed. Need to confirm that should I try 11 plus. Can you please make sure that it will work on redmi note 7s like redmi note 7. Or is there anything else that I should do other than normal steps in installation?

**Comment by Gaurav241** [comment]
This isn't the place for discussion. Head towards https://t.me/pixelexperiencechat or your device specific group.
