### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by dhruvkumar1805** [PixelExperience/official_devices#2217]
## Device you want to apply for
```
Redmi S2/Y2 (YSL)
```

## Device tree sources
```
https://github.com/DhruvChhura/android_device_xiaomi_ysl
https://github.com/DhruvChhura/kernel-perf
https://github.com/DhruvChhura/android_vendor_xiaomi_ysl
```

## Number of ROM's you maintain officially
```
2
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
t.me/DhruvChhura
```

### GitHub username
```
GitHub.com/DhruvChhura
```

**Comment by Hasaber8** [comment]
Review is as follows.
The device tree is basically revengeOS tree , with no real contributions from your side.

Sorry to say that your application was not accepted
