### ISSUE TITLE
New maintainer for OnePlus 5/5T (cheeseburger/dumpling)

### ISSUE THREAD

**Issue by Protowise** [PixelExperience/official_devices#2218]
## Device you want to apply for
```
OnePlus 5/5T (cheeseburger/dumpling)
```

## Device tree sources

```
https://github.com/Protowise/device_oneplus_msm8998-common
https://github.com/Protowise/device_oneplus_cheeseburger
https://github.com/Protowise/device_oneplus_dumpling
https://github.com/Protowise/kernel_oneplus_msm8998
https://github.com/Protowise/vendor_oneplus
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
http://t.me/protocheese
```

### GitHub username
```
Protowise
```

**Comment by KakatkarAkshay** [comment]
Review is as follows.

You are setting Custom Build Fingerprint which is not allowed.
Your commits do not have proper authorship or commit messages.
You are setting cloudflare dns as default dns. (Just why?)

Sorry to say that your application was not accepted

**Comment by Protowise** [comment]
How about now?
