### ISSUE TITLE
New maintainer For Tulip

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#2226]
## Device you want to apply for
```
Xiaomi Redmi Note 6pro (tulip/twolip)
```

## Device tree sources

```
https://github.com/Mishrahpp/device_xiaomi_twolip
https://github.com/Mishrahpp/device_xiaomi_sdm660-common
https://github.com/Mishrahpp/kernel_xiaomi_sdm660
https://gitlab.com/the-muppets/proprietary_vendor_xiaomi/-/tree/lineage-18.1/sdm660-common
https://gitlab.com/the-muppets/proprietary_vendor_xiaomi/-/tree/lineage-18.1/twolip
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
so what you wants to be official please answer you can try my builds its and my users are loving it
```

### Telegram username
```
@Mishrahpp
```

### GitHub username
```
https://github.com/Mishrahpp
```

**Comment by jjpprrrr** [comment]
PixelExperience-Devices org already has a xiaomi sdm660 common tree. Are you going to use that, or are you going to make a separate tree for tulip?

**Comment by ghost** [comment]
I will use Pixel-Experience Sdm660-common tree ..

**Comment by jjpprrrr** [comment]
> I will use Pixel-Experience Sdm660-common tree ..

Then update your tree and your application to reflect the changes.

**Comment by ghost** [comment]
I have updated....

**Comment by jjpprrrr** [comment]
> I have updated....

There's no way you have finished a build and tested the build within 6 minutes. Here's the thing: we are not trying to give you a hard time. What we would like to see is some kind of proof that

- you have basic understanding of how android works
- you are capable of fixing things and making improvements beyond simply renaming a Lineage device tree

Unfortunately, I cannot see any of them from your current offerings. Your github profile is basically blank, and you do not have previous participation in open source projects. Your tree is from Lineage without any of your original commits.

**Comment by ghost** [comment]
I said I will use future build  Pixel-Experience sdm660 common trees and please tell me that when lineage trees are working Correctly without any issue so why I commit... I clone device trees directly form Lineage os github without Forked in my profile I have just Forked it to fulfill requirement for maintainer

I think you have to cheak my build and use it For some time... 
Because Just cloning device tree and Build is Bugless without any commits in Trees ..

**Comment by ghost** [comment]
It there is no issue in build so why I edit device tree? 
(Everything Working fine)
Just Answer this 


There is no issue.. That's your wish you have to give A tag of official or not but I will support unofficial

**Comment by ghost** [comment]
![Screenshot_20210501-034204_Pixel_Launcher](https://user-images.githubusercontent.com/63914710/116759149-4d2e5900-aa2f-11eb-8ef5-ddcb54a511e1.png)

**Comment by jjpprrrr** [comment]
> I said I will use future build Pixel-Experience sdm660 common trees and please tell me that when lineage trees are working Correctly without any issue so why I commit... I clone device trees directly form Lineage os github without Forked in my profile I have just Forked it to fulfill requirement for maintainer
> 
> I think you have to cheak my build and use it For some time...
> Because Just cloning device tree and Build is Bugless without any commits in Trees ..

I am not sure if you understand what I meant. I did not say anything about the stability of your build. In fact, I do not own tulip so there is no way for me to check it anyway.

My question was about **you** as a maintainer. If all we need is a working build that follows everything from LIneage, I can write a script in 5 minutes to do the renaming automatically. That is not what we want. 

What we are looking for is a capable maintainer.

**Comment by ghost** [comment]
As your wish

But I Think User Will use Rom and He wants Stable Rom
He does not Know/matter which device tress Uses in build

You should know this the device is about 3 year Old....
Most Rom's Developer has dropped

**Comment by jjpprrrr** [comment]
> As your wish
> 
> But I Think User Will use Rom and He wants Stable Rom
> He does not Know/matter which device tress Uses in build
> 
> You should know this the device is about 3 year Old....
> Most Rom's Developer has dropped

Everyone wants a stable build. That is not the point.

Let's consider a couple of different scenarios:

- Pixel Experience is not LineageOS. What if something that exists on PE but not on Lineage becomes broken in the future? Will you be able to fix that?
- What if Lineage stops maintaining tulip? What are you going to do after that? Will you be able to keep the device, kernel, and vendor updated without the help of Lineage?

**Comment by ghost** [comment]
1. Pixel Experience is not LineageOS. What if something that exists on PE but not on Lineage becomes broken in the future? Will you be able to fix that? -- I will When it is required I don't think it is required Now

2.What if Lineage stops maintaining tulip? What are you going to do after that? Will you be able to keep the device, kernel, and vendor updated without the help of Lineage?  ---  I will maintain it As Long as Possible 


I am giving you a clear cut Answer : Till the time we get the trees Readymade(Stable) , why should we edit the trees and when the trees are not available, then I will edit

That's the final Words from me...  Give Your Final Result and Close This.....  
I am Happy With Unofficial

**Comment by jjpprrrr** [comment]
> I am giving you a clear cut Answer : Till the time we get the trees Readymade(Stable) , why should we edit the trees and when the trees are not available, then I will edit
> 
> That's the final Words from me... Give Your Final Result and Close This.....
> I am Happy With Unofficial

Again, editing the tree or not is not the point. The point is to prove that you are a capable device maintainer for PE. 

It is the same as applying for a school, for a job, for a position in an organization, or for anything similar. You need to prove your capability, for example, through a resume with works you have done. How do you prove it doesn't really matter. Original commits in your device tree is just one way of doing it.

We, as an open source project, cannot simply recruit maintainers based on good faith. We are happy to see that you are making unofficial builds for PE on tulip, and I'm sure users are happy as well. Unfortunately we cannot accept your maintainer application at the current stage. Feel free to come back and apply again in the future.
