### ISSUE TITLE
New maintainer For Twolip

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#2229]
## Device you want to apply for
```
Xiaomi Redmi Note 6pro (Twolip/tulip)
```

## Device tree sources

```
https://github.com/Mishrahpp/device_xiaomi_twolip
https://github.com/Mishrahpp/vendor_xiaomi_twolip
https://github.com/Mishrahpp/vendor_xiaomi_sdm660-common
https://github.com/Mishrahpp/device_xiaomi_sdm660-common
https://github.com/Mishrahpp/mystic_kernel_sdm660-4.4
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@Mishrahpp
```

### GitHub username
```
https://github.com/Mishrahpp
```

**Comment by Hasaber8** [comment]
If those are the trees you are applying with , I'm closing the pr.

**Comment by ghost** [comment]
Can you please explain What's the problem in these trees Please...

**Comment by KakatkarAkshay** [comment]
> Can you please explain What's the problem in these trees Please...

No authorship, you basically deleted .git folder from a repository and did git init again. The fact that you asked that question is enough to close the issue.
