### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by scarymen1325** [PixelExperience/official_devices#2237]
## Device you want to apply for
```
Xiaomi Redmi Note 9S/9 Pro/Pro Max / POCO M2 Pro  (miatoll)
```

## Device tree sources

```
https://github.com/RebornProjectTeam/android_device_xiaomi_sm6250-common/tree/pe
https://github.com/RebornProjectTeam/android_device_xiaomi_miatoll/tree/pe
https://github.com/RebornProjectTeam/miatoll-msm-4.14
https://github.com/RebornProjectTeam/android_vendor_xiaomi_miatoll
https://github.com/RebornProjectTeam/android_vendor_xiaomi_sm6250-common
```

## Number of ROM's you maintain officially
```
3
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@ScaryMen1325
```

### GitHub username
```
@scarymen1325
```

**Comment by Hlcpereira** [comment]
Good morning/afternoon/night

We are not accepting miatoll applications at the moment.

However I can tell that by the fact that you keep updating VENDOR_SECURITY_PATCH flag as if it's related to the actual system security patch, general commiting by yourself, which even includes some kangs as far as I can see shows that, you don't fulfill the requirements, leading to rejecting your application, even if we were accepting miatoll applications.

Fell free to reapply in the future.
Best regards.

**Comment by scarymen1325** [comment]
> Good morning/afternoon/night
> 
> We are not accepting miatoll applications at the moment.
> 
> However I can tell that by the fact that you keep updating VENDOR_SECURITY_PATCH flag as if it's related to the actual system security patch, general commiting by yourself, which even includes some kangs as far as I can see shows that, you don't fulfill the requirements, leading to rejecting your application, even if we were accepting miatoll applications.
> 
> Fell free to reapply in the future.
> Best regards.

What you mean in "kang"? I mean, what files is kanged in sources?

**Comment by Hlcpereira** [comment]
Kang = Stolen work from someone else. Usually refering to commits that were made without the proper authorship. In this case it isn't files that you kanged, and yes changes that you kanged. 

For example: https://github.com/RebornProjectTeam/android_device_xiaomi_sm6250-common/commit/b1367397c183e0660c19e03deee87db4007366f4

Which is an original commit by luk1337: https://github.com/LineageOS/android_device_oneplus_sdm845-common/commit/ebe358dcbfa185e6c70c08e5abc06d2e0dd1dbb6

That also shows that you don't have much of practice with Git, only the basics (clone, add, commit, push), which as per our requirements already make you not to be accepted, and also it does show that you have lack of knowledge/experience with Git, which can afford to say that you don't have much experience, or didn't go far enough yet to get more knowledge, with custom ROM development either.
