### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by SreekanthPalakurthi** [PixelExperience/official_devices#2239]
## Device you want to apply for
```
Phoenix
```

## Device tree sources

```
https://github.com/SreekanthPalakurthi/device_xiaomi_phoenix/tree/eleven
https://github.com/ArrowOS-Devices/android_kernel_xiaomi_phoenix/tree/arrow-11.0
https://github.com/SreekanthPalakurthi/vendor_xiaomi_phoenix/tree/eleven
```

## Number of ROM's you maintain officially
```
1
```

## Any Exceptions/special concern?
```
Extra patch needed - 11437
```

### Telegram username
```
sreekanthpalakurthi
```

### GitHub username
```
sreekanthpalakurthi
```

**Comment by KakatkarAkshay** [comment]
The hardware/xiaomi repo is same as lineage or different?

**Comment by SreekanthPalakurthi** [comment]
same as lineage

**Comment by KakatkarAkshay** [comment]
All right, trees seem good. Force push them with aosp.dependencies instead of arrow.dependencies once you get access to PixelExperience-Devices repos. Make pr on this same repo and wiki if you need any changes there. Also let me know the ci username you want.

**Comment by KakatkarAkshay** [comment]
Also make sure to sign up to gitlab.pixelexperience.org with same username as GitHub for vendor repo access

**Comment by SreekanthPalakurthi** [comment]
Thanks! Can I get ci username as - Sreekanth, please.

> All right, trees seem good. Force push them with aosp.dependencies instead of arrow.dependencies once you get access to PixelExperience-Devices repos. Make pr on this same repo and wiki if you need any changes there. Also let me know the ci username you want.

**Comment by SreekanthPalakurthi** [comment]
> Also make sure to sign up to gitlab.pixelexperience.org with same username as GitHub for vendor repo access

Yes logged in with same username, that is sreekanthpalakurthi

**Comment by KakatkarAkshay** [comment]
> Thanks! Can I get ci username as - Sreekanth, please.
> 
> > All right, trees seem good. Force push them with aosp.dependencies instead of arrow.dependencies once you get access to PixelExperience-Devices repos. Make pr on this same repo and wiki if you need any changes there. Also let me know the ci username you want.

Done, created and sent you credentials in telegram pm. You should have also been added to telegram group already. Now make pull request adding you and eleven version for the device with or without xda thread that's your choice

**Comment by SreekanthPalakurthi** [comment]
Done, https://github.com/PixelExperience/official_devices/pull/2240

> > Thanks! Can I get ci username as - Sreekanth, please.
> > > All right, trees seem good. Force push them with aosp.dependencies instead of arrow.dependencies once you get access to PixelExperience-Devices repos. Make pr on this same repo and wiki if you need any changes there. Also let me know the ci username you want.
> 
> Done, created and sent you credentials in telegram pm. You should have also been added to telegram group already. Now make pull request adding you and eleven version for the device with or without xda thread that's your choice

**Comment by KakatkarAkshay** [comment]
Merged, closing this issue now
