### ISSUE TITLE
fajita: New maintainer

### ISSUE THREAD

**Issue by SevralT** [PixelExperience/official_devices#2252]
## Device you want to apply for
```
OnePlus 6T (fajita)
```

## Device tree sources

```
https://github.com/SevralT/device_oneplus_fajita
https://github.com/SevralT/device_oneplus_sdm845-common
https://github.com/SevralT/device_oneplus_common
https://github.com/LineageOS/android_kernel_oneplus_sdm845/tree/lineage-18.1
https://github.com/SevralT/vendor_oneplus
```

## Number of ROM's you maintain officially
```
2
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
SevralT
```

### GitHub username
```
SevralT
```

**Comment by jjpprrrr** [comment]
Thanks for the application. I would like to ask about the kernel defconfig defined in sdm845-common:

https://github.com/SevralT/device_oneplus_sdm845-common/commit/d54a3de187f612b0c83a354730a1eebc20895378

The TARGET_KERNEL_CONFIG flag specifies enchilada_defconfig as the defconfig, but the kernel repo you provided in your application does not have it. Besides, the kernel is slightly outdated, as the latest 4.9 common kernel is 4.9.270, not 4.9.248.

**Comment by SevralT** [comment]
Oh. Sorry. I switched to LineageOS kernel and forgot to change link.
https://github.com/LineageOS/android_kernel_oneplus_sdm845/tree/lineage-18.1

**Comment by Hlcpereira** [comment]
Very well. Nothing wrong with the trees themselves from my POV too, so consider this application as approved.

The next steps would be:

- Make a pr on this same repo and wiki if you need any changes there. Also let us know the CI username you want.
- Make sure to sign up to gitlab.pixelexperience.org with same username as the CI for vendor repo access

After that any of us will send the CI credentials for you and add you in the Telegram group.

**Comment by SevralT** [comment]
I want "SevralT" username.

**Comment by Hlcpereira** [comment]
Credentials sent over Telegram PM same as adding you to the telegram group. The only thing left would be the PRs

**Comment by Hlcpereira** [comment]
#2260 merged. Closing this issue and welcome aboard.
