### ISSUE TITLE
beyond0lte: New Maintainer

### ISSUE THREAD

**Issue by ECr34T1v3** [PixelExperience/official_devices#2255]
## Device you want to apply for
```
Galaxy S10e (beyond0lte)
```

## Device tree sources

```
https://github.com/ECr34T1v3/android_device_samsung_beyond0lte
https://github.com/ECr34T1v3/android_device_samsung_exynos9820-common
https://github.com/ECr34T1v3/android_vendor_samsung_beyond0lte
https://github.com/ECr34T1v3/android_vendor_samsung_exynos9820-common
https://github.com/ECr34T1v3/android_kernel_samsung_exynos9820
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
ECr34T1v3
```

### GitHub username
```
ECr34T1v3
```

**Comment by Hlcpereira** [comment]
Good afternoon. 

There are still points that need to be made to adjust the trees. With those being:

- FBE is a must if that's the stock behaviour
- Create the aosp.dependencies with all the dependencies that the device will need on the device trees

Other than that I don't see anything wrong or that would make you being rejected at this moment.

Once those points are solved we can go ahead with the officialization of beyond0lte.

**Comment by ECr34T1v3** [comment]
Changes made. FBE re-added, aosp.dependencies and tree rebased. Waiting officialization.

**Comment by Hasaber8** [comment]
CC: @Hlcpereira

**Comment by Hlcpereira** [comment]
The only thing remaining would be the aosp.dependencies on the common-tree, including the remaining dependencies or add the rest of them over the device-specific aosp.dependencies

**Comment by Marcelo-blip-lap** [comment]
I'm hoping this happens!!!! pleaase **officialization** **** 💯

**Comment by Jorg3Lucas** [comment]
@ECr34T1v3 ?

**Comment by ECr34T1v3** [comment]
@Hlcpereira @Jorg3Lucas forgive me for the delay again. Done! aosp.dependencies added to common tree
