### ISSUE TITLE
Please See Once Please new maintainer ( I am Not Spamming)

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#2277]
## Device you want to apply for
```
Redmi Note 6pro (Tulip)
```

## Device tree sources

```
https://github.com/Mishrahpp/device_xiaomi_tulip
https://github.com/Mishrahpp/device_xiaomi_sdm660-common
https://github.com/Mishrahpp/kernel_xiaomi_sdm660
https://github.com/Mishrahpp/vendor_xiaomi_tulip
https://github.com/Mishrahpp/vendor_xiaomi_sdm660-common
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
I know i am not eligble but if You help , i will do all thinks that can make me eligble and also sorry for spamming this is happend because i am not form Computer,coding side i am new learner and i invested some time and getting rejected every time to in firestating i done spamming one again sorry for all
```

### Telegram username
```
@Mishrahpp
```

### GitHub username
```
https://github.com/Mishrahpp
```

**Comment by Mishrahpp** [comment]
I know i am not eligble but if You help , i will do all thinks that can make me eligble and also sorry for spamming this is happend because i am not form Computer,coding side i am new learner and i invested some time and getting rejected every time to in firestating i done spamming one again sorry for all

**Comment by KakatkarAkshay** [comment]
Dude do you have no brain cells?

**Comment by Jorg3Lucas** [comment]
@Mishrahpp At the moment we cannot accept you on the project. As I've explained to you before, at the moment you've already proved to be a newbie and we're looking for more experienced people to represent us. There are still a few months to go before Android 12 is released and I really hope you will continue to strive to evolve and learn more and more from your mistakes to become a good builder (And I know you can do that if you really put in the effort). Until then I wish you good luck and any questions you may have, you can count on me, just talk to me via telegram.
