### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by allanpereira99** [PixelExperience/official_devices#2283]
## Device you want to apply for
```
Mi 8 Lite (platina)
```

## Device tree sources

```
https://github.com/Allansouzadk/android_device_xiaomi_platina/tree/aosp
https://github.com/LineageOS/android_kernel_xiaomi_sdm660
https://github.com/Allansouzadk/proprietary_vendor_xiaomi_platina
https://github.com/PixelExperience-Devices/device_xiaomi_sdm660-common
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sdm660-common
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
Allan_dk
```

### GitHub username
```
Allansouzadk
```

**Comment by Jorg3Lucas** [comment]
Hi, thank you for taking an interest in joining our team.

I ask you to remove the overlay for lineage-sdk and create aop.dependencies as it is needed for official builds.

Device sources are ok for me until now.

**Comment by allanpereira99** [comment]
> Hi, thank you for taking an interest in joining our team.
> 
> I ask you to remove the overlay for lineage-sdk and create aop.dependencies as it is needed for official builds.
> 
> Device sources are ok for me until now.

Ok bro , Just moment

**Comment by allanpereira99** [comment]
done!
tree fixed and aosp.dependecies created

**Comment by Hlcpereira** [comment]
All in all, everything seems to be A-Ok. So consider this application as approved.

The next steps would be:
- Make a pr on this same repo and wiki if you need any changes there. Also let us know the CI username you want.
- Make sure to sign up to gitlab.pixelexperience.org with same username as the CI for vendor repos access

After the PR is merged any of us will send the CI credentials for you and add you in the Telegram group.

Another observation: the firmware repo should also be tracked from gitlab (where the vendor blobs repos are) Once that one is done the deps must be updated too.

**Comment by Allansouzadk** [comment]
> Ao todo, tudo parece estar OK. Portanto, considere este aplicativo como aprovado.
> 
> Os próximos passos seriam:
> 
> * Faça um relatório neste mesmo repositório e wiki se precisar de alguma alteração lá. Informe-nos também o nome de usuário CI que você deseja.
> * Certifique-se de se inscrever em gitlab.pixelexperience.org com o mesmo nome de usuário do CI para acesso a repositor de fornecedores
> 
> Após a fusão do PR, qualquer um de nós enviará as credenciais do CI para você e o adicionará ao grupo do Telegram.
> 
> Outra observação: o repositório de firmware também deve ser rastreado a partir do gitlab (onde estão os repositórios de blobs do fornecedor). Uma vez feito esse repositório, o depto deve ser atualizado também.

ok bro , thanks

**Comment by allanpereira99** [comment]
> All in all, everything seems to be A-Ok. So consider this application as approved.
> 
> The next steps would be:
> 
> * Make a pr on this same repo and wiki if you need any changes there. Also let us know the CI username you want.
> * Make sure to sign up to gitlab.pixelexperience.org with same username as the CI for vendor repos access
> 
> After the PR is merged any of us will send the CI credentials for you and add you in the Telegram group.
> 
> Another observation: the firmware repo should also be tracked from gitlab (where the vendor blobs repos are) Once that one is done the deps must be updated too.

ok bro ,thanks
