### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ocd0711** [PixelExperience/official_devices#2294]
## Device you want to apply for
```
OnePlus 9 (lemonade)
```

## Device tree sources

```
https://github.com/OCD0711/device_oneplus_lemonade.git
https://github.com/OCD0711/device_oneplus_sm8350-common.git
https://github.com/OCD0711/kernel_oneplus_sm8350.git
https://github.com/OCD0711/vendor_oneplus_lemonade.git
https://github.com/OCD0711/vendor_oneplus_sm8350.git
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
OCD2057
```

### GitHub username
```
OCD0711
```

**Comment by Hasaber8** [comment]
Hi, thank you for taking an interest in joining our team.

But the device trees you have attached don't have proper git history, nor do they seem like your own work.

You may try and fix the tree and apply again later.

**Comment by ocd0711** [comment]
> Hi, thank you for taking an interest in joining our team.
> 
> But the device trees you have attached don't have proper git history, nor do they seem like your own work.
> 
> You may try and fix the tree and apply again later.

This project is not done by anyone else. I cleaned up the commit after the local adjustment, so the submission record is very clean.

**Comment by Hasaber8** [comment]
Resetting GIT history isn't called Local Adjustment

**Comment by ocd0711** [comment]
> Resetting GIT history isn't called Local Adjustment

So how should I prove that the project was completed by me?

**Comment by Hasaber8** [comment]
Its not about proving anything, THE FREAKING GIT HISTORY IS MISSING.

**Comment by Hlcpereira** [comment]
> I cleaned up the commit after the local adjustment, so the submission record is very clean.

If anything that's the complete opposite to be done and it's proving the completely opposite of being capable of maintaining a ROM.

The preservation of the commit history and/or the authorship of each commit is a must in most, if not all, custom ROM projects, independently of where the sources originally came from, even more when we are talking about the kernel source repo.

And yes we have it stated in our Maintainers' requirements and Code of Conduct this point.

Best regards.

**Comment by OCD0711** [comment]
Okay, I'll reply after adjusting later.


在 2021年6月25日，下午7:19，Henrique Pereira ***@***.***> 写道：

﻿

I cleaned up the commit after the local adjustment, so the submission record is very clean.

If anything that's the complete opposite to be done and it's proving the completely opposite of being capable of maintaining a ROM.

The preservation of the commit history and/or the authorship of each commit is a must in most, if not all, custom ROM projects, independently of where the sources originally came from, even more when we are talking about the kernel source repo.

And yes we have it stated in our Maintainers' requirements and Code of Conduct this point.

Best regards.
