### ISSUE TITLE
New maintainer for cheeseburger and dumpling

### ISSUE THREAD

**Issue by xLexip** [PixelExperience/official_devices#2304]
## Device you want to apply for
```
cheeseburger
dumpling
```

## Device tree sources

```
https://github.com/xLexip/pe_device_oneplus_msm8998-common
https://github.com/xLexip/pe_device_oneplus_cheeseburger
https://github.com/xLexip/pe_device_oneplus_dumpling
https://github.com/xLexip/pe_kernel_oneplus_msm8998/tree/eleven-stormbreaker
https://github.com/xLexip/pe_vendor_oneplus
```

## Number of ROM's you maintain officially
```
None yet.
PE unofficial since September.
```

## Any Exceptions/special concern?
```
I already switched to the [packages_resources_devicesettings-custom] strings recently,
but there are a few (that i need) missing in the repo atm. I will ofc add and use them from the official repo in case of officialization.

Another point are the "Device Settings". They currently include more features than just the alert slider and button swap settings. 
All those features are fully functional and can also be found in OxygenOS itself. Before I nuke them,
I just want to ask if some of the features can stay there as they are highly demanded by the/my users.
I am especially talking about the vibration strength and panel mode settings here.  
```

### Telegram username
```
xLexip
```

### GitHub username
```
xLexip
```

**Comment by xLexip** [comment]
**These are the mentioned Device Settings:**
![Screenshot_20210703-183658_OnePlus_Settings](https://user-images.githubusercontent.com/46321162/124361284-99179d00-dc2e-11eb-9176-892acaa88924.png)
![Screenshot_20210703-183701_OnePlus_Settings](https://user-images.githubusercontent.com/46321162/124361282-94eb7f80-dc2e-11eb-8776-b0bd0db84c69.png)

**Comment by Hasaber8** [comment]
@xLexip can you push the change you are referring to our Gerrit.
(packages_resources_devicesettings-custom)

**Comment by xLexip** [comment]
@Hasaber8 Sure, done. I also removed the FPS overlay from the device settings.

**https://gerrit.pixelexperience.org/c/packages_resources_devicesettings-custom/+/12487**

**Comment by Hasaber8** [comment]
@xLexip Your device trees and kernel seem fine. Go ahead and PR to official_devices.
This PR will be kept open until the Gerrit stuff is merged.
Also, go ahead and PM me on telegram - @hasaber8
