### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Official-Ayrton990** [PixelExperience/official_devices#2305]
## Device you want to apply for
```
Xiaomi POCO F2 Pro (lmi/lmipro).
```

## Device tree sources

```
https://github.com/Official-Ayrton990/android_device_xiaomi_lmi
https://github.com/Official-Ayrton990/device_xiaomi_sm8250-common
https://github.com/Official-Ayrton990/android_kernel_xiaomi_sm8250
https://github.com/Official-Ayrton990/vendor_xiaomi
```

## Number of ROM's you maintain officially
```
1
```

## Any Exceptions/special concern?
```
Common tree has XiaomiParts just to handle Pop Up camera and  High Touch Polling Rate support (similar to game mode on MIUI).
Kernel tree is always at latest CAF and LTS Tag for SMxx50.0
```

### Telegram username
```
@Ayrton990
```

### GitHub username
```
@Official-Ayrton990
```

**Comment by jjpprrrr** [comment]
Which branch of the kernel repo are you applying with? According to PE's CoC, any form of overclocking or underclocking is not allowed.

**Comment by Official-Ayrton990** [comment]
> 
> 
> Which branch of the kernel repo are you applying with? According to PE's CoC, any form of overclocking or underclocking is not allowed.

Dear jjpprrrr, thanks for your comment:

Branch is upstreamed-common, but the master branch is there in case anyone want to see the kernel changes I made without being lost with the upstreams merged commits. And yes, for roms overclock isn't enabled by default, powerhint is made to make use of 670MHz (for SD870 since it's common) but I can adjust it to use 587MHz only so I can follow PE's CoC strictly.

About High Touch Polling Rate support it's a official feature found on MIUI Gameboost app. We handle what userspace app should do by kernel and using a toggle on XiaoMi parts to enable sysfs node.

**Comment by jjpprrrr** [comment]
> > Which branch of the kernel repo are you applying with? According to PE's CoC, any form of overclocking or underclocking is not allowed.
> 
> Dear jjpprrrr, thanks for your comment:
> 
> Branch is upstreamed-common, but the master branch is there in case anyone want to see the kernel changes I made without being lost with the upstreams merged commits. And yes, for roms overclock isn't enabled by default, powerhint is made to make use of 670MHz (for SD870 since it's common) but I can adjust it to use 587MHz only so I can follow PE's CoC strictly.
> 
> About High Touch Polling Rate support it's a official feature found on MIUI Gameboost app. We handle what userspace app should do by kernel and using a toggle on XiaoMi parts to enable sysfs node.

The touch polling rate is fine. I am aware of Xiaomi's gaming mode stuff on kona. 

Regarding your device tree, there are policy that allows write to generic labels. Here is an example:

https://github.com/Official-Ayrton990/device_xiaomi_sm8250-common/blob/eleven/sepolicy/vendor/hal_fingerprint_default.te#L34

This is against PE maintainer CoC. Please read the CoC carefully and address any violations in your tree. Thank you.

**Comment by Hlcpereira** [comment]
Closing this one as no further conversation happened, therefor treated as a rejected application case. As stated, generic labeling is not permitted as per our Code of Conduct.

Feel free to reapply in the future.
Best regards
