### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mhmdeve** [PixelExperience/official_devices#2308]
## Device you want to apply for
```
Xiaomi Mi 10T/Pro (apollo/apollopro)
```

## Device tree sources

```
https://github.com/mhmdeve/device_xiaomi_apollon
https://github.com/mhmdeve/device_xiaomi_apollon
https://github.com/Ramisky/vendor_xiaomi_apollon
https://github.com/Ramisky/vendor_xiaomi_sm8250-common
https://github.com/Ramisky/kernel_xiaomi_sm8250
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@mhmdeveloper
```

### GitHub username
```
@mhmdeve
```

**Comment by Jorg3Lucas** [comment]
@mhmdeve Hi, thank you for your interest in joining our team. Unfortunately we cannot accept you at this time but we hope that you will continue to give your best to maybe do a new apply in the future.

**Comment by mhmdeve** [comment]
Please Leave a reason

**Comment by Jorg3Lucas** [comment]
> Please Leave a reason

basically the linked device sources are not yours, much less there is a contribution from you in the repositories

From what I've seen, your account was created 17 days ago so you're pretty newbie so far too.

**Comment by Hasaber8** [comment]
> Please Leave a reason

https://github.com/PixelExperience/docs
have a read of the docs, you'll immediately know your mistake.
