### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by afterallafk** [PixelExperience/official_devices#2312]
## Device you want to apply for
```
Redmi 7 (onclite)
```

## Device tree sources

```
https://github.com/afterallafk/device_xiaomi_onclite
https://github.com/LineageOS/android_kernel_xiaomi_onclite
https://github.com/bibarub/android_vendor_xiaomi_onclite
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
afterallafk
```

### GitHub username
```
afterallafk
```

**Comment by Hasaber8** [comment]
Good morning/afternoon,
The application is rejected please learn git and then you may reapply later
