### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ncarvalho99** [PixelExperience/official_devices#2324]
## Device you want to apply for

Redmi S2/Y2 (ysl)

## Device tree sources

https://github.com/nataloppez/android_device_xiaomi_ysl
https://github.com/ItsVixano/android_kernel_xiaomi_ysl
https://github.com/nataloppez/android_vendor_xiaomi_ysl

## Number of ROM's you maintain officially

Only PE+ Unofficial

## Any Exceptions/special concern?

The device was released by the manufacturer with a 32bits system, the head dev at the time (https://github.com/mahajant99) used tissot (Mi A1) to port 64bits for custom roms, so the fp has tissot has base because of that, i only switched to redfin in my last build because all others who build to this device was doing so.

### Telegram username

@onygan

### GitHub username

nataloppez

[json.zip](https://github.com/PixelExperience/official_devices/files/6987460/json.zip)
![19611908-ce8d-45be-be47-05f279199a6c-removebg-preview](https://user-images.githubusercontent.com/47823287/129466036-62d13322-2269-4eaf-ab36-90ae32b59392.png)

**Comment by jjpprrrr** [comment]
Hi! Thanks for submitting the application. I spotted a several violations of PE's CoC. Please go through the CoC carefully and revise accordingly.

Here are some examples:

- Ignoring sepolicy neverallows
  - https://github.com/nataloppez/android_device_xiaomi_ysl/blob/r11.0/BoardConfig.mk#L178
- Write access to generic SELinux labels
  - https://github.com/nataloppez/android_device_xiaomi_ysl/blob/r11.0/sepolicy/system_app.te#L14

**Comment by ncarvalho99** [comment]
> Hi! Thanks for submitting the application. I spotted a several violations of PE's CoC. Please go through the CoC carefully and revise accordingly.
> 
> Here are some examples:
> 
>     * Ignoring sepolicy neverallows
>       
>       * https://github.com/nataloppez/android_device_xiaomi_ysl/blob/r11.0/BoardConfig.mk#L178
> 
>     * Write access to generic SELinux labels
>       
>       * https://github.com/nataloppez/android_device_xiaomi_ysl/blob/r11.0/sepolicy/system_app.te#L14

Hi, sorry about that, this is an additional configuration called Xiaomi Parts that give some extra configurations for the ROM. 
It'll certainly be dropped in next build and i'll drop right now from the device tree
It was only used to see how the community whould react and see if they like it

**Comment by jjpprrrr** [comment]
Not a problem. You can still include features in Parts, if the stock ROM has those features as well.

Regarding sepolicy, if you need to grant write access to a certain node (sysfs in this case), find out what the node is and label it. Granting write access to the whole sysfs context is bad practice and defeats the purpose of SELinux as a security feature.

**Comment by Hlcpereira** [comment]
Just adding up: As @jjpprrrr said, XiaomiParts are fine as long as it does comply with our code of conduct. KCAL Profiles for example are prohibited as per the PE CoC. You may adapt the sources and once done with it feel free to tag in here for a recheck of the sources

**Comment by jjpprrrr** [comment]
There are still generic labels granting write permission. Here's an example:

https://github.com/nataloppez/android_device_xiaomi_ysl/blob/r11.0/sepolicy/hal_health_default.te#L1

**Comment by ncarvalho99** [comment]
Hi, 

Thank you for the help

I have read again PE CoC deeply and revised the device tree, if there's something that goes in disagreement with PE CoC, let me know.

**Comment by jjpprrrr** [comment]
Again, there exists generic SELinux label that grants the write permission. This is the third and the last time I point out the same type of violations in your device tree. It is your device tree, and it __shouldn't__ take too long for you go at least go through each sepolicy file and check for generic labels.

https://github.com/nataloppez/android_device_xiaomi_ysl/blob/r11.0/sepolicy/hal_power_default.te#L1
https://github.com/nataloppez/android_device_xiaomi_ysl/blob/r11.0/sepolicy/hal_vibrator_default.te#L1

The avc denail message in logs and dmesg does not always reflect the real denial, and constructing sepolicy from things like scontext, tcontext and tclass directly may not always be the correct solution. Some sepolicy in your device tree looks like you either generated them from a script or you lack some basic understanding of how sepolicy works. I would suggest that you go through the basic documentation of SELinux from Google [https://source.android.com/security/selinux](url), and perhaps search in places like device/qcom/sepolicy to see how other people handle similar cases.

**Comment by ncarvalho99** [comment]
Hello,

I'm not using any script, my knowledge is a work in progress.

I have lerned a lot in past feel days looking in android enviroment, i focused in other things and forgot to revise the sepolicy again that i thought i had sorted out.

Thank you for your time pointing me the problems, i'll focus on fixing it but i'm closing this New maintainer subscription until i'm fully aware that is everything working.
