### ISSUE TITLE
New maintainer for Realme 2 Pro

### ISSUE THREAD

**Issue by Ad1tyaS1ngh** [PixelExperience/official_devices#2326]
## Device you want to apply for

Realme 2 Pro (r2p)

## Device tree sources

https://github.com/ad1tyas1ngh/device_realme_r2p.git
https://github.com/LineageOS/android_kernel_realme_sdm660
https://github.com/ad1tyas1ngh/vendor_realme_r2p.git

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

No

### Telegram username

@Ad1tyaS1ngh

### GitHub username

ad1tyas1ngh

**Comment by Hasaber8** [comment]
Kernel repo doesn't exist.
Please update it with the correct link.

**Comment by Ad1tyaS1ngh** [comment]
> Kernel repo doesn't exist.
> Please update it with the correct link.

Fixed

**Comment by Ad1tyaS1ngh** [comment]
Guys can anyone review?

**Comment by Hasaber8** [comment]
+1 from me, @Hlcpereira

**Comment by Hlcpereira** [comment]
So far so good for me. You can open a PR for this repo and also another one for the wiki repo. While at that someone from the core team will send you the link for our maintainers chat and request you some more details. This Issue will be closed once everything is set

**Comment by Ad1tyaS1ngh** [comment]
I have opened both the PRs, thanks.
