### ISSUE TITLE
New maintainer for Lenovo Z5s (jd2019)

### ISSUE THREAD

**Issue by lzgmc** [PixelExperience/official_devices#2328]
## Device you want to apply for

Lenovo Z5s (jd2019)

## Device tree sources

https://github.com/lenovo-sdm710/device_lenovo_jd2019
https://github.com/lenovo-sdm710/device_lenovo_sdm710-common
https://github.com/lenovo-sdm710/kernel_lenovo_sdm710
https://github.com/lenovo-sdm710/vendor_lenovo_jd2019
https://github.com/lenovo-sdm710/vendor_lenovo_sdm710-common
https://gitlab.com/victor10520/vendor_lenovo-firmware

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

@lzgmc

### GitHub username

lzgmc

**Comment by Hasaber8** [comment]
@Hlcpereira seems fine to me

**Comment by Jorg3Lucas** [comment]
@lzgmc  Make a pull request on official_devices and on the wiki by adding your device. This issue will remain open until you finish what was requested.

**Comment by lzgmc** [comment]
PRs submitted.
