### ISSUE TITLE
New maintainer for Surya/Karna 

### ISSUE THREAD

**Issue by CHRISL7** [PixelExperience/official_devices#2331]
## Device you want to apply for

Poco X3/X3 NFC - Surya/Karna

## Device tree sources

https://github.com/ChrisW444/android_device_xiaomi_surya
https://github.com/ChrisW444/vendor_xiaomi_surya
https://github.com/ChrisW444/kernel_xiaomi_surya

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

No

### Telegram username

@CHRISL7

### GitHub username

@ChrisW444

**Comment by Hasaber8** [comment]
Please drop MotoDolby you can't be using that, as it isnt a stock feature

**Comment by CHRISL7** [comment]
> Please drop MotoDolby you can't be using that, as it isnt a stock feature

- yes, now it's all right

**Comment by Hasaber8** [comment]
> > Please drop MotoDolby you can't be using that, as it isnt a stock feature
> 
> * yes, now it's all right

Not yet.
https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/vendor.prop#L119..L124
https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/vendor.prop#L177
https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/configs/audio/audio_effects.xml#L46
https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/configs/audio/audio_effects.xml#L97
https://github.com/ChrisW444/android_device_xiaomi_surya/tree/eleven/sepolicy/vendor - all dolby sepolicy are still there. Clean up the history properly.

**Comment by CHRISL7** [comment]
> > > Please drop MotoDolby you can't be using that, as it isnt a stock feature
> > 
> > 
> > 
> > * yes, now it's all right
> 
> Not yet.
> https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/vendor.prop#L119..L124
> https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/vendor.prop#L177
> https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/configs/audio/audio_effects.xml#L46
> https://github.com/ChrisW444/android_device_xiaomi_surya/blob/eleven/configs/audio/audio_effects.xml#L97
> https://github.com/ChrisW444/android_device_xiaomi_surya/tree/eleven/sepolicy/vendor - all dolby sepolicy are still there. Clean up the history properly.

Yes, I had just dropped it from the vendor. Thanks, look at the latest commit again

**Comment by Jorg3Lucas** [comment]
@ChrisW444 A rebase would be better than this commit: https://github.com/ChrisW444/android_device_xiaomi_surya/commit/209356a22881baf91861f158c9163a011a2f8288

**Comment by CHRISL7** [comment]
>  @Jorg3Lucas Look now

**Comment by Jorg3Lucas** [comment]
Some overlays can be removed but other than that I think it's ok. any objections? @KakatkarAkshay @Hlcpereira

**Comment by Hasaber8** [comment]
https://github.com/ChrisW444/kernel_xiaomi_surya/tree/eleven/AnyKernel3 - drop this please
https://github.com/ChrisW444/kernel_xiaomi_surya/commit/8de3f59675ff5c2ec55a906e1f481a19c926f959 - adapt this to PE
https://github.com/ChrisW444/kernel_xiaomi_surya/commit/cb63f312211dcba9ad6fab984f6b7a0560207ea8

https://github.com/ChrisW444/kernel_xiaomi_surya/commit/31d1bfdfd6ef53f1264fc2862a84fda4987e6ebd

- i recommend against using these

**Comment by CHRISL7** [comment]
> @Hasaber8 Done, changes tested too.
