### ISSUE TITLE
New maintainer For Redmi Note 6pro

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#2335]
## Device you want to apply for

Redmi Note 6pro (tulip)

## Device tree sources

https://github.com/arturo51236/device_xiaomi_tulip
https://github.com/Sixzz9/kernel-xiaomi-sdm660
https://github.com/arturo51236/vendor_xiaomi_tulip

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

I am building PE unofficially for tulip I recently Pushed 2 public build and it's getting 100+ users So I request you to please Officialize Mee for tulip https://t.me/tulipofficial/731730

### Telegram username

BharatSingh1008

### GitHub username

https://github.com/BharatSingh1008-pixel

**Comment by Hasaber8** [comment]
Submitted Device Tree's don't belong to the person submitting the tree's for review.
