### ISSUE TITLE
New vayu/bhima maintainer

### ISSUE THREAD

**Issue by Bagualisson** [PixelExperience/official_devices#2338]
## Device you want to apply for

Poco X3 Pro (Vayu)

## Device tree sources

https://github.com/AlissonGrizotti/device_xiaomi_vayu
https://github.com/AlissonGrizotti/kernel_xiaomi_vayu
https://github.com/AlissonGrizotti/vendor_xiaomi_vayu

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

No

### Telegram username

@Bagualisson

### GitHub username

AlissonGrizotti

**Comment by Jorg3Lucas** [comment]
Drop parts strings in your device tree and use from https://github.com/PixelExperience/packages_resources_devicesettings-custom

**Comment by Bagualisson** [comment]
> Drop parts strings in your device tree and use from https://github.com/PixelExperience/packages_resources_devicesettings-custom

Done, pls check if alright
https://github.com/AlissonGrizotti/device_xiaomi_vayu

**Comment by Jorg3Lucas** [comment]
ok, make a PR
