### ISSUE TITLE
New maintainer For Redmi Note 6pro

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#2342]
## Device you want to apply for

Redmi Note 6pro (tulip)

## Device tree sources

https://github.com/PinCredible/device_xiaomi_tulip
https://github.com/PinCredible/device_xiaomi_tulip-common
https://github.com/PinCredible/vendor_xiaomi_tulip
https://github.com/PinCredible/vendor_xiaomi_tulip-common
https://github.com/PinCredible/kernel-xiaomi-sdm660

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

Sir i am Bulding unoffically builds and providing in tg group 
SourceForge : https://sourceforge.net/projects/pe-plus-edition-for-tulip/files/

### Telegram username

@PinCredible

### GitHub username

https://github.com/PinCredible

**Comment by PinCredible** [comment]
Any Update

**Comment by PinCredible** [comment]
Any Update ?

**Comment by PinCredible** [comment]
Sir please give some update ?

**Comment by Jorg3Lucas** [comment]
Hi, sorry but we can't accept you right now as you don't meet all the requirements

**Comment by ghost** [comment]
Sir please can you explain that can i improve in future
