### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AndroX2** [PixelExperience/official_devices#2347]
## Device you want to apply for

Realme X2

## Device tree sources

https://github.com/AndroX2/nad-device_realme_X2
https://github.com/AndroX2/kernel_realme_sm6150
https://github.com/AndroX2/vendor_realme_X2

## Number of ROM's you maintain officially

currently no rom
But maintaining pe from may,2021

## Any Exceptions/special concern?

selinux permissive

### Telegram username

@Chayan_H

### GitHub username

AndroX2

**Comment by Jorg3Lucas** [comment]
Hello, unfortunately you do not meet our minimum requirements
