### ISSUE TITLE
New maintainer for Redmi 9 Prime/Poco M2 (lava)

### ISSUE THREAD

**Issue by SakthivelNadar** [PixelExperience/official_devices#2350]
## Device you want to apply for

Redmi 9 Prime/Poco M2 unified (lava)

## Device tree sources

https://github.com/Redmi-MT6768/android_device_xiaomi_lava/tree/eleven
https://github.com/Redmi-MT6768/android_device_xiaomi_mt6768-common/tree/eleven
https://github.com/Redmi-MT6768/android_kernel_xiaomi_mt6768
https://github.com/Redmi-MT6768/android_vendor_xiaomi_lava

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

SakthivelNadar

### GitHub username

SparXFusion

**Comment by Hasaber8** [comment]
Good morning/afternoon/evening.
Unfortunately we are freezing new device intake until we start A12 stable builds.

**Comment by Sushrut1101** [comment]
> Good morning/afternoon/evening.
> Unfortunately we are freezing new device intake until we start A12 stable builds.

Ah Okay...
