### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by eualexandrerrr** [PixelExperience/official_devices#2362]
## Device you want to apply for

Poco F2 Pro (lmi)

## Device tree sources

https://github.com/mamutal91/device_xiaomi_lmi
https://github.com/mamutal91/device_xiaomi_sm8250-common
https://github.com/mamutal91/kernel_xiaomi_sm8250
https://github.com/mamutal91/vendor_xiaomi_lmi
https://github.com/mamutal91/vendor_xiaomi_sm8250-common

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

@mamutal91

### GitHub username

@mamutal91

**Comment by Hlcpereira** [comment]
Just to register: Despite we are closed for applications, an exception regarding mamutal's was given. Therefor the application process **can, and will** be taken in a normal way.

**Comment by Jorg3Lucas** [comment]
@mamutal91 make a pr
