### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ralph950412** [PixelExperience/official_devices#2394]
## Device you want to apply for
```
Mi Pad 4/4 Plus
```

## Device tree sources

```
https://github.com/xiaomi-sdm660/android_device_xiaomi_sdm660-common
https://github.com/pix106/android_kernel_xiaomi_sdm660_southwest
https://github.com/xiaomi-sdm660/android_vendor_xiaomi_sdm660-common
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
Tofu ;)
```

### GitHub username
```
ralph950412
```

**Comment by Hasaber8** [comment]
For now our applications are closed. Please reapply once we open them.

**Comment by Jorg3Lucas** [comment]
Hello @ralph950412 !
hope you're fine! We are currently refusing new devices during the BETA phase, we will reopen again next year, so be aware of new news and improve your knowledge.

Best Regards,
Jorge
