### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by qwertyuiii-code** [PixelExperience/official_devices#2407]
## Device you want to apply for

Redmi 6/6a

## Device tree sources

https://github.com/kbt69/android_device_xiaomi_certus
https://github.com/kbt69/android_kernel_xiaomi_mt6765/
https://github.com/kbt69/proprietary_vendor_xiaomi

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

Volte 

### Telegram username

@Chikoni_UwU

### GitHub username

qwertyuui-code

**Comment by Jorg3Lucas** [comment]
@qwertyuiii-code hello, thank you for your interest to be part of our team but unfortunately your sources do not meet all the minimum requirements required in our CoC, I saw that you have little experience in development, I recommend that you study a little more before trying to apply again.

best regards,
Jorge
