### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by dereference23** [PixelExperience/official_devices#2413]
## Device you want to apply for

miatoll

## Device tree sources

https://github.com/Positron-Foundation/android_device_xiaomi_miatoll
https://github.com/Positron-Foundation/android_device_xiaomi_sm6250-common
https://github.com/LineageOS/android_kernel_xiaomi_sm6250
https://gitlab.com/the-muppets/proprietary_vendor_xiaomi

## Number of ROM's you maintain officially

2 ROMs: LineageOS and Project Fluid

## Any Exceptions/special concern?

No

### Telegram username

dereference

### GitHub username

dereference23

**Comment by Hlcpereira** [comment]
Hello, the only doubt around this application is about the state of the device on twelve, that being the bugs that are still present and if the device is actually functional for daily driving (not to mention the luck that we had in the last two times we had in our roster this device :sweat_smile:). So having just two points answered would be useful to get a final answer on this application, as nothing wrong was found on the device source themselves.

**Comment by dereference23** [comment]
> Hello, the only doubt around this application is about the state of the device on twelve, that being the bugs that are still present and if the device is actually functional for daily driving (not to mention the luck that we had in the last two times we had in our roster this device sweat_smile). So having just two points answered would be useful to get a final answer on this application, as nothing wrong was found on the device source themselves.

FM radio doesn't work for some users and there are some minor mic issues. Overall it's completely suitable for daily driving, there are many good responses from users.

**Comment by Hlcpereira** [comment]
@dereference23 please open a PR for both official_devices and wiki repos to add miatoll in the roster.
