### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by maluueu** [PixelExperience/official_devices#2417]
## Device you want to apply for

Xiaomi Mi 10 Lite 5G (monet)

## Device tree sources

https://github.com/maluueu-android-development/android_device_xiaomi_monet/ (eleven/eleven-plus/twelve)
https://github.com/maluueu-android-development/android_device_xiaomi_sm7250-common/ (eleven/eleven-plus/twelve)

https://github.com/maluueu-android-development/android_kernel_xiaomi_sm7250/ (eleven/twelve)

https://gitlab.com/maluueu/android_vendor_xiaomi_monet/ (eleven/twelve)

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

I have been unofficially maintaining Monet for 6-7 months now. [XDA Link here](https://forum.xda-developers.com/t/rom-11-monet-pixelexperience-plus-aosp-unofficial.4333241/)
It runs without any issues or bugs (A11), even the A12 Beta is stable enough to use as a daily driver, no bugs whatsoever.

### Telegram username

maluueu

### GitHub username

maluueu (Personal)
maluueu-android-development (Org where my device stuff lives)

**Comment by Hasaber8** [comment]
That patch was abandoned as we're not going to support custom perf hints, so lineage power hal isn't needed

**Comment by maluueu** [comment]
> That patch was abandoned as we're not going to support custom perf hints, so lineage power hal isn't needed

Yeah, thanks. I already saw that the patch was abandoned and will remove lineage power hal.

**Comment by maluueu** [comment]
@Hasaber8 I dropped vangogh for now, I will later apply for vangogh too.
For now I will focus on monet.

**Comment by maluueu** [comment]
@Hasaber8 all repos are pushed now and should be ready.

**Comment by Jorg3Lucas** [comment]
@maluueu Helloo, I hope you're well
We don't have lineage-sdk in Pixel Experience, if necessary move to normal overlays folder,
after that please do a PR by adding you and your device to our official_devices and wiki!

https://github.com/maluueu-android-development/android_device_xiaomi_sm7250-common/tree/twelve/overlay/lineage-sdk

**Comment by maluueu** [comment]
@Jorg3Lucas Hey, yes thank you, I hope you do too :)
I will change the overlay and finalize the official_devices and the wiki PRs.
I will tell you when I'm done.

**Comment by maluueu** [comment]
@Jorg3Lucas I did a night shift and everything should be fine now. The PRs are done too.
