### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Atlas78** [PixelExperience/official_devices#2426]
## Device you want to apply for

Realme 6

## Device tree sources

https://github.com/Atlas78/device_realme_RM6785
https://github.com/Atlas78/kernel_realme_mt6785
https://github.com/Atlas78/vendor_realme

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

@tlas78

### GitHub username

Atlas78

**Comment by ZIDAN44** [comment]
Hello!

As per CoC requarments permissive sepolicy are not allowed. Pls read CoC requarments.

https://github.com/PixelExperience/docs/blob/master/device_requirements.md#:~:text=The%20device%20MUST%20have%20SELinux%20Enforcing%20to%20release%20builds.%20During%20Beta%20Stage%20builds%20it%27s%20allowed%20to%20have%20SELinux%20Permissive.
