### ISSUE TITLE
New Maintainer For Lavender

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#2436]
## Device you want to apply for

Xiaomi Redmi Note 7/7S (Lavender)

## Device tree sources

https://github.com/inferno964/android_device_xiaomi_lavender
https://github.com/inferno964/vendor_xiaomi_lavender
https://github.com/inferno964/android_kernel_xiaomi_lavender

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

Everything is totally fine.
I'm doing unofficial builds on R & S since october regularly. Users are highly satisfied.

### Telegram username

@inferno964

### GitHub username

@inferno964

**Comment by ghost** [comment]
Any Updates Team ?

**Comment by ZIDAN44** [comment]
As you are using common trees and those are already exits and active in PixelExperience-Devices org so adapt your changes with it or use Standalone tree. Check CoC requarments.

**Comment by ghost** [comment]
> As you are using common trees and those are already exits and active in PixelExperience-Devices org so adapt your changes with it or use Standalone tree. Check CoC requarments.

Okay , I'll Adapt the common trees from pixel exp. device org and make the necessary changes required.

**Comment by faham1997** [comment]
From what i see, the common tree and device tree are not in sync with each other. Moreover, multiple violations of CoC requirements. If you may want, I can write in a detailed sheet and present here for you.

**Comment by protonmailtp** [comment]
Buildbot gang, we don't need u 🤣

**Comment by protonmailtp** [comment]
Agreed with @faham1997

**Comment by protonmailtp** [comment]
Take other's dt, kernel, rename it, be author of 0 commits, build 5-6 officials. Get new buggg, wait for others to fix it, cherrypick it, beeld bot again and go one. I really don't want this happen with some very Good custom rom like PixelExperience @inferno964

**Comment by protonmailtp** [comment]
@ZIDAN44 please look into this matter, I'm not joking, really don't want buildbots to take over pe

**Comment by protonmailtp** [comment]
Also he already has 4 or 5 officials, don't think it is possible for him to deliver proper support.

**Comment by inferno964** [comment]
> Take other's dt, kernel, rename it, be author of 0 commits, build 5-6 officials. Get new buggg, wait for others to fix it, cherrypick it, beeld bot again and go one. I really don't want this happen with some very Good custom rom like PixelExperience @inferno964 

I only have 2 official roms and you can check my organization for that , the team can check the trees themselves and see my commits. Moreover this is just a fake account created to spam against me. You're way of commenting actually proves it. The decision lies with the PE team.

**Comment by protonmailtp** [comment]
You should take recommendation from @faham1997 who had maintained lavender and knows who is buildbot snd who isn't

**Comment by ghost** [comment]
> From what i see, the common tree and device tree are not in sync with each other. Moreover, multiple violations of CoC requirements. If you may want, I can write in a detailed sheet and present here for you. 

Keeping @ZIDAN44 points in mind , I'll make sure to make the necessary changes while switching with the already existing common trees on source org. I've tested it. Moreover if things doesn't go well then I'll switch with the standalone trees.

**Comment by ghost** [comment]
As mentioned above , the common trees will be used from source and the application links have been updated.

**Comment by Jorg3Lucas** [comment]
the device is already being developed by another dev.

**Comment by ghost** [comment]
That person didn't even released any unofficial build. And I think either it's the alternate account of the old maintainer , or he's the part of pe team. Rest the team knows.

**Comment by Quarkin** [comment]
yeah that's what we all think as there were hints before all this. Tbh chinese gets banged everywhere
