### ISSUE TITLE
New maintainer Samsung Galaxy S10&N10 Series

### ISSUE THREAD

**Issue by Orel6505** [PixelExperience/official_devices#2450]
## Device you want to apply for

beyond0lte, beyond1lte, beyond2lte, beyondx, d1, d2s, d2x

## Device tree sources

https://github.com/Orel6505/android_device_samsung_beyond0lte/tree/PE-12
https://github.com/Orel6505/android_device_samsung_beyond1lte/tree/PE-12
https://github.com/Orel6505/android_device_samsung_beyond2lte/tree/PE-12
https://github.com/Orel6505/android_device_samsung_beyondx/tree/PE-12
https://github.com/Orel6505/android_device_samsung_d1/tree/PE-12
https://github.com/Orel6505/android_device_samsung_d2s/tree/PE-12
https://github.com/Orel6505/android_device_samsung_d2x/tree/PE-12
https://github.com/Orel6505/android_device_samsung_exynos9820-common/tree/PE-12
https://github.com/TheMuppets/proprietary_vendor_samsung
https://github.com/LineageOS/android_kernel_samsung_exynos9820
https://github.com/Orel6505/android_hardware_samsung/tree/PE-12
https://github.com/LineageOS/android_device_samsung_slsi_sepolicy

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

link for unofficial XDA treads:
A11: https://forum.xda-developers.com/t/rom-unofficial-11-galaxy-s10-e-pixelexperience-plus-aosp-encryption.4342919/
A12: https://forum.xda-developers.com/t/rom-unofficial-12-galaxy-s10-e-5g-pixelexperience-aosp-encryption.4368775/

### Telegram username

@Orel6505

### GitHub username

@Orel6505

**Comment by Orel6505** [comment]
@Hasaber8

**Comment by Orel6505** [comment]
Kernel in LineageOS gerrit.

**Comment by Orel6505** [comment]
I want to prove that I built and it booted:
![IMG_20211222_205944_244.jpg](https://user-images.githubusercontent.com/85583144/147142088-2d326a82-4378-46ea-ac00-c130d342f692.jpg)

**Comment by Orel6505** [comment]
Can someone look at my apply maintain please, I'm waiting 5 days

**Comment by dereference23** [comment]
Wouldn't it be more fair to review applications in FIFO order?

**Comment by Hasaber8** [comment]
> Wouldn't it be more fair to review applications in FIFO order?

How about some patients 😄

**Comment by Hlcpereira** [comment]
Hello, hope you are doing fine. I'm sorry to give you the news that this application was rejected.

"Why?"
It all came down when starting looking on you experience with ROM development, so the main factor in the decision was the lack of experience.

However I wouldn't say that it's a doors closed for forever, feel free to reapply in the future once you have more experience.

Best regards

**Comment by Orel6505** [comment]
3 months of building PE for S10 doesn't enough???

**Comment by KakatkarAkshay** [comment]
3 months of building but it has no original work by you. It's all done by lineage team

**Comment by Orel6505** [comment]
> Hello, hope you are doing fine. I'm sorry to give you the news that this application was rejected.
> 
> "Why?"
> It all came down when starting looking on you experience with ROM development, so the main factor in the decision was the lack of experience.
> 
> However I wouldn't say that it's a doors closed for forever, feel free to reapply in the future once you have more experience.
> 
> Best regards

Tell me why you rejected me, I can't understand.

**Comment by Orel6505** [comment]
@Linux4 trees are the best for my phone, and I don't see why I can't use them for official PE if they're already official lineage

**Comment by DaniAsh551** [comment]
@KakatkarAkshay That is a stupid reason which I do not think is justified.

If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?

Would this not slow down the progress of PE on multiple devices?

**Comment by KakatkarAkshay** [comment]
> @KakatkarAkshay That is a stupid reason which I do not think is justified.
> 
> If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> 
> Would this not slow down the progress of PE on multiple devices?

You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.

**Comment by DaniAsh551** [comment]
> > @KakatkarAkshay That is a stupid reason which I do not think is justified.
> > If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> > Would this not slow down the progress of PE on multiple devices?
> 
> You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.

I am sorry, but your answers ring hollow to me and seem like that these answers are basically non answers.

If you really want to know, you can check the work of the LOS source maintainers and how actively they maintain the sources. Its OSS so you could just go and check instead of claiming that there is no way to know. The trees and sources used are listed above.

Also, I am not affiliated with the applicant, this is not my work, but this is saddening that a well supported device is rejected because it is well supported and maintained.

**Comment by ZIDAN44** [comment]
> > > @KakatkarAkshay That is a stupid reason which I do not think is justified.
> > > If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> > > Would this not slow down the progress of PE on multiple devices?
> > 
> > 
> > You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.
> 
> I am sorry, but your answers ring hollow to me and seem like that these answers are basically non answers.
> 
> If you really want to know, you can check the work of the LOS source maintainers and how actively they maintain the sources. Its OSS so you could just go and check instead of claiming that there is no way to know. The trees and sources used are listed above.
> 
> Also, I am not affiliated with the applicant, this is not my work, but this is saddening that a well supported device is rejected because it is well supported and maintained.

Only cloning good trees aren't enough you also need more experience in ROM building that's he mean.

**Comment by jjpprrrr** [comment]
> > > @KakatkarAkshay That is a stupid reason which I do not think is justified.
> > > If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> > > Would this not slow down the progress of PE on multiple devices?
> > 
> > 
> > You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.
> 
> I am sorry, but your answers ring hollow to me and seem like that these answers are basically non answers.
> 
> If you really want to know, you can check the work of the LOS source maintainers and how actively they maintain the sources. Its OSS so you could just go and check instead of claiming that there is no way to know. The trees and sources used are listed above.
> 
> Also, I am not affiliated with the applicant, this is not my work, but this is saddening that a well supported device is rejected because it is well supported and maintained.

Just a few words as a core team member of PE. We would like to recruit maintainers that are able to fix issues and make improvements individually instead of simply tracking every change Lineage makes. Yes, the device is currently well maintained by Lineage, but that does not mean it will always be like that in the future, and not everything from Lineage is applicable to PE.

Why is this important? Take OnePlus 6/6t as an example. Our previous maintainer for OP6/6t followed everything from Lineage. It was all good in android 11 because most things worked, and luk from Lineage maintained the device in a good form. Android 12 was released, and without luk's active commits on OP6/6t, our maintainer was not able to fix everything and provide a good experience for PE12. Eventually we had to drop OP6/6t support.

This is exactly the case we would like to avoid. I am not saying that the original applicant of S10/N10 isn't capable. It's just from the current code shown above, there is no way for us to tell how much the applicant knows and how well the applicant will be able to maintain this device (alone, not depending on Lineage) going forward. This is why we decided to hold on to the application. As Henrique said above, "However I wouldn't say that it's a doors closed for forever, feel free to reapply in the future once you have more experience."

**Comment by DaniAsh551** [comment]
> > > > @KakatkarAkshay That is a stupid reason which I do not think is justified.
> > > > If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> > > > Would this not slow down the progress of PE on multiple devices?
> > > 
> > > 
> > > You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.
> > 
> > 
> > I am sorry, but your answers ring hollow to me and seem like that these answers are basically non answers.
> > If you really want to know, you can check the work of the LOS source maintainers and how actively they maintain the sources. Its OSS so you could just go and check instead of claiming that there is no way to know. The trees and sources used are listed above.
> > Also, I am not affiliated with the applicant, this is not my work, but this is saddening that a well supported device is rejected because it is well supported and maintained.
> 
> Just a few words as a core team member of PE. We would like to recruit maintainers that are able to fix issues and make improvements individually instead of simply tracking every change Lineage makes. Yes, the device is currently well maintained by Lineage, but that does not mean it will always be like that in the future, and not everything from Lineage is applicable to PE.
> 
> Why is this important? Take OnePlus 6/6t as an example. Our previous maintainer for OP6/6t followed everything from Lineage. It was all good in android 11 because most things worked, and luk from Lineage maintained the device in a good form. Android 12 was released, and without luk's active commits on OP6/6t, our maintainer was not able to fix everything and provide a good experience for PE12. Eventually we had to drop OP6/6t support.
> 
> This is exactly the case we would like to avoid. I am not saying that the original applicant of S10/N10 isn't capable. It's just from the current code shown above, there is no way for us to tell how much the applicant knows and how well the applicant will be able to maintain this device (alone, not depending on Lineage) going forward. This is why we decided to hold on to the application. As Henrique said above, "However I wouldn't say that it's a doors closed for forever, feel free to reapply in the future once you have more experience."

I can understand this, but I cannot understand why it is undesirable to give a device support in PE for some time and then drop it instead of having no support from the beginning.

**Comment by jjpprrrr** [comment]
> > > > > @KakatkarAkshay That is a stupid reason which I do not think is justified.
> > > > > If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> > > > > Would this not slow down the progress of PE on multiple devices?
> > > > 
> > > > 
> > > > You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.
> > > 
> > > 
> > > I am sorry, but your answers ring hollow to me and seem like that these answers are basically non answers.
> > > If you really want to know, you can check the work of the LOS source maintainers and how actively they maintain the sources. Its OSS so you could just go and check instead of claiming that there is no way to know. The trees and sources used are listed above.
> > > Also, I am not affiliated with the applicant, this is not my work, but this is saddening that a well supported device is rejected because it is well supported and maintained.
> > 
> > 
> > Just a few words as a core team member of PE. We would like to recruit maintainers that are able to fix issues and make improvements individually instead of simply tracking every change Lineage makes. Yes, the device is currently well maintained by Lineage, but that does not mean it will always be like that in the future, and not everything from Lineage is applicable to PE.
> > Why is this important? Take OnePlus 6/6t as an example. Our previous maintainer for OP6/6t followed everything from Lineage. It was all good in android 11 because most things worked, and luk from Lineage maintained the device in a good form. Android 12 was released, and without luk's active commits on OP6/6t, our maintainer was not able to fix everything and provide a good experience for PE12. Eventually we had to drop OP6/6t support.
> > This is exactly the case we would like to avoid. I am not saying that the original applicant of S10/N10 isn't capable. It's just from the current code shown above, there is no way for us to tell how much the applicant knows and how well the applicant will be able to maintain this device (alone, not depending on Lineage) going forward. This is why we decided to hold on to the application. As Henrique said above, "However I wouldn't say that it's a doors closed for forever, feel free to reapply in the future once you have more experience."
> 
> I can understand this, but I cannot understand why it is undesirable to give a device support in PE for some time and then drop it instead of having no support from the beginning.

This is an opinionated project, and you don't have to agree with everything we do. I guess we put quality over quantity.

An unexperienced maintainer also creates more problems than adding support for now and dropping it later.

**Comment by DaniAsh551** [comment]
> > > > > > @KakatkarAkshay That is a stupid reason which I do not think is justified.
> > > > > > If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> > > > > > Would this not slow down the progress of PE on multiple devices?
> > > > > 
> > > > > 
> > > > > You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.
> > > > 
> > > > 
> > > > I am sorry, but your answers ring hollow to me and seem like that these answers are basically non answers.
> > > > If you really want to know, you can check the work of the LOS source maintainers and how actively they maintain the sources. Its OSS so you could just go and check instead of claiming that there is no way to know. The trees and sources used are listed above.
> > > > Also, I am not affiliated with the applicant, this is not my work, but this is saddening that a well supported device is rejected because it is well supported and maintained.
> > > 
> > > 
> > > Just a few words as a core team member of PE. We would like to recruit maintainers that are able to fix issues and make improvements individually instead of simply tracking every change Lineage makes. Yes, the device is currently well maintained by Lineage, but that does not mean it will always be like that in the future, and not everything from Lineage is applicable to PE.
> > > Why is this important? Take OnePlus 6/6t as an example. Our previous maintainer for OP6/6t followed everything from Lineage. It was all good in android 11 because most things worked, and luk from Lineage maintained the device in a good form. Android 12 was released, and without luk's active commits on OP6/6t, our maintainer was not able to fix everything and provide a good experience for PE12. Eventually we had to drop OP6/6t support.
> > > This is exactly the case we would like to avoid. I am not saying that the original applicant of S10/N10 isn't capable. It's just from the current code shown above, there is no way for us to tell how much the applicant knows and how well the applicant will be able to maintain this device (alone, not depending on Lineage) going forward. This is why we decided to hold on to the application. As Henrique said above, "However I wouldn't say that it's a doors closed for forever, feel free to reapply in the future once you have more experience."
> > 
> > 
> > I can understand this, but I cannot understand why it is undesirable to give a device support in PE for some time and then drop it instead of having no support from the beginning.
> 
> This is an opinionated project, and you don't have to agree with everything we do. I guess we put quality over quantity.
> 
> An unexperienced maintainer also creates more problems than adding support for now and dropping it later.

I understand that any project is subject to the developer/maintainers' opinions.

And don't get me wrong, I have the utmost respect for this project and the people involved, I am just trying my best to get a clear understanding of the process here, so please bear with me.

If a device has all that is needed for PE on their LOS port, and I use the sources from LOS and make none of my own changes to the sources (simply because none are needed), how could an applicant prove that they are indeed capable of maintaining?

**Comment by jjpprrrr** [comment]
> > > > > > > @KakatkarAkshay That is a stupid reason which I do not think is justified.
> > > > > > > If there are good sources available and the maintainer of these sources update and maintain it properly, should we not use them and instead just try to get the same results by ourselves?
> > > > > > > Would this not slow down the progress of PE on multiple devices?
> > > > > > 
> > > > > > 
> > > > > > You have no other experience in building roms, if someone has experience then using those sources is fine but in your case we have no way to know.
> > > > > 
> > > > > 
> > > > > I am sorry, but your answers ring hollow to me and seem like that these answers are basically non answers.
> > > > > If you really want to know, you can check the work of the LOS source maintainers and how actively they maintain the sources. Its OSS so you could just go and check instead of claiming that there is no way to know. The trees and sources used are listed above.
> > > > > Also, I am not affiliated with the applicant, this is not my work, but this is saddening that a well supported device is rejected because it is well supported and maintained.
> > > > 
> > > > 
> > > > Just a few words as a core team member of PE. We would like to recruit maintainers that are able to fix issues and make improvements individually instead of simply tracking every change Lineage makes. Yes, the device is currently well maintained by Lineage, but that does not mean it will always be like that in the future, and not everything from Lineage is applicable to PE.
> > > > Why is this important? Take OnePlus 6/6t as an example. Our previous maintainer for OP6/6t followed everything from Lineage. It was all good in android 11 because most things worked, and luk from Lineage maintained the device in a good form. Android 12 was released, and without luk's active commits on OP6/6t, our maintainer was not able to fix everything and provide a good experience for PE12. Eventually we had to drop OP6/6t support.
> > > > This is exactly the case we would like to avoid. I am not saying that the original applicant of S10/N10 isn't capable. It's just from the current code shown above, there is no way for us to tell how much the applicant knows and how well the applicant will be able to maintain this device (alone, not depending on Lineage) going forward. This is why we decided to hold on to the application. As Henrique said above, "However I wouldn't say that it's a doors closed for forever, feel free to reapply in the future once you have more experience."
> > > 
> > > 
> > > I can understand this, but I cannot understand why it is undesirable to give a device support in PE for some time and then drop it instead of having no support from the beginning.
> > 
> > 
> > This is an opinionated project, and you don't have to agree with everything we do. I guess we put quality over quantity.
> > An unexperienced maintainer also creates more problems than adding support for now and dropping it later.
> 
> I understand that any project is subject to the developer/maintainers' opinions.
> 
> And don't get me wrong, I have the utmost respect for this project and the people involved, I am just trying my best to get a clear understanding of the process here, so please bear with me.
> 
> If a device has all that is needed for PE on their LOS port, and I use the sources from LOS and make none of my own changes to the sources (simply because none are needed), how could an applicant prove that they are indeed capable of maintaining?

As a person who also started with Lineage trees for Xiaomi 845 devices and gradually worked my way towards PE, I can assure you that not a single device tree on earth is perfect. You will start fixing bugs and making improvements that are not present in Lineage's code, and your trees will gradually diverge from Lineage. You will also learn a lot more along the way. Things like this in your tree will show your experience.
