### ISSUE TITLE
New maintainer for Razer Phone 2(aura)

### ISSUE THREAD

**Issue by Alcatraz323** [PixelExperience/official_devices#2463]
## Device you want to apply for

Razer Phone 2(aura)

## Device tree sources

https://github.com/Alcatraz323/android_device_razer_aura
https://github.com/Alcatraz323/android_kernel_razer_sdm845
https://github.com/Alcatraz323/vendor_razer_aura

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

Alcatraz323

### GitHub username

Alcatraz323

**Comment by Alcatraz323** [comment]
Anyone？

**Comment by jjpprrrr** [comment]
Overall, the tree looks fine to me. Please be more careful with keeping authorship and using proper git workflows (like cherry-pick or am) in the future, as some commits are clearly taken from other people, with the same wording of commit title or commit messages.

**Comment by Alcatraz323** [comment]
> Overall, the tree looks fine to me. Please be more careful with keeping authorship and using proper git workflows (like cherry-pick or am) in the future, as some commits are clearly taken from other people, with the same wording of commit title or commit messages.

👌

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying however I must point out the fact that some of the commits in your device tree and kernel have ripped out authorship, as of example the sdFAT driver import which is originally authored by bgcngm.

We'd like to request you to fix both device tree and kernel with proper authorships as per our Code of Conduct, kanging is extremely prohibited, as this has caused enough drama in the past around

**Comment by Alcatraz323** [comment]
> Hello. Thanks for applying however I must point out the fact that some of the commits in your device tree and kernel have ripped out authorship, as of example the sdFAT driver import which is originally authored by bgcngm.
> 
> We'd like to request you to fix both device tree and kernel with proper authorships as per our Code of Conduct, kanging is extremely prohibited, as this has caused enough drama in the past around

Hi. it is done now

**Comment by jjpprrrr** [comment]
Some issues regarding this commit:

https://github.com/Alcatraz323/android_kernel_razer_sdm845/commit/ae48da9797ffb4cfff7d3a9f87375455ceda9104

- I am the author of the [commit](https://github.com/PixelExperience-Devices/kernel_xiaomi_polaris/commit/62a72cdb6f5f88de3c815c8a3786d27aa223acdd). I don't know where you picked it from, but that person clearly stripped off the authorship as well. He even copied my commit message word-by-word.
- This commit is only needed during the initial android 12 bring-up, when the cgroup and task_profile of RT scheduling was not fixed. If your device was launched before pie (like aura with O MR1), you need this [commit](https://github.com/PixelExperience-Devices/device_xiaomi_polaris/commit/089d3ba6fdefc4386c17e87d6720331444cfe113) to properly set up cgroup for things like schedtune and RT. After that, bluetooth should work just fine without disabled RT group sched in kernel.

**Comment by Alcatraz323** [comment]
> Some issues regarding this commit:
> 
> [Alcatraz323/android_kernel_razer_sdm845@ae48da9](https://github.com/Alcatraz323/android_kernel_razer_sdm845/commit/ae48da9797ffb4cfff7d3a9f87375455ceda9104)
> 
> * I am the author of the [commit](https://github.com/PixelExperience-Devices/kernel_xiaomi_polaris/commit/62a72cdb6f5f88de3c815c8a3786d27aa223acdd). I don't know where you picked it from, but that person clearly stripped off the authorship as well. He even copied my commit message word-by-word.
> * This commit is only needed during the initial android 12 bring-up, when the cgroup and task_profile of RT scheduling was not fixed. If your device was launched before pie (like aura with O MR1), you need this [commit](https://github.com/PixelExperience-Devices/device_xiaomi_polaris/commit/089d3ba6fdefc4386c17e87d6720331444cfe113) to properly set up cgroup for things like schedtune and RT. After that, bluetooth should work just fine without disabled RT group sched in kernel.

Thanks for pointing it out, it's done now.

**Comment by jhenrique09** [comment]
@Alcatraz323 please make a PR for both official_devices and wiki repos

**Comment by Alcatraz323** [comment]
> @Alcatraz323 please make a PR for both official_devices and wiki repos

done
