### ISSUE TITLE
New maintainer for Xiaomi Redmi 8A Dual 

### ISSUE THREAD

**Issue by shield44** [PixelExperience/official_devices#2469]
## Device you want to apply for

Xiaomi Redmi 8A Dual 

## Device tree sources

https://github.com/shield44-project/device_xiaomi_olivewood
https://github.com/shield44-project/kernel_xiaomi_olivewood
https://gitlab.com/shield44/vendor_xiaomi_olivewood

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

shield44

### GitHub username

shield44

**Comment by jjpprrrr** [comment]
As per PE's CoC, any form of overclocking is not allowed.

Some examples:

https://github.com/shield44-project/kernel_xiaomi_olivewood/commit/7eb4d76b7cf2855ad31f5b008e2604d51e6edfb6

https://github.com/shield44-project/kernel_xiaomi_olivewood/commit/57f54e2fadb8e2202f071b0de53bf77657a2c3ad

**Comment by shield44** [comment]
> As per PE's CoC, any form of overclocking is not allowed.
> 
> Some examples:
> 
> [shield44-project/kernel_xiaomi_olivewood@7eb4d76](https://github.com/shield44-project/kernel_xiaomi_olivewood/commit/7eb4d76b7cf2855ad31f5b008e2604d51e6edfb6)
> 
> [shield44-project/kernel_xiaomi_olivewood@57f54e2](https://github.com/shield44-project/kernel_xiaomi_olivewood/commit/57f54e2fadb8e2202f071b0de53bf77657a2c3ad)

Kernel tree branch is a11/lineageos forgot to mention about that sorry! I will do that branch default

**Comment by shield44** [comment]
> As per PE's CoC, any form of overclocking is not allowed.
> 
> Some examples:
> 
> [shield44-project/kernel_xiaomi_olivewood@7eb4d76](https://github.com/shield44-project/kernel_xiaomi_olivewood/commit/7eb4d76b7cf2855ad31f5b008e2604d51e6edfb6)
> 
> [shield44-project/kernel_xiaomi_olivewood@57f54e2](https://github.com/shield44-project/kernel_xiaomi_olivewood/commit/57f54e2fadb8e2202f071b0de53bf77657a2c3ad)

Everything is fine in a11/lineageos branch

**Comment by Orel6505** [comment]
Redmi 8A Dual have 2gb version, which not passing PE device requirements.

https://github.com/PixelExperience/docs/blob/master/device_requirements.md

**Comment by shield44** [comment]
> Redmi 8A Dual have 2gb version, which not passing PE device requirements.
> 
> https://github.com/PixelExperience/docs/blob/master/device_requirements.md

No, Redmi 8A Dual has three variants (2gb,3gb and 4gb) and nearly very few peoples use 2gb(noone use it also this version is not available) variants almost many of them have 3gb and 4gb variants

**Comment by Hlcpereira** [comment]
We are still avaluating the application, as so far the only thing holding back the approval of olivewood is what @Orel6505 mentioned, as we are looking on a way to avoid the flashing of the build on 2 GB devices (whether blocking through releasetools on the device side or do something about on the ROM side as a general block without the maintainers having to care about it). Once the decision was made it's going to be communicated in here ASAP.

**Comment by Orel6505** [comment]
> > Redmi 8A Dual have 2gb version, which not passing PE device requirements.
> > 
> > https://github.com/PixelExperience/docs/blob/master/device_requirements.md
> 
> No, Redmi 8A Dual has three variants (2gb,3gb and 4gb) and nearly very few peoples use 2gb(noone use it also this version is not available) variants almost many of them have 3gb and 4gb variants 

Redmi 8A Dual doesn't have 4gb variant.
As you can see here:
https://m.gsmarena.com/xiaomi_redmi_8a_dual-ampp-10078.php

**Comment by jrizz0li** [comment]
> > > Redmi 8A Dual have 2gb version, which not passing PE device requirements.
> > > https://github.com/PixelExperience/docs/blob/master/device_requirements.md
> > 
> > 
> > No, Redmi 8A Dual has three variants (2gb,3gb and 4gb) and nearly very few peoples use 2gb(noone use it also this version is not available) variants almost many of them have 3gb and 4gb variants
> 
> Redmi 8A Dual doesn't have 4gb variant. As you can see here: https://m.gsmarena.com/xiaomi_redmi_8a_dual-ampp-10078.php

Even 3gb variant is enough to pass pe's device requirements and 2gb variants will be blocked

**Comment by shield44** [comment]
> We are still avaluating the application, as so far the only thing holding back the approval of olivewood is what @Orel6505 mentioned, as we are looking on a way to avoid the flashing of the build on 2 GB devices (whether blocking through releasetools on the device side or do something about on the ROM side as a general block without the maintainers having to care about it). Once the decision was made it's going to be communicated in here ASAP.

Ok

**Comment by shield44** [comment]
@Hlcpereira shall I block 2gb ram devices from releasetools ?

**Comment by Hlcpereira** [comment]
For the sake of getting this one a final word about, yes, let's go this way considering that if something changes down the line it can be undone.

Please open a PR on both official_devices and wiki repositories.

**Comment by shield44** [comment]
> For the sake of getting this one a final word about, yes, let's go this way considering that if something changes down the line it can be undone.
> 
> Please open a PR on both official_devices and wiki repositories.

Done ,PR's submitted

**Comment by Orel6505** [comment]
> > For the sake of getting this one a final word about, yes, let's go this way considering that if something changes down the line it can be undone.
> > 
> > Please open a PR on both official_devices and wiki repositories.
> 
> Done ,PR's submitted

Congratulations @shield44! 🎉

**Comment by shield44** [comment]
> > > For the sake of getting this one a final word about, yes, let's go this way considering that if something changes down the line it can be undone.
> > > Please open a PR on both official_devices and wiki repositories.
> > 
> > 
> > Done ,PR's submitted
> 
> Congratulations @shield44! 🎉

Thanks 👍
