### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Krxyzn** [PixelExperience/official_devices#2475]
## Device you want to apply for

Redmi 4X Santoni

## Device tree sources

https://github.com/JktFdrxProjektz/android_device_xiaomi_santoni
https://github.com/JktFdrxProjektz/L_check_msm
https://github.com/JktFdrxProjektz/android_vendor_xiaomi_santoni

## Number of ROM's you maintain officially

5

## Any Exceptions/special concern?

No

### Telegram username

@Krxyzn

### GitHub username

@Krxyzn

**Comment by Orel6505** [comment]
Your device tree are private...

**Comment by ZIDAN44** [comment]
> ## Device you want to apply for
> Redmi 4X Santoni
> 
> ## Device tree sources
> https://github.com/JktFdrxProjektz/android_device_xiaomi_santoni https://github.com/JktFdrxProjektz/L_check_msm https://github.com/JktFdrxProjektz/android_vendor_xiaomi_santoni
> 
> ## Number of ROM's you maintain officially
> 5
> 
> ## Any Exceptions/special concern?
> No
> 
> ## Contact
> ### Telegram username
> @Krxyzn
> 
> ### GitHub username
> @Krxyzn

which branch ?

**Comment by Orel6505** [comment]
![Screenshot_20211228-092834_GitHub.png](https://user-images.githubusercontent.com/85583144/147540169-23941933-ea81-409b-b6c5-e16d0b36e640.png)

**Comment by ZIDAN44** [comment]
You dont match with our CoC requarments. Go check them out from here https://github.com/PixelExperience/docs/blob/master/maintainers_requirements.md
