### ISSUE TITLE
New maintainer for lavender

### ISSUE THREAD

**Issue by D3nesyan** [PixelExperience/official_devices#2477]
## Device you want to apply for

Redmi Note 7 (lavender)

## Device tree sources

https://github.com/Ratoriku/android_device_xiaomi_lavender
https://github.com/Ratoriku/android_vendor_xiaomi_lavender
https://github.com/Ratoriku/android_kernel_xiaomi_lavender-1

## Number of ROM's you maintain officially

1, ArrowOS

## Any Exceptions/special concern?

No

### Telegram username

@Ratoriku

### GitHub username

@Ratoriku

**Comment by protonmailtp** [comment]
Yaaasssssssssss, can't wait to see official.

**Comment by protonmailtp** [comment]
Sorry for spam but i am so happy today, thanks @Ratoriku . Hope that other buidlbot don't get official.

**Comment by Jorg3Lucas** [comment]
the device is already being developed by another dev
