### ISSUE TITLE
New maintainer for Redmi Note 7 ( lavender )

### ISSUE THREAD

**Issue by ticklemykettle** [PixelExperience/official_devices#2479]
## Device you want to apply for

Redmi Note 7 (lavender)

## Device tree sources

https://github.com/ticklemykettle/device_xiaomi_lavender
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/tree/oldcam-eas
https://github.com/ticklemykettle/vendor_xiaomi_lavender

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

@ticklemykettle

### GitHub username

@ticklemykettle

**Comment by Jorg3Lucas** [comment]
@ticklemykettle make a pr
