### ISSUE TITLE
New maintainer for Redmi Note 9

### ISSUE THREAD

**Issue by surblazer** [PixelExperience/official_devices#2483]
## Device you want to apply for

merlinx

## Device tree sources

https://github.com/Redmi-MT6768/android_device_xiaomi_merlinx/tree/twelve
https://github.com/Redmi-MT6768/android_device_xiaomi_mt6768-common/tree/twelve
https://github.com/Redmi-MT6768/android_kernel_xiaomi_mt6768
https://github.com/Redmi-MT6768/android_vendor_xiaomi_mt6768-ims
https://github.com/Redmi-MT6768/android_vendor_xiaomi_merlinx

## Number of ROM's you maintain officially

1 (CrDroid)

## Any Exceptions/special concern?

Screen recording doesn't work with system app (as on begonia), some patches needed for IMS, rest is fine.

### Telegram username

surblazer

### GitHub username

surblazer

**Comment by ZIDAN44** [comment]
Overall, the tree looks fine to me. Show me the patches you need for ims.

**Comment by lazydev1852** [comment]
yallah pq disabled🏳‍⚧🙏💪

bismillah gaming rom

**Comment by surblazer** [comment]
> Overall, the tree looks fine to me. Show me the patches you need for ims.

https://gerrit.pixelexperience.org/q/topic:%22mediatek-ims%22+(status:open%20OR%20status:merged)

**Comment by Hlcpereira** [comment]
@surblazer please make a PR for both official_devices and wiki repos adding merlinx in them.

**Comment by surblazer** [comment]
> @surblazer please make a PR for both official_devices and wiki repos adding merlinx in them.

Done
