### ISSUE TITLE
New maintainer Redmi 9 Prime/Poco M2

### ISSUE THREAD

**Issue by SakthivelNadar** [PixelExperience/official_devices#2484]
## Device you want to apply for

lava

## Device tree sources

https://github.com/Redmi-MT6768/android_device_xiaomi_lava/tree/twelve
https://github.com/PixelExperience-Devices/device_xiaomi_mt6768-common
https://github.com/PixelExperience-Devices/kernel_xiaomi_mt6768
https://github.com/Redmi-MT6768/android_vendor_mediatek-ims
https://github.com/Redmi-MT6768/android_vendor_xiaomi_lava

## Number of ROM's you maintain officially

None

## Any Exceptions/special concern?

Screen recording doesn't work with system app (as on begonia), some patches needed for IMS, rest is fine.

### Telegram username

SakthivelNadar

### GitHub username

SparXFusion

**Comment by veshrao** [comment]
pero

**Comment by ZIDAN44** [comment]
Hello!

As per our CoC requirements we dont accept trees with Sepolicy NEVERALLOWS enabled. Pls check our CoC requirements. 
https://github.com/PixelExperience/docs/blob/master/maintainers_code_of_conduct.md#:~:text=Ignore%20Sepolicy%20Neverallows.

**Comment by SakthivelNadar** [comment]
> Hello!
> 
> As per our CoC requirements we dont accept trees with Sepolicy NEVERALLOWS enabled. Pls check our CoC requirements. https://github.com/PixelExperience/docs/blob/master/maintainers_code_of_conduct.md#:~:text=Ignore%20Sepolicy%20Neverallows.

did it now

**Comment by NeonzGamingYT** [comment]
pru sar

**Comment by ZIDAN44** [comment]
Remove lineage related overlays https://github.com/Redmi-MT6768/android_device_xiaomi_lava/tree/twelve/overlay-lineage

**Comment by SakthivelNadar** [comment]
> Remove lineage related overlays https://github.com/Redmi-MT6768/android_device_xiaomi_lava/tree/twelve/overlay-lineage

done

**Comment by ZIDAN44** [comment]
@SparXFusion please make a PR for both official_devices and wiki repos adding lava in them
