### ISSUE TITLE
Davinci co-maintainer

### ISSUE THREAD

**Issue by trpsl** [PixelExperience/official_devices#2499]
## Device you want to apply for

davinci

## Device tree sources

https://github.com/trpsl/device_xiaomi_davinci
https://github.com/trpsl/davinci-kernel
https://gitlab.com/trpsl/vendor_xiaomi_davinci

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

trpsl

### GitHub username

trpsl

**Comment by baalajimaestro** [comment]
Due to an internal discussion, it has come to a conclusion that, neither of us will be joining for PE12.

Thanks a good luck!
