### ISSUE TITLE
New maintainer for Z01R (Asus Zenfone 5z)

### ISSUE THREAD

**Issue by yograjfire18** [PixelExperience/official_devices#2503]
## Device you want to apply for

Z01R [Asus Zenfone 5z]

## Device tree sources

https://github.com/yograjsingh-cmd/android_device_asus_Z01R/tree/PE-12
https://github.com/yograjsingh-cmd/kernel_z01r/tree/twelve
https://github.com/yograjsingh-cmd/vendor_asus/tree/12

## Number of ROM's you maintain officially

None as of Now

## Any Exceptions/special concern?

No

### Telegram username

yograjfire18

### GitHub username

yograjsingh-cmd

**Comment by Hasaber8** [comment]
You need to have enforcing in order to ship official builds.

**Comment by yograjfire18** [comment]
enforcing needed
sad here
have been trying but device goes in bootloop
and usb connection isn't available in bootloop but available in fastboot
also no pstore file is found and couldn't fix...
will try more and then apply back..
Thnx
