### ISSUE TITLE
New maintainer for Nokia 8

### ISSUE THREAD

**Issue by raphaelthegreat** [PixelExperience/official_devices#2532]
## Device you want to apply for

NB1

## Device tree sources

https://github.com/GPUCode/device_nokia_NB1
https://github.com/GPUCode/android_kernel_nokia_msm8998
https://github.com/GPUCode/vendor_nokia_NB1

## Number of ROM's you maintain officially

Currently none, but I maintained crDroid unofficially for a year

## Any Exceptions/special concern?

Our device requires a special patch in bootable/recovery to make the AOSP recovery work properly.
In addition due to the blobs used we need updated display/media HALs (LA.UM.9.2.r1-03500-SDMxx0.0 specifically)

### Telegram username

@emufan4568

### GitHub username

@GPUCode

**Comment by raphaelthegreat** [comment]
Bump

**Comment by ghost** [comment]
Bump

**Comment by jjpprrrr** [comment]
Looks good to me.

Reviewed-by: Chenyang Zhong <zhongcy95@gmail.com>

**Comment by Hasaber8** [comment]
@GPUCode welcome to the team.
 Please put up a PR on wiki and official devices.

**Comment by raphaelthegreat** [comment]
> @GPUCode welcome to the team. Please put up a PR on wiki and official devices.

Thanks! Could you point me on what to do next? What kind of PR should I do? I've never maintained a ROM officially so this is a bit new for me.
