### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by vytska69** [PixelExperience/official_devices#2537]
## Device you want to apply for

Your device name
redmi 7a

## Device tree sources

https://github.com/vytska69/android_device_xiaomi_pine
https://github.com/mi-sdm439/android_kernel_xiaomi_sdm439
https://github.com/hsx02/vendor_xiaomi_pine
https://github.com/hsx02/device_xiaomi_sdm439-common
https://github.com/hsx02/vendor_xiaomi_sdm439-common

## Number of ROM's you maintain officially

3

## Any Exceptions/special concern?

this device has 3 GB RAM/32 GB internal storage model and most of people uses my builds on this model

### Telegram username

randomas_3000

### GitHub username

vytska69

**Comment by ZIDAN44** [comment]
Hey there..!

Pls read our CoC requirements & as per our CoC requirements 3GB ram devices are not allowed.

**Comment by Demigod4255** [comment]
Any news?

**Comment by Orel6505** [comment]
LOL

**Comment by Hlcpereira** [comment]
Hey there. Thanks for applying and sorry for the long wait for the final answer.

Unfortunately I'm sorry to say that your application was rejected.

"Why?"
While we were checking your repos we couldn't see much of what we would consider a reasonable git experience/knowledge.

That doesn't mean that you are rejected forever. Feel free to apply in the near future again whenever you've gathered more experience.

Best regards.
