### ISSUE TITLE
New maintainer for Instantnoodlep

### ISSUE THREAD

**Issue by jef00** [PixelExperience/official_devices#2539]
## Device you want to apply for

instantnoodlep

## Device tree sources

https://github.com/jef00/device_oneplus_instantnoodlep
https://github.com/PixelExperience-Devices/kernel_oneplus_sm8250/tree/twelve-wip
https://github.com/jef00/vendor_oneplus_instantnoodlep
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_oneplus_sm8250-common
https://github.com/PixelExperience-Devices/device_oneplus_sm8250-common

## Number of ROM's you maintain officially

0 Iam new to this all

## Any Exceptions/special concern?

No a lot of experience 

### Telegram username

@Jef009

### GitHub username

jef00

**Comment by Hlcpereira** [comment]
Hey there.

Thanks for applying and I'd like to tell you that your application was approved.

Please open a PR to the official_devices and wiki repos to properly add OnePlus 8 Pro back in the roaster.

Once those are done, a core member will contact you to take care of the next steps

**Comment by jef00** [comment]
Hey Hlcpereira,

Thank you so much! I will do that!
