### ISSUE TITLE
New maintainer for lavender

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#2545]
## Device you want to apply for

Xiaomi Redmi Note 7 / 7S

## Device tree sources

https://github.com/inferno964/device_xiaomi_lavender
https://github.com/inferno964/android_kernel_xiaomi_sdm660
https://github.com/inferno964/vendor_xiaomi_lavender

## Number of ROM's you maintain officially

1 ( And That's My Own ROM Project )

## Any Exceptions/special concern?

None as of yet. I've tested the common trees from source. Furthermore if there's any problem then I'll switch with the standalone (decommonized) trees.

### Telegram username

@inferno964

### GitHub username

@inferno964

**Comment by SlogKr** [comment]
Pro Is Arriving 🙃

**Comment by Quarkin** [comment]
well what we need is a responsible dev.

**Comment by Quarkin** [comment]
and as a matter of fact he is and not toxic as the other one's.

**Comment by imSu-r-aj** [comment]
Yes, You Are Right Brother @Quarkin

**Comment by 7celestial** [comment]
What we need is you tape your mouth shut.. what if you tryna build one and let's see until where your sass will get you.. find someone else to apply the  instead running your mouth

**Comment by GamanBadra** [comment]
Inferno is a very good dev.he has lots of knowledge of custom roms building.in a very short time he developed his own rom and that's a very big thing.pixel experience is a big and well known rom,it will be great if inferno maintain PE for lavender.good luck inferno 🙂🙂🙂

**Comment by ghost** [comment]
@ZIDAN44 @Hasaber8 Are there any kind of issues or concerns with the trees ?

**Comment by ghost** [comment]
I'm closing my maintainership application.
"lavender is having a lot of background issues" is a statement made by the PE team member itself. I don't see me getting approved anyway. I'm stepping back from it. Maintaining PE has always been like a dream for me.I would love to see this opportunity again whereby I can get approved.
@Hlcpereira @jhenrique09

**Comment by jjpprrrr** [comment]
As per PE's CoC, any form of frequency or voltage modification is not allowed.

Some examples:
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/2802e454fc52ef9143adc4970b3e36027820ae8e
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/2b8299e95754084aac9aeccd7ebabeff8deac355
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/f03656c808367672ef96c3e49321b9ce591effb5

**Comment by ghost** [comment]
> As per PE's CoC, any form of frequency or voltage modification is not allowed.
> 
> Some examples: [stormbreaker-project/kernel_xiaomi_lavender@2802e45](https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/2802e454fc52ef9143adc4970b3e36027820ae8e) [stormbreaker-project/kernel_xiaomi_lavender@2b8299e](https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/2b8299e95754084aac9aeccd7ebabeff8deac355) [stormbreaker-project/kernel_xiaomi_lavender@f03656c](https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/f03656c808367672ef96c3e49321b9ce591effb5)

The commits have been reverted , please check the new link https://github.com/inferno964/kernel_xiaomi_sdm660

**Comment by jjpprrrr** [comment]
Boeffla wakelock blocker is also not allowed, according to CoC. 

https://github.com/inferno964/kernel_xiaomi_sdm660/commit/b1628c3fbdf3bfaacbbece74e813439be64ec4d0

I suggest that you go through the whole CoC and fix any potential violations in your tree. This is the last time I point out  obvious things for you.

**Comment by ghost** [comment]
> Boeffla wakelock blocker is also not allowed, according to CoC. 
> 
> https://github.com/inferno964/kernel_xiaomi_sdm660/commit/b1628c3fbdf3bfaacbbece74e813439be64ec4d0
> 
> I suggest that you go through the whole CoC and fix any potential violations in your tree. This is the last time I point out  obvious things for you.

https://github.com/inferno964/android_kernel_xiaomi_sdm660 

This meets up all the requirements.

**Comment by ghost** [comment]
The kernel earlier was having issues with the CoC , but the thing I figured out was that it existed even on the Previous offical maintainer's kernel too.
Here are the proofs & it's in your own device org.

https://github.com/PixelExperience-Devices/kernel_xiaomi_lavender/blob/twelve/drivers/base/power/boeffla_wl_blocker.c

https://github.com/PixelExperience-Devices/kernel_xiaomi_lavender/commit/2802e454fc52ef9143adc4970b3e36027820ae8e

https://github.com/PixelExperience-Devices/kernel_xiaomi_lavender/commit/f03656c808367672ef96c3e49321b9ce591effb5

https://github.com/PixelExperience-Devices/kernel_xiaomi_lavender/commit/2b8299e95754084aac9aeccd7ebabeff8deac355

So I got confused but now I've posted the new kernel link which meets up CoC requirements.

**Comment by jjpprrrr** [comment]
That was indeed an oversight on us. Thanks for updating your kernel.

**Comment by KUIpru** [comment]
@jjpprrrr any progress on this issue sir ?

**Comment by Hlcpereira** [comment]
Sorry for long wait on the final position of this application.

Unfortunately, I must tell you that you application was not accepted.

"Why?"

We don't feel a general safety regarding a healthy development on the device side and the impacts of those in the project as a whole, even more considering that we are talking about the lavender community. 

That doesn't mean that the doors are closed forever. Feel free to reapply in a near future when you gather more experience.

Best regards.

**Comment by KUIpru** [comment]
HLcpereira u are talking non sense 😆 , @Hlcpereira what do u actually mean by healthy development , he maintained aex , raven too and u are saying that it will not healthy development so ig u need more experience than him .
Don't be a puppet

**Comment by ZIDAN44** [comment]
> HLcpereira u are talking non sense 😆 , @Hlcpereira what do u actually mean by healthy development , he maintained aex , raven too and u are saying that it will not healthy development so ig u need more experience than him . Don't be a puppet And now u will remove this comment too , ik 😁

Useless poor online people.. thanks

**Comment by KUIxd** [comment]
> > HLcpereira u are talking non sense 😆 , @Hlcpereira what do u actually mean by healthy development , he maintained aex , raven too and u are saying that it will not healthy development so ig u need more experience than him . Don't be a puppet And now u will remove this comment too , ik 😁
> 
> Useless poor online people.. thanks

Ok and ?

**Comment by GamanBadra** [comment]
> > > HLcpereira u are talking non sense 😆 , @Hlcpereira what do u actually mean by healthy development , he maintained aex , raven too and u are saying that it will not healthy development so ig u need more experience than him . Don't be a puppet And now u will remove this comment too , ik 😁
> > 
> > 
> > Useless poor online people.. thanks
> 
> Ok and ?

Accha kui
