### ISSUE TITLE
New maintainer for RMX2170

### ISSUE THREAD

**Issue by mithuprince** [PixelExperience/official_devices#2548]
## Device you want to apply for

Realme 7 Pro

## Device tree sources

https://github.com/sm7125/android_device_realme_RMX2170.git
https://github.com/sm7125/android_device_realme_sm7125-common.git
https://github.com/sm7125/android_kernel_realme_sm7125.git
https://github.com/sm7125/proprietary_vendor_realme.git (vendor is private else everything is public)

## Number of ROM's you maintain officially

1 bcz didnt applied for more

## Any Exceptions/special concern?

aaah yes as mainting 2 devices 1st device is my sakura(redmi 6 pro) now realme 7 pro is my primary device for seeking to be offlicial...and mainting 3 mnths unofficial PE for this device

### Telegram username

@mxpr

### GitHub username

mithuprince

**Comment by ZIDAN44** [comment]
Hello there

Where did you adapted your device tree for PE ?

Also private repos are not allowed. Read all rules first !!

**Comment by Hasaber8** [comment]
Can't gauge if the maintainer can fix stuff on his own + devices trees aren't adapted to PE neither is the vendor public.
