### ISSUE TITLE
New maintainer for lemonadep

### ISSUE THREAD

**Issue by YouLop-09** [PixelExperience/official_devices#2551]
## Device you want to apply for

OnePlus 9 Pro (lemonadep)

## Device tree sources

https://github.com/PixelExperience-Lemonadep/device_oneplus_lemonadep
https://github.com/PixelExperience-Lemonadep/device_oneplus_sm8350-common
https://github.com/PixelExperience-Lemonadep/kernel_oneplus_sm8350
https://github.com/PixelExperience-Lemonadep/vendor_oneplus_lemonadep
https://github.com/PixelExperience-Lemonadep/vendor_oneplus_sm8350-common

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

@youlop09

### GitHub username

YouLop-09

**Comment by Hasaber8** [comment]
https://github.com/PixelExperience-Lemonadep/device_oneplus_sm8350-common/commit/c7e8353b8328f2806982c16fa0b933b8254c1dd1
According to PE - CoC device settings aren't allowed, especially the stuff that isn't even on stock.
+ Seems like you are running a permissive build.

**Comment by YouLop-09** [comment]
> [PixelExperience-Lemonadep/device_oneplus_sm8350-common@c7e8353](https://github.com/PixelExperience-Lemonadep/device_oneplus_sm8350-common/commit/c7e8353b8328f2806982c16fa0b933b8254c1dd1) According to PE - CoC device settings aren't allowed, especially the stuff that isn't even on stock.
> 
> * Seems like you are running a permissive build.

hi, thanks for answering the current build is enforcing:
https://github.com/PixelExperience-Lemonadep/device_oneplus_sm8350-common/blob/twelve-wip/BoardConfigCommon.mk

about the additional features that are included with the OnePlus Settings this does not modify the system and provides functionalities that we have in the stock system.
