### ISSUE TITLE
New maintainer for hotdogb, hotdog, guacamole

### ISSUE THREAD

**Issue by classified** [PixelExperience/official_devices#2555]
## Device you want to apply for

OnePlus 7T
OnePlus 7 Pro
OnePlus 7T Pro

## Device tree sources

https://github.com/classified/android_device_oneplus_hotdogb
https://github.com/classified/device_oneplus_guacamole
https://github.com/classified/device_oneplus_hotdog
https://github.com/classified/android_device_oneplus_sm8150-common
https://github.com/classified/vendor_oneplus_sm8150-common
https://github.com/classified/vendor_oneplus_hotdogb
https://github.com/classified/vendor_oneplus_guacamole
https://github.com/classified/vendor_oneplus_hotdog
https://github.com/classified/hardware_oneplus
https://github.com/classified/android_kernel_oneplus_sm8150

## Number of ROM's you maintain officially

1 ( 2011 - 2012) Motorola defy 

## Any Exceptions/special concern?

No

### Telegram username

@classified7667

### GitHub username

@classified

**Comment by jjpprrrr** [comment]
According to PE's CoC, write access to generic sysfs file type is not allowed. It is generally a bad practice to give such a broad write access, and this kind of sepolicy defeats the purpose of SELinux itself.

https://github.com/classified/android_device_oneplus_sm8150-common/blob/twelve/sepolicy/vendor/vendor_qti_init_shell.te#L14

**Comment by jjpprrrr** [comment]
In addition to that, I was wondering if you used some sort of automatic script to fix denials. I don't think everything in the following commits is necessary:

https://github.com/classified/android_device_oneplus_sm8150-common/commit/0c7e88338c5e908d7935a519b5e2ff94ecbbdc76
https://github.com/classified/android_device_oneplus_sm8150-common/commit/84dfc1c5f7900f5ef49efd8ab93a575959655e12

**Comment by classified** [comment]
> According to PE's CoC, write access to generic sysfs file type is not allowed. It is generally a bad practice to give such a broad write access, and this kind of sepolicy defeats the purpose of SELinux itself.
> 
> https://github.com/classified/android_device_oneplus_sm8150-common/blob/twelve/sepolicy/vendor/vendor_qti_init_shell.te#L14

Hey @jjpprrrr 

Thanks for the review, I have fixed that and updated branch

https://github.com/classified/android_device_oneplus_sm8150-common/commits/twelve

**Comment by classified** [comment]
> In addition to that, I was wondering if you used some sort of automatic script to fix denials. I don't think everything in the following commits is necessary:
> 
> [classified/android_device_oneplus_sm8150-common@0c7e883](https://github.com/classified/android_device_oneplus_sm8150-common/commit/0c7e88338c5e908d7935a519b5e2ff94ecbbdc76) [classified/android_device_oneplus_sm8150-common@84dfc1c](https://github.com/classified/android_device_oneplus_sm8150-common/commit/84dfc1c5f7900f5ef49efd8ab93a575959655e12)

Hey @jjpprrrr ,

Thanks for notifying me about this, as i was maintaining unofficial build from December, around sometime back i was trying to resolve all the denials which i could see in the logs (don't know why :dagger: ). this should not have made it to main branch when i posted for the review. my apologies for that

**Comment by jjpprrrr** [comment]
Alright the rest looks good to me. Welcome aboard! Feel free to submit PRs to official_devices and wiki. I'm closing this issue.
