### ISSUE TITLE
New maintainer for lavender

### ISSUE THREAD

**Issue by AbrarNoob** [PixelExperience/official_devices#2557]
## Device you want to apply for

Redmi Note 7 

## Device tree sources

https://github.com/AbrarNoob/device_xiaomi_lavender-S/tree/pe
https://github.com/AbrarNoob/kernel_xiaomi_lavender/tree/qti-oldcam-eas
https://github.com/AbrarNoob/android_vendor_xiaomi_lavender-S

## Number of ROM's you maintain officially

2 ( AncientOS, OctaviOS)

## Any Exceptions/special concern?

No

### Telegram username

@AbrarNoob

### GitHub username

@AbrarNoob

**Comment by jjpprrrr** [comment]
As per PE's CoC, any form of frequency or voltage modification is not allowed.

Some examples:
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/2802e454fc52ef9143adc4970b3e36027820ae8e
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/2b8299e95754084aac9aeccd7ebabeff8deac355
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/commit/f03656c808367672ef96c3e49321b9ce591effb5

**Comment by jjpprrrr** [comment]
As per PE's CoC, any form of frequency or voltage modification is not allowed.

Some examples:
https://github.com/AbrarNoob/kernel_xiaomi_lavender/commit/2802e454fc52ef9143adc4970b3e36027820ae8e
https://github.com/AbrarNoob/kernel_xiaomi_lavender/commit/2b8299e95754084aac9aeccd7ebabeff8deac355
https://github.com/AbrarNoob/kernel_xiaomi_lavender/commit/f03656c808367672ef96c3e49321b9ce591effb5

**Comment by Hlcpereira** [comment]
As due to no replies for the points mentioned and general lack of experience as far as we could check, this application has been rejected. Feel free to reapply in a near future.
