### ISSUE TITLE
New maintainer for lemonadep

### ISSUE THREAD

**Issue by YouLop-09** [PixelExperience/official_devices#2558]
## Device you want to apply for

OnePlus 9 Pro lemonadep

## Device tree sources

https://github.com/PixelExperience-Lemonadep/device_oneplus_lemonadep
https://github.com/PixelExperience-Lemonadep/device_oneplus_sm8350-common
https://github.com/PixelExperience-Lemonadep/kernel_oneplus_sm8350
https://github.com/PixelExperience-Lemonadep/vendor_oneplus_lemonadep
https://github.com/PixelExperience-Lemonadep/vendor_oneplus_sm8350-common
https://github.com/PixelExperience-Lemonadep/vendor_oneplus_extras

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No, this is just an update with the updated trees without the special device settings that are not in the stock rom and the kernel in enforcing.

### Telegram username

@youlop09

### GitHub username

YouLop-09

**Comment by Jorg3Lucas** [comment]
Helloo @YouLop-09, I hope you are well!

I apologize for the delay in responding to your application;
Are you still interested in joining our team?

**Comment by YouLop-09** [comment]
> Helloo @YouLop-09, I hope you are well!
> 
> I apologize for the delay in responding to your application; Are you still interested in joining our team?

hello thank you  for considering me for now I had a problem with my device so I can't take care of the ROM now.
