### ISSUE TITLE
New maintainer for zippo

### ISSUE THREAD

**Issue by Lucchetto** [PixelExperience/official_devices#2570]
## Device you want to apply for

Lenovo Z6 Pro

## Device tree sources

https://github.com/lenovo-sm8150/android_device_lenovo_zippo
https://github.com/lenovo-sm8150/android_device_lenovo_sm8150-common
https://github.com/lenovo-sm8150/android_kernel_lenovo_sm8150
https://github.com/lenovo-sm8150/proprietary_vendor_lenovo

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

pasta_con_tonno

### GitHub username

@Lucchetto

**Comment by jjpprrrr** [comment]
Hi Lucchetto. Thanks for the application and sorry for the delay in response. The trees look good to me. Are you still interested in maintaining zippo officially for PE?

**Comment by Lucchetto** [comment]
Yes

**Comment by jjpprrrr** [comment]
Great. Closing this issue.
