### ISSUE TITLE
New maintainer for vince.

### ISSUE THREAD

**Issue by rk134** [PixelExperience/official_devices#2571]
## Device you want to apply for

Redmi 5 Plus/Redmi Note 5 | vince

## Device tree sources

https://github.com/rk134/device_xiaomi_vince/tree/pixelexperience-user
https://github.com/rk134/kernel_xiaomi_vince
https://github.com/rk134/vendor_xiaomi_vince

## Number of ROM's you maintain officially

2 (crDroid & KomodoOS)

## Any Exceptions/special concern?

Yes, encryption.
Encryption on vince has been a little bit difficult since A10, as when forcing fde/fbe, the device gets stuck on splash, with no logs/pstore/last_kmsg. Currently on FDE, not forced.

### Telegram username

https://t.me/rk_134

### GitHub username

rk134

**Comment by veshrao** [comment]
pro

**Comment by jjpprrrr** [comment]
Hi. Thanks for the application. According to PE's CoC, Boeffla wakelock blocker is not allowed.

https://github.com/rk134/kernel_xiaomi_vince/blob/coastline/arch/arm64/configs/vince-perf_defconfig#L578

**Comment by jjpprrrr** [comment]
Change of PE's system default behaviors like this is not allowed.

https://github.com/rk134/device_xiaomi_vince/commit/93846e3b07f89651d66e06527737c2d48b20d047

Package removal method like this should generally be avoided. If your device has limited system partition space and there is no way around that, the list of packages to be removed needs direct approval from the core team.

https://github.com/rk134/device_xiaomi_vince/blob/pixelexperience-user/remove_packages/Android.mk#L7

**Comment by jjpprrrr** [comment]
Granting write access to generic sysfs nodes is not allowed, according to PE's CoC. If the init shell needs access to certain nodes, label those nodes as specific sysfs types and grant access to those types only.
https://github.com/rk134/device_xiaomi_vince/blob/pixelexperience-user/sepolicy/vendor/qti_init_shell.te#L19

**Comment by rk134** [comment]
> Hi. Thanks for the application. According to PE's CoC, Boeffla wakelock blocker is not allowed.
> 
> https://github.com/rk134/kernel_xiaomi_vince/blob/coastline/arch/arm64/configs/vince-perf_defconfig#L578

Hi, thank you so much for the replies! I will get working on them straightaway.

**Comment by rk134** [comment]
> Granting write access to generic sysfs nodes is not allowed, according to PE's CoC. If the init shell needs access to certain nodes, label those nodes as specific sysfs types and grant access to those types only. https://github.com/rk134/device_xiaomi_vince/blob/pixelexperience-user/sepolicy/vendor/qti_init_shell.te#L19

Hi, all changes have been done as requested.

Summary:
rk134/device_xiaomi_vince@3302f9a
rk134/kernel_xiaomi_vince@490769b

rk134.

**Comment by jjpprrrr** [comment]
You still have this commit left that changes the animation speed.

https://github.com/rk134/device_xiaomi_vince/commit/31e07df968b7091fd5127050e4e7bc3e417199d7

**Comment by rk134** [comment]
> You still have this commit left that changes the animation speed.
> 
> [rk134/device_xiaomi_vince@31e07df](https://github.com/rk134/device_xiaomi_vince/commit/31e07df968b7091fd5127050e4e7bc3e417199d7)

This has been fixed.

**Comment by jjpprrrr** [comment]
Alright the rest looks good to me. Welcome aboard! Feel free to submit PRs to official_devices and wiki. I'm closing this issue.
