### ISSUE TITLE
New maintainer for Mi 11X Pro/Redmi K40 Pro+/Mi 11i (haydn)

### ISSUE THREAD

**Issue by AdarshGrewal** [PixelExperience/official_devices#2577]
## Device you want to apply for

Mi 11X Pro/Redmi K40 Pro+/Mi 11i (haydn)

## Device tree sources

https://github.com/AdarshGrewal/android_device_xiaomi_haydn
https://github.com/AdarshGrewal/android_kernel_xiaomi_haydn
https://gitlab.com/AdarshGrewal/proprietary_vendor_xiaomi_haydn

## Number of ROM's you maintain officially

None

## Any Exceptions/special concern?

Change 16716 from Gerrit is needed otherwise enroll screen crashes due to blank animations for Sidefps

### Telegram username

@grewal

### GitHub username

@AdarshGrewal

**Comment by Hasaber8** [comment]
Everything seems fine to me, any comments @jjpprrrr ?

**Comment by jjpprrrr** [comment]
Granting write access to generic sysfs label is not allowed, according to PE's CoC. If mi_thermald needs write access to a specific sysfs node, label the node with a non-generic type and grant access for that type only.

https://github.com/AdarshGrewal/android_device_xiaomi_haydn/blob/pe-twelve/sepolicy/vendor/mi_thermald.te#L16

**Comment by AdarshGrewal** [comment]
> Granting write access to generic sysfs label is not allowed, according to PE's CoC. If mi_thermald needs write access to a specific sysfs node, label the node with a non-generic type and grant access for that type only.
> 
> https://github.com/AdarshGrewal/android_device_xiaomi_haydn/blob/pe-twelve/sepolicy/vendor/mi_thermald.te#L16

Thanks for notifying me about that. FIxed and Pushed

**Comment by jjpprrrr** [comment]
The rest looks good to me. Welcome aboard! Feel free to submit PRs to official_devices and wiki. I'm closing this issue.
