### ISSUE TITLE
New maintainer for Mi 10S (thyme)

### ISSUE THREAD

**Issue by KaguraRinko** [PixelExperience/official_devices#2581]
## Device you want to apply for
Mi 10S (thyme)

## Device tree sources

https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/twelve
https://github.com/Lynnrin-Studio/android_kernel_xiaomi_thyme (Only using for generating kernel header for now)
https://github.com/Lynnrin-Studio/android_vendor_xiaomi_thyme/tree/twelve

## Number of ROM's you maintain officially
ArrowOS, PixelExperience

## Any Exceptions/special concern?
Need [this](https://gerrit.pixelexperience.org/c/frameworks_base/+/17396) to make FOD dimming working

### Telegram username
@LynnrinChan

### GitHub username
@LynnrinChan

**Comment by jjpprrrr** [comment]
Ignoring neverallows is not allowed.

https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/blob/twelve/BoardConfig.mk#L138

**Comment by KaguraRinko** [comment]
> Ignoring neverallows is not allowed.
> 
> https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/blob/twelve/BoardConfig.mk#L138

Forget that sorry, will fix it asap

**Comment by KaguraRinko** [comment]
> Ignoring neverallows is not allowed.
> 
> https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/blob/twelve/BoardConfig.mk#L138

Sir, fixed now, please check again.

**Comment by KaguraRinko** [comment]
Due to some problems found, it can't go official right now. will apply again after fixed all problems.

**Comment by KaguraRinko** [comment]
> https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/twelve

Neverallow fixed now

**Comment by ZIDAN44** [comment]
Why translation https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/arrow-12.1/parts/res/values-zh left here ?
Also https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/twelve/parts/res/values

Try to adapt you parts with pixelexperience_settings_resources repo.

**Comment by KaguraRinko** [comment]
> Why translation https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/arrow-12.1/parts/res/values-zh left here ? Also https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/twelve/parts/res/values
> 
> Try to adapt you parts with pixelexperience_settings_resources repo.

Done sir, please check twelve branch
https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/twelve/parts/res

**Comment by ZIDAN44** [comment]
> > Why translation https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/arrow-12.1/parts/res/values-zh left here ? Also https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/twelve/parts/res/values
> > Try to adapt you parts with pixelexperience_settings_resources repo.
> 
> Done sir, please check twelve branch https://github.com/Lynnrin-Studio/android_device_xiaomi_thyme/tree/twelve/parts/res

Oho yeah

**Comment by ZIDAN44** [comment]
Everything looks fine now. Now wait for Gerrit commits get merged.
