### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by GhostRider1998** [PixelExperience/official_devices#2592]
## Device you want to apply for

Redmi Note 7

## Device tree sources

https://github.com/PixelExperience-Devices/device_xiaomi_lavender
https://github.com/PixelExperience-Devices/kernel_xiaomi_lavender
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_lavender

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No. Using the device sources from previous maintainer. Everything will be updated.

### Telegram username

ghostrider1998

### GitHub username

ghostrider1998

**Comment by jjpprrrr** [comment]
Thanks for the application. Unfortunately, we cannot take a maintainer whose GitHub profile was created 9 hours ago, and there are no development activities at all. Besides, you are using the existing code in the PE devices org, so we have no means of evaluating your knowledge and capability in maintaining android.

You are welcome to come back and apply again in the future.
