### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by retrozenith** [PixelExperience/official_devices#2602]
## Device you want to apply for

Samsung Galaxy A50 (A505FN)

## Device tree sources

< -- Device Tree -- >
https://github.com/Galaxya50/android_device_samsung_a505fn
< -- Common Tree -- >
https://github.com/Galaxya50/android_device_samsung_a50-common
< -- Kernel -- >
https://github.com/Galaxya50/android_kernel_samsung_a50-common
< -- Vendor -- >
https://github.com/Galaxya50/android_vendor_samsung_a505fn
< -- Vendor Common -- >
https://github.com/Galaxya50/android_vendor_samsung_a50-common

## Number of ROM's you maintain officially

ZERO

## Any Exceptions/special concern?

Yes. I do have issues with fingerprint on Lineage Even some guys who are maintainers tried but did not get to work . I also know that is not allowed but its not devs fault and its phone.

### Telegram username

@v1ctor_cris

### GitHub username

victor4cris

**Comment by ZIDAN44** [comment]
Hello there !!

Where did you pushed your modified trees for PE ? & Did you read our PE CoC ?

**Comment by retrozenith** [comment]
Via web and PC For web I use a specific account and for PC another one. Also what do you mean by "CoC". Thanks for fast answer !

**Comment by retrozenith** [comment]
Oh code of conduct . Yes, I did that before apply.

**Comment by retrozenith** [comment]
> Hello there !!
> 
> Where did you pushed your modified trees for PE ? & Did you read our PE CoC ?
> 
> 

Also trees for PE are old but I will update them bc in last versions I used Lineage trees and modified for Pixel Experience.

**Comment by retrozenith** [comment]
Should I make a device tree branch with all the changes needed for good documentation requirements ?

**Comment by jjpprrrr** [comment]
This is an application for the official PE maintainer. Don't you think you should at least include buildable source code for PE?

**Comment by retrozenith** [comment]
> This is an application for the official PE maintainer. Don't you think you should at least include buildable source code for PE?

I have but it's not up to date also base of Lineage os branch was built from pe device tree

**Comment by retrozenith** [comment]
Also should I update and try again ?

**Comment by jjpprrrr** [comment]
Closing this issue as the applicant is clearly not ready. This is a waste of time. Please do not do this again.
