### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ArixElo** [PixelExperience/official_devices#2609]
## Device you want to apply for

Mi 11 Lite 5G (renoir)

## Device tree sources

https://github.com/ArixElo/device_xiaomi_renoir
https://github.com/ArixElo/device_xiaomi_sm7350-common
https://github.com/ArixElo/android_kernel_xiaomi_sm7350
https://gitlab.com/ArixElo/vendor_xiaomi

## Number of ROM's you maintain officially

ProjectStreak

## Any Exceptions/special concern?

I can't convert the common tree to other name than sm8350, because otherwise fingerprint and vibration motor are not working, so the repo name will be changed only.

### Telegram username

ArixElo

### GitHub username

ArixElo

**Comment by ArixElo** [comment]
Fixed stuff that i needed to fix, reopening application.

**Comment by jjpprrrr** [comment]
Hi! Thanks for the application.
First of all, could you please rename the common repo to sm7350-common and make sure the include paths are updated? It is unlikely our sm8350-common (the one me and some other current maintainers are working on) will be compatible with renoir.
The rest looks good to me.

**Comment by ArixElo** [comment]
> Hi! Thanks for the application. First of all, could you please rename the common repo to sm7350-common and make sure the include paths are updated? It is unlikely our sm8350-common (the one me and some other current maintainers are working on) will be compatible with renoir. The rest looks good to me.

Hi, as I stated in concerns, i can't fully convert to sm7350, but i can change vendor and common paths, rest things will remain as before.

**Comment by jjpprrrr** [comment]
Yes that should be enough. We just need the repo names to be different. You may also need to update renoir tree with the new path.

**Comment by ArixElo** [comment]
> Yes that should be enough. We just need the repo names to be different. You may also need to update renoir tree with the new path.

Hi, I changed paths, so am I accepted?

**Comment by jjpprrrr** [comment]
Great. Welcome aboard! Feel free to make PRs to official_devices and the wiki repo. Closing this issue.
