### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mercertom** [PixelExperience/official_devices#2637]
## Device you want to apply for

billie

## Device tree sources

https://github.com/PixelExperience-Devices/device_oneplus_billie

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

TT

### GitHub username

mercertom

**Comment by ZIDAN44** [comment]
Hello there !

Thanks for the application. You are using the existing code in the PE devices org, so we have no means of evaluating your knowledge and capability in maintaining android.

You are welcome to come back and apply again in the future.

**Comment by mercertom** [comment]
@ZIDAN44  Why isn't there an official release for billie if PE already has a good device tree? I'm confused by this whole setup. It seemed to me the only thing missing was a person willing to be official maintainer.

**Comment by ZIDAN44** [comment]
> @ZIDAN44 Why isn't there an official release for billie if PE already has a good device tree? I'm confused by this whole setup. It seemed to me the only thing missing was a person willing to be official maintainer.

Looks like you didn't read Pixel Experience CoC docs yet.. How can I know your android/building roms skills without your device trees ? Pls check Pixel Experience doc before re-apply.

**Comment by mercertom** [comment]
I don't know what those are. Maybe I read them, maybe I didn't. I can't
know your internal lingo as an outsider. Please link to the CoC docs. My
understanding is building a rom is straightforward. PE doesn't lack the
skills to build roms. PE lacks a person willing to be an official
maintainer for each of the devices that aren't officially supported. If you
have a device tree for a device, and you know how to build roms, why don't
you officially support that device? My understanding is that you lack
someone responsible for it. Clearly, you think it's something else. I don't
know what that is. I've read the docs about applying to be a maintainer,
otherwise, how would I have made this application in accordance with the
documentation? Sheer luck?

**Comment by ZIDAN44** [comment]
I didn't get your point. And nope PE don't lacks a person willing to be an official. And from the beginning I am asking you to show your trees but you didn't..

Thanks for your time 🙂
