### ISSUE TITLE
New maintainer for RMX2061

### ISSUE THREAD

**Issue by debdeep199x** [PixelExperience/official_devices#2643]
## Device you want to apply for

realme 6 Pro (RMX2061)

## Device tree sources

https://github.com/rm6p/android_device_realme_RMX2061
https://github.com/rm6p/android_device_realme_sm7125-common
https://github.com/rm6p/android_kernel_realme_sm7125
https://gitlab.com/crdroidandroid/android_vendor_realme_RMX2061

## Number of ROM's you maintain officially

One (1)

## Any Exceptions/special concern?

Would like to keep vendor in Gitlab if possible as realme likes to go trigger happy with DMCAs (proprietary cam blobs, doesn't work without them (one license file to be specific)).

### Telegram username

telegram.me/debdeep199x

### GitHub username

github.com/debdeep199x

**Comment by ZIDAN44** [comment]
Hello there !

I have checked your trees & noticed few things as of now

1. You killed autho of some commits in your device tree.
2. Your kernel upstream looks wrong. (You picked all upstream commits rather then using merge command)

Fix them and let me know ;)

**Comment by debdeep199x** [comment]
Thanks for a taking a look. I'll fix those and let you know. Also a few commits like encryption, neverallows and some overlays didn't have authors. 
The rest I'll fix. Thanks.

**Comment by debdeep199x** [comment]
> Hello there !
> 
> I have checked your trees & noticed few things as of now
> 
> 1. You killed autho of some commits in your device tree.
> 2. Your kernel upstream looks wrong. (You picked all upstream commits rather then using merge command)
> 
> Fix them and let me know ;)

Hello again. 
The trees are now rebased as per the requirements. 

Please let me know if any more modifications are reqd to the trees. 
Also the trees have been tested after rebase and it boots fine. 

Thanks.

**Comment by ZIDAN44** [comment]
Still can see some commits on your common tree that don't have any author
https://github.com/rm6p/android_device_realme_sm7125-common/commit/eef837413b228e77cef1a1a9f38c16cb0dcd4a1a
https://github.com/rm6p/android_device_realme_sm7125-common/commit/4d6725fc970b6f44f1129a35366f925335699f23
https://github.com/rm6p/android_device_realme_sm7125-common/commit/eb69cdbc673cf491e8f8f9824efbfd0e198658b9
https://github.com/rm6p/android_device_realme_sm7125-common/commit/fa3af9255cdd4b3cd9cc0450ba3ed1421086dec4
And possibly more on

Also there are some commits those don't make scene or beginning done to hide other commits errors
https://github.com/rm6p/android_device_realme_sm7125-common/commit/3c3f0068a14901e8389dcf585da11410f70a387d
https://github.com/rm6p/android_device_realme_sm7125-common/commit/157b2b7ac308fe4a64cb64f5d0b50f856d6e31c8
https://github.com/rm6p/android_device_realme_sm7125-common/commit/51f0225727c33ab4a51f57ebf3e812125e54064a

https://github.com/rm6p/android_device_realme_sm7125-common/commit/0062f68411036f6707f8469e7992b55b9d898882 this one looks incomplete..

Also seems like you pick a commit and then revert it after one or two commit.. just drop them completely..

 Cleanup your commits properly & pick or add which you need or allowed.

**Comment by ZIDAN44** [comment]
For kernel

First of all boeffla wakelocker not allowed.

What is the reason for this commit https://github.com/rm6p/android_kernel_realme_sm7125/commit/0ac7eb3b52b240cefd23d8868cfa4c25d1214e8d ?

https://github.com/rm6p/android_kernel_realme_sm7125/commit/4da862fa7f70808d0e7050ccdbfd228ef932ef17 & https://github.com/rm6p/android_kernel_realme_sm7125/commit/24f9f346af7828f6a6750f1b49968466a6e7afa2 should have been done at once

**Comment by debdeep199x** [comment]
Hello. Apologies for the delayed response.

The required changes have been made.

1. for sm7125-common all changes that had been added/made and later removed or reverted has been dropped. this includes stuff like system/vendor props, boardconfig flags etc. 
2. cleaned up kernel. removed boeffla wakelock blocker.

Hope the trees are satisfactory. 

Thank you.

**Comment by jjpprrrr** [comment]
Kernel looks good to me.

**Comment by debdeep199x** [comment]
> Kernel looks good to me.

Thank you for taking a look.

**Comment by ZIDAN44** [comment]
Device trees are looking fine now

**Comment by ZIDAN44** [comment]
Welcome aboard! Feel free to submit PRs to official_devices and wiki.

**Comment by debdeep199x** [comment]
> Welcome aboard! Feel free to submit PRs to official_devices and wiki.

Thank You. :)
