### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by popogijo** [PixelExperience/official_devices#2655]
## Device you want to apply for

oneplus 6/6t

## Device tree sources

https://github.com/popogijo/device_oneplus_enchilada
https://github.com/popogijo/device_oneplus_fajita
https://github.com/popogijo/device_oneplus_sdm845-common
https://github.com/popogijo/kernel_oneplus_sdm845
https://github.com/popogijo/vendor_oneplus_enchilada
https://github.com/popogijo/vendor_oneplus_fajita
https://github.com/popogijo/vendor_oneplus_sdm845-common
https://github.com/popogijo/hardware_oneplus

## Number of ROM's you maintain officially

None. Was a maintainer for aquarios rom.

## Any Exceptions/special concern?

Had to remove several gapps from the gapps package to get it to build. Noe sure if this is allowed. I'm a little rusty on git, but it's coming back. Hope this application is better.

### Telegram username

popo

### GitHub username

popogijo

**Comment by ZIDAN44** [comment]
Hello there..!!

Private trees are not allowed sorry.

**Comment by popogijo** [comment]
Sorry dude. I'll take a look at the trees when I get home. About a week.
Chuck

**Comment by MabezDev** [comment]
@popogijo Are you still looking to become a maintainer for the OnePlus 6/6T? Would be really cool to run PE on my aging 6T :)

**Comment by popogijo** [comment]
Hey dude,
Sorry, I'm taking a step back from maintaining at the moment. I needed a few lineage caf files not included in the pixel experience source. Was going to try and get them pushed, but a couple of family health emergencies came up that required travel. Maybe by next cycle I can get involved again.
popogijo
