### ISSUE TITLE
New maintainer for Exynos 9810 Series

### ISSUE THREAD

**Issue by dylanneve1** [PixelExperience/official_devices#2667]
## Device you want to apply for

Galaxy S9 (starlte), Galaxy S9+ (star2lte) and Galaxy Note 9 (crownlte)

## Device tree sources

Device Repos
https://github.com/universal9810/android_device_samsung_starlte/tree/twelve-plus
https://github.com/universal9810/android_device_samsung_star2lte/tree/twelve-plus
https://github.com/universal9810/android_device_samsung_crownlte/tree/twelve-plus

Common Repo
https://github.com/universal9810/android_device_samsung_exynos9810-common/tree/twelve-plus

Vendor Repos
https://github.com/universal9810/android_vendor_samsung_exynos9810-common/tree/twelve-plus
https://github.com/universal9810/android_vendor_samsung_starlte/tree/twelve-plus
https://github.com/universal9810/android_vendor_samsung_star2lte/tree/twelve-plus
https://github.com/universal9810/android_vendor_samsung_crownlte/tree/twelve-plus

## Number of ROM's you maintain officially

Currently maintaining one other official ROM

## Any Exceptions/special concern?

- VoLTE does not work
- Encryption does not work unless forced from first boot, if this is preferable to having no encryption then it can be implemented

### Telegram username

dylanneve1

### GitHub username

dylanneve1

**Comment by dylanneve1** [comment]
Have rebased on latest Lineage trees with my own modifications here

Device
https://github.com/Sexynos/android_device_samsung_starlte/tree/twelve
https://github.com/Sexynos/android_device_samsung_star2lte/tree/twelve
https://github.com/Sexynos/android_device_samsung_crownlte/tree/twelve

Common Repo
https://github.com/Sexynos/android_device_samsung_exynos9810-common/tree/twelve

Vendor Repos
https://github.com/Sexynos/android_vendor_samsung_exynos9810-common/tree/twelve
https://github.com/Sexynos/android_vendor_samsung_starlte/tree/twelve
https://github.com/Sexynos/android_vendor_samsung_star2lte/tree/twelve
https://github.com/Sexynos/android_vendor_samsung_crownlte/tree/twelve

**Comment by jjpprrrr** [comment]
Hi! Thanks for the application. I apologize for the delay as most of the core team members have been preoccupied with other stuff.

The device and vendor repos look good to me. May I ask where the kernel source is? Even if you plan to use someone else's kernel source, you still need to present it for review.

**Comment by jjpprrrr** [comment]
Regarding encryption, if what you meant is that encryption only works when forced from fstab, then that is perfectly normal for FBE. Encryption is required for PE if it works on stock.

**Comment by dylanneve1** [comment]
Thank you for the response! For kernel source I will be using the following repo from our devices ArrowOS maintainer as he is the main kernel developer that we have.

https://github.com/ArrowOS-Devices/android_kernel_samsung_exynos9810

As for encryption that is understood, I can force it from fstab

**Comment by jjpprrrr** [comment]
Kernel seems fine as well. Welcome aboard! Feel free to submit PRs to official_devices and wiki. Closing this issue.
