### ISSUE TITLE
New maintainer request for FP3

### ISSUE THREAD

**Issue by teamb58** [PixelExperience/official_devices#2668]
## Device you want to apply for

Fairphone FP3

## Device tree sources

https://github.com/teamb58/android_device_fairphone_FP3
https://github.com/teamb58/android_kernel_fairphone_sdm632
https://github.com/teamb58/vendor_fairphone_fp3

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

No

### Telegram username

Bharath

### GitHub username

teamb58

**Comment by teamb58** [comment]
Hi @ZIDAN44 .
Any update on this request?

Thanks.

**Comment by teamb58** [comment]
Why is my request being ignored? It's been more than a week since I submitted this but there has been no response from any of the assignee.

Let me know if I have to do anything else from my side.

Thanks.

**Comment by jjpprrrr** [comment]
Hi! Thanks for the application. I apologize for the delay as most of the core team members have been preoccupied with other stuff.

According to CoC, granting write permission to a generic sysfs label is not allowed. If the init script needs access to certain nodes, label the node and grant access to that label only.
https://github.com/teamb58/android_device_fairphone_FP3/blob/snow/sepolicy/vendor/qti_init_shell.te#L1

The rest looks good to me.

**Comment by teamb58** [comment]
Thank you very much.

No problem, I shall drop that policy entirely and revisit if it gets critical.

**Comment by teamb58** [comment]
This is very disappointing. It's been 25 days since I created this request and none of the 7 assignees have some minutes of their precious time to look into this?

This is clear ignorance for new/incoming maintainers. The issues that were created after this have been approved and closed but not mine.

Very very disappointing. I am done with PE. Thank you for not looking into my issue and for not accepting it.

Thanks.

**Comment by jjpprrrr** [comment]
Wait a minute. I pointed out a CoC violation, and you said you "shall drop that policy entirely and revisit if it gets critical". You never said you have done it already and never told me if I should look at your tree again.

I already give you a pass on everything else, and I have been waiting for you to fix the sepolicy. Is there something I am not aware of?
