### ISSUE TITLE
New maintainer for a225f

### ISSUE THREAD

**Issue by rolimlucas** [PixelExperience/official_devices#2669]
## Device you want to apply for

samsung a22 4g (a225f)

## Device tree sources

https://github.com/rolimlucas/a225f
https://github.com/rolimlucas/kernel_a225f
https://github.com/rolimlucas/vendor_a225f

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

rolim_lucas

### GitHub username

rolimlucas

**Comment by ZIDAN44** [comment]
Hello there!

You killed all commit autho of your trees and its not allowed for PE official ;-;
