### ISSUE TITLE
New maintainer for nio

### ISSUE THREAD

**Issue by JarlPenguin** [PixelExperience/official_devices#2674]
## Device you want to apply for

nio

## Device tree sources

https://github.com/JarlPenguin/device_motorola_nio
https://github.com/JarlPenguin/kernel_motorola_sm8250
https://github.com/JarlPenguin/vendor_motorola_nio

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

Needs either https://github.com/JarlPenguin/device_motorola_nio/commit/3052a651685fc64f2efc1af61fc01d4515511ba8 merged in source, or need to remove system/qcom syncing by default
https://github.com/PixelExperience/hardware_qcom-caf_sm8250_display needs to have LA.UM.9.12.r1-13500.01-SMxx50.QSSI12.0 merged

### Telegram username

JarlPenguin

### GitHub username

JarlPenguin

**Comment by Hasaber8** [comment]
The two exceptions can stay on gerrit until we merge them into source.
Everything else seems fine, just don't push the DNM commit from NIO tree to main device org.

**Comment by Hasaber8** [comment]
@JarlPenguin could you push the necessary changes to gerrit?

**Comment by Hasaber8** [comment]
Aside from the changes needed, the tree seems absolutely fine. Will close the issue after that stuff is up. Until then @JarlPenguin please make the necessary PRs, you already know the drill xD.

**Comment by JarlPenguin** [comment]
Alright, was busy for a couple of days, will do soon
