### ISSUE TITLE
New maintainer for Xiaomi Mi A3 (laurel_sprout)

### ISSUE THREAD

**Issue by zlewchan** [PixelExperience/official_devices#2675]
## Device you want to apply for

Xiaomi Mi A3 (laurel_sprout)

## Device tree sources

https://github.com/zlewchan/android_device_xiaomi_laurel_sprout/tree/twelve-PixelExperience
https://github.com/zlewchan/android_kernel_xiaomi_laurel_sprout
https://github.com/zlewchan/android_vendor_xiaomi_laurel_sprout

## Number of ROM's you maintain officially

2 (CrDroid and Project Streak)

## Any Exceptions/special concern?

Yes. Due to limited space on the device I needed to add remove packages, otherwise the ROM couldn't be built. The list is overall very minimal and it's picked from your devices organization [Link](https://github.com/PixelExperience-Devices/device_xiaomi_msm8953-common/commit/9749c6ec26c718094e8b00fabd9a549a18057d87). Also Need [this](https://gerrit.pixelexperience.org/c/frameworks_base/+/17396) to make FOD dimming working (same thing as thyme).

### Telegram username

zlewchan

### GitHub username

zlewchan

**Comment by jjpprrrr** [comment]
Hi! Thanks for the application. I apologize for the delay as most of the core team members have been preoccupied with other stuff.

According to CoC, granting write permission to a generic sysfs label is not allowed. If the fingerprint hal needs access to certain nodes, label the node and grant access to that label only.
https://github.com/zlewchan/android_device_xiaomi_laurel_sprout/blob/twelve-PixelExperience/sepolicy/vendor/hal_fingerprint_default.te#L14

Not sure why would prevent userspace boosting from kernel when your device tree ships libperfmgr with schedtune boosts in powerhint? AFAIK that commit was originally intended for custom kernels that did not have control over userspace. You are building the whole ROM, so this behavior makes no sense.
https://github.com/zlewchan/android_kernel_xiaomi_laurel_sprout/commit/cdcae0c8bb003b02f674a6a5aa544867265ba9dd

**Comment by zlewchan** [comment]
> Hi! Thanks for the application. I apologize for the delay as most of the core team members have been preoccupied with other stuff.
> 
> According to CoC, granting write permission to a generic sysfs label is not allowed. If the fingerprint hal needs access to certain nodes, label the node and grant access to that label only. https://github.com/zlewchan/android_device_xiaomi_laurel_sprout/blob/twelve-PixelExperience/sepolicy/vendor/hal_fingerprint_default.te#L14
> 
> Not sure why would prevent userspace boosting from kernel when your device tree ships libperfmgr with schedtune boosts in powerhint? AFAIK that commit was originally intended for custom kernels that did not have control over userspace. You are building the whole ROM, so this behavior makes no sense. [zlewchan/android_kernel_xiaomi_laurel_sprout@cdcae0c](https://github.com/zlewchan/android_kernel_xiaomi_laurel_sprout/commit/cdcae0c8bb003b02f674a6a5aa544867265ba9dd)

Hello,
All the requested changes have been done. Please check again.

**Comment by jjpprrrr** [comment]
Looks good to me. Welcome aboard! Feel free to submit PRs to official_devices and wiki. I'm closing this issue.
