### ISSUE TITLE
New maintainer for Moto X4 (payton)

### ISSUE THREAD

**Issue by ExactExampl** [PixelExperience/official_devices#2683]
## Device you want to apply for

Motorola Moto X4 (payton)

## Device tree sources

https://github.com/ExactExampl/device_motorola_payton
https://github.com/ExactExampl/kernel_motorola_payton
https://github.com/ExactExampl/vendor_motorola_payton

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

@ExactXmpl

### GitHub username

ExactExampl

**Comment by Hlcpereira** [comment]
Everything seems to be ok as far as I can see. Welcome aboard, and please open the PRs for official_devices and wiki whenever possible. I'm closing this issue.
