### ISSUE TITLE
New maintainer - OnePlus 7

### ISSUE THREAD

**Issue by shantanu-sarkar** [PixelExperience/official_devices#2703]
## Device you want to apply for

OnePlus 7 (guacamoleb)

## Device tree sources

https://github.com/shantanu-sarkar/device_oneplus_guacamoleb-merged
https://github.com/shantanu-sarkar/kernel_sm8150
https://github.com/shantanu-sarkar/vendor_oneplus_guacamoleb-merged
https://github.com/shantanu-sarkar/android_hardware_oneplus
https://gitlab.com/shantanu-sarkar/vendor_oneplus_apps_guacamoleb

## Number of ROM's you maintain officially

2 - LineageOS and AOSP Extended 

## Any Exceptions/special concern?

No

### Telegram username

shantanusarkar

### GitHub username

shantanu-sarkar

**Comment by KakatkarAkshay** [comment]
https://github.com/shantanu-sarkar/device_oneplus_guacamoleb-merged/commit/d6bd050485c2f1c8a618520f1b5d988ab22646dd

Isn't allowed on twelve and repainter is already included on twelve-plus

https://github.com/shantanu-sarkar/device_oneplus_guacamoleb-merged/commit/547778a043005b3b98044b53bb22aa234aeee7f3

PE does not have needed source side comments for this and will probably not add it

https://github.com/shantanu-sarkar/device_oneplus_guacamoleb-merged/commit/a46b00caf3e88bb70ab9b0d28fc74e8596cf5d8f
OnePlus camera is fine but OnePlus gallery cannot be shipped in PE

**Comment by KakatkarAkshay** [comment]
Looks good, Welcome aboard! Feel free to submit PRs to official_devices and wiki. Closing this issue.
