### ISSUE TITLE
New maintainer for oxygen

### ISSUE THREAD

**Issue by halibw** [PixelExperience/official_devices#2725]
## Device you want to apply for

Xiaomi Max 2 (oxygen)

## Device tree sources

https://github.com/halibw/android_device_xiaomi_oxygen/tree/twelve
https://github.com/halibw/android_kernel_xiaomi_oxygen/tree/twelve
https://github.com/halibw/proprietary_vendor_oxygen/tree/twelve

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

harisFY

### GitHub username

halibw

**Comment by KakatkarAkshay** [comment]
Looks good, Welcome aboard! Saw your PRs on official_devices and wiki, will merge those. Closing this issue.
