### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iamimmanuelraj** [PixelExperience/official_devices#2747]
## Device you want to apply for

Xiaomi Mi A2 [jasmine_sprout]

## Device tree sources

https://github.com/PixelExperience-MiA2-Mi6X

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

Told to jhenrique about trees

### Telegram username

iamimmanuelraj

### GitHub username

iamimmanuelraj

**Comment by ZIDAN44** [comment]
Hello There !

Where is you trees ?

**Comment by iamimmanuelraj** [comment]
> Hello There !
> 
> Where is you trees ?

Umm...its actually private in that org...there is a slight issues going so ive mentioned @jhenrique09 about it and he told he will take care so ig its good as of now

**Comment by ZIDAN44** [comment]
Ok then.. its upto jhenrique09

**Comment by iamimmanuelraj** [comment]
> Ok then.. its upto jhenrique09

Btw u asked to see the trees?
Are you one of the reviewers? Reviewers have access and i dont see you in reviewers list

**Comment by Hlcpereira** [comment]
As per Item #4 in the [Maintainers Requirements](https://github.com/PixelExperience/docs/blob/master/maintainers_requirements.md) the trees, vendor and kernel sources and all modified repositories sources (if any) for the device must be public upon review. Until this being granted, the application is to be considered either frozen or completely rejected.

**Comment by iamimmanuelraj** [comment]
Hi @Hlcpereira i spoke with @jhenrique09 about this long before in dm and only after his approval i have made this issues, I said to him that i will make my trees public if i get selected as there are numerous problems going on in the community . And i gave access to all the reviewers here and but no one except akshay did accept it and i gave re request to others yesterday again. So please check on it and do the needful,

**Comment by Hlcpereira** [comment]
Devices sources are fine as far I could check. @jjpprrrr if possible please check kernel sources for further validation please.

**Comment by jjpprrrr** [comment]
> Devices sources are fine as far I could check. @jjpprrrr if possible please check kernel sources for further validation please.

The kernel looks good to me.

**Comment by iamimmanuelraj** [comment]
So wer good to go now right?
Shall i make the necessary changes?

**Comment by jhenrique09** [comment]
https://github.com/PixelExperience/official_devices/pull/2768
https://github.com/PixelExperience/wiki/pull/221
