### ISSUE TITLE
New Maintainer For Redmi Note 7 & 7S (Lavender).

### ISSUE THREAD

**Issue by ImSurajx** [PixelExperience/official_devices#2762]
## Device you want to apply for

Redmi Note 7 & 7S

## Device tree sources

https://github.com/ImSurajx/android_device_xiaomi_lavender
https://github.com/ImSurajx/android_vendor_xiaomi_lavender
https://github.com/ImSurajx/android_kernel_xiaomi_lavender
https://gitlab.com/ImSurajxD/packages_apps_android

## Number of ROM's you maintain officially

0, But Unofficially I Am Maintaing Few Roms With Stable Edition Tag From Last 6 Months, Like PixelExperience & Plus & Many Others. 

## Any Exceptions/special concern?

No

### Telegram username

ImSurajx

### GitHub username

ImSurajx

**Comment by veshrao** [comment]
ah yes kanger + stable edition buildbot applying for pixel experience, AXAXAXAXAXA

**Comment by Hlcpereira** [comment]
Rejected upon the basis of another application for the device be accepted. Thanks for applying anyway
