### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AaradhayVijay** [PixelExperience/official_devices#2764]
## Device you want to apply for

lavender 

## Device tree sources

https://github.com/AaradhayVijay/device_xiaomi_lavender
https://github.com/AaradhayVijay/device_xiaomi_sdm660-common
https://github.com/AaradhayVijay/kernel_xiaomi_lavender
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sdm660-common
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_lavender

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

Inferno964

### GitHub username

AaradhayVijay

**Comment by Hlcpereira** [comment]
@AaradhayVijay open the PR with the revert for the official_devices repo

**Comment by AaradhayVijay** [comment]
> @AaradhayVijay open the PR with the revert for the official_devices repo

Done.

**Comment by KUIpru** [comment]
DEAR PE TEAM , PLEASE DON'T LET HIM TAKE OFFICIAL , BOT MAKIN BOT BUILDS , COULDN'T RUN EVEN HIS OWN PROJECT . HE KEEPS DROPPING AND APPLYING AGAIN , HE NEED SOME MENTAL SUPPORT .

**Comment by KUIpru** [comment]
BOTS ARE NOT SUPPOSED TO TAKE PE

**Comment by Hlcpereira** [comment]
Closing this as PR #2767 was merged
