### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Pulkit077** [PixelExperience/official_devices#2773]
## Device you want to apply for

Redmi Note 10 Pro (sweet)

## Device tree sources

https://github.com/Pulkit077/device_xiaomi_sweet
https://github.com/Pulkit077/vendor_xiaomi_sweet
https://github.com/Pulkit077/kernel_xiaomi_sweet

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

Pulkit077

### GitHub username

Pulkit077

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying.

This application is going to be reviewed only after the beta period of Android 13 is over, as the applications are closed as announced on [September 4th in our Telegram channel](https://t.me/PixelExperience/7231).

Thanks very much.

**Comment by Hlcpereira** [comment]
Everything seems to be A-Ok. Feel free to open up the PR for both official_devices and wiki adding sweet.

**Comment by Pulkit077** [comment]
Thank You! I've opened PR for both
