### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by onkarsinghsahil** [PixelExperience/official_devices#2774]
## Device you want to apply for

mido

## Device tree sources

https://github.com/onkarsinghsahil/device_xiaomi_mido/tree/12.1L
https://github.com/onkarsinghsahil/android_kernel_xiaomi_mido/tree/twelve
https://github.com/onkarsinghsahil/proprietary_vendor_xiaomi/tree/twelve

## Number of ROM's you maintain officially

nil

## Any Exceptions/special concern?

No

### Telegram username

https://t.me/error7951

### GitHub username

https://github.com/onkarsinghsahil

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying however I must say that applications are closed for Android 12. Android 13 applications aren't open, and as mido is a hwkeys device we have no plans in supporting those on 13.

Once again thanks for applying.

**Comment by onkarsinghsahil** [comment]
okay sir 
thanks for replying

**Comment by onkarsinghsahil** [comment]
> Hello. Thanks for applying however I must say that applications are closed for Android 12. Android 13 applications aren't open, and as mido is a hwkeys device we have no plans in supporting those on 13.
> 
> Once again thanks for applying.

okay sir
thanks for replying
