### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ihardcore** [PixelExperience/official_devices#2795]
## Device you want to apply for

Moto Edge X30 

## Device tree sources

https://github.com/ihardcore/android_device_motorola_hiphic
https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-S0SC32.16-49-4

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

K40 PE ROM user since released

### Telegram username

lok

### GitHub username

ihardcore

**Comment by RisenID** [comment]
That looks like a tree for twrp recovery, not for a rom. Will not work to build pe rom or any other rom.
