### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by GiovanYCringe** [PixelExperience/official_devices#2815]
## Device you want to apply for

Samsung Galaxy A50

## Device tree sources

https://github.com/GiovanYCringe/device_samsung_a50-common
https://github.com/GiovanYCringe/android_kernel_samsung_a50
https://github.com/GiovanYCringe/android_kernel_samsung_a50
https://github.com/GiovanYCringe/android_vendor_samsung_a50-common
https://github.com/GiovanYCringe/android_vendor_samsung_a505f

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

No

### Telegram username

https://t.me/GiovanYCringe

### GitHub username

https://github.com/GiovanYCringe

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying.

This application is going to be reviewed only after the beta period of Android 13 is over, as the applications are closed as announced on [September 4th in our Telegram channel](https://t.me/PixelExperience/7231).

Thanks very much

**Comment by GiovanYCringe** [comment]
Ok, Thanks

**Comment by Hlcpereira** [comment]
Closing this as per what has been communicated internally about the Galaxy A50/A50s maintainship
