### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Broly1** [PixelExperience/official_devices#2837]
## Device you want to apply for

Oneplus-8t

## Device tree sources

https://github.com/Broly1/android_device_oneplus_kebab
https://github.com/Broly1/device_oneplus_sm8250-common
https://github.com/Broly1/android_hardware_oplus
https://github.com/Broly1/vendor_oneplus_kebab
https://github.com/Broly1/vendor_oneplus_sm8250-common
https://github.com/PixelExperience-Devices/kernel_oneplus_sm8250

## Number of ROM's you maintain officially

none

## Any Exceptions/special concern?

No

### Telegram username

@Broly_1

### GitHub username

Broly1

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying.

Unfortunately we have to reject your application at the moment.

"Why?"
The main reason has to do with a noticible lack of experience for the amount of responsability that comes with been part of the PixelExperience team.

That doesn't mean however that if you apply at a near future you'll be rejected aswell. Feel free to apply whenever you've gathered more experience.

Best regards.
