### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kleidione** [PixelExperience/official_devices#2867]
## Device you want to apply for

Veux and Peux

## Device tree sources

https://github.com/kleidione/device_xiaomi_veux
https://github.com/kleidione/device_xiaomi_veux-kernel
https://github.com/kleidione/kernel_xiaomi_sm6375
https://github.com/kleidione/vendor_xiaomi_veux

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

@kleidione

### GitHub username

kleidione

**Comment by Hlcpereira** [comment]
LiveDisplay is not available on Standard Edition, only on Plus Edition builds. Everything else seems to be ok though.

**Comment by kleidione** [comment]
This I can drop, it didn't turn out the way I wanted kkk

Em qua., 9 de nov. de 2022 às 17:21, Henrique Pereira <
***@***.***> escreveu:

**Comment by kleidione** [comment]
Ready done rebase without livedisplay

Em qua., 9 de nov. de 2022 às 17:21, Henrique Pereira <
***@***.***> escreveu:

**Comment by Hlcpereira** [comment]
Feel free to open up a PR for both official_devices and wiki

**Comment by kleidione** [comment]
Thanks 😎

Em qua., 9 de nov. de 2022 às 17:34, Henrique Pereira <
***@***.***> escreveu:

**Comment by Hlcpereira** [comment]
Merged on #2878
