### ISSUE TITLE
New maintainer (Co-maintainership)

### ISSUE THREAD

**Issue by windowz414** [PixelExperience/official_devices#2898]
## Device you want to apply for

Pixel 2/2 XL (walleye/taimen)

## Device tree sources

https://github.com/PixelExperience-Devices/device_google_walleye
https://github.com/PixelExperience-Devices/device_google_taimen
https://github.com/PixelExperience-Devices/device_google_wahoo
https://github.com/PixelExperience-Devices/kernel_google_wahoo
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_google_taimen
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_google_walleye

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No(t yet?)

### Telegram username

@lndscpr

### GitHub username

windowz414

**Comment by PixelBoot** [comment]
Looks good to me!
I'll let @jhenrique09 @Hlcpereira take care of the rest :D

**Comment by windowz414** [comment]
@PixelBoot perfect, thanks! Let's see what others will say! x3

**Comment by PixelBoot** [comment]
I'll handle it instead

**Comment by windowz414** [comment]
> I'll handle it instead

@PixelBoot LMAO
