### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by neikos4962** [PixelExperience/official_devices#2899]
## Device you want to apply for

Redmi Note 11 Pro 5g Poco X4 Pro 5G

## Device tree sources

https://github.com/alexandrusemina/device_xiaomi_veux
https://github.com/alexandrusemina/vendor_xiaomi_veux
https://github.com/alexandrusemina/device_xiaomi_veux-kernel

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

No

### Telegram username

@semialex16

### GitHub username

alexandrusemina

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying.

Unfortunately we have to reject your application at the moment.

"Why?"
The main reason has to do with a noticible lack of experience for the amount of responsability that comes with been part of the PixelExperience team.

That doesn't mean however that if you apply at a near future you'll be rejected aswell. Feel free to apply whenever you've gathered more experience.

Best regards.
