### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Broly1** [PixelExperience/official_devices#2906]
## Device you want to apply for

OnePlus 8T kebab

## Device tree sources

https://github.com/Broly1/android_device_oneplus_kebab
https://github.com/PixelExperience-Devices/device_oneplus_sm8250-common
https://github.com/Broly1/vendor_oneplus_kebab
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_oneplus_sm8250-common
https://github.com/PixelExperience/hardware_oplus
https://github.com/PixelExperience-Devices/kernel_oneplus_sm8250

## Number of ROM's you maintain officially

none

## Any Exceptions/special concern?

No

### Telegram username

@Broly_1

### GitHub username

Broly1

**Comment by Hlcpereira** [comment]
Hello.

Thank for applying. The application is approved, please proceed opening PRs for both official_devices and wiki.

**Comment by Hlcpereira** [comment]
Closing as per #2916
