### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hiper25** [PixelExperience/official_devices#2952]
## Device you want to apply for

Nothing Phone (1)

## Device tree sources

https://github.com/hiper25-OpenSource/device_nothing_Spacewar
https://github.com/hiper25-OpenSource/vendor_nothing_Spacewar
https://github.com/hiper25-OpenSource/kernel_nothing_sm7325

## Number of ROM's you maintain officially

Only ArrowOS maintain officially (coral and flame)

## Any Exceptions/special concern?

lahania and with yupik has a Bluetooth problem, so it needs repopick (21651 21789 21869).

### Telegram username

[hiper25](https://t.me/hiper25)

### GitHub username

[hiper25](https://github.com/hiper25)

**Comment by jjpprrrr** [comment]
Ignoring neverallows is against PE's Code of Conduct.

https://github.com/hiper25-OpenSource/device_nothing_Spacewar/commit/baf6393b00bccd20974a1bc6e9e97d6bda9e1978

**Comment by hiper25** [comment]
> Ignoring neverallows is against PE's Code of Conduct.
> 
> [hiper25-OpenSource/device_nothing_Spacewar@baf6393](https://github.com/hiper25-OpenSource/device_nothing_Spacewar/commit/baf6393b00bccd20974a1bc6e9e97d6bda9e1978)

I've checked it. It's because the PE code is missing something.
repopick 21652-21654 can be solved
So i remove ignore neverallows

**Comment by Hlcpereira** [comment]
In regrads to the sepolicy, we have planned in changing and/or updating them with the December security patch. The trees must be set to production use, hence the Ignore neverallows flag must be removed either way.

**Comment by hiper25** [comment]
> In regrads to the sepolicy, we have planned in changing and/or updating them with the December security patch. The trees must be set to production use, hence the Ignore neverallows flag must be removed either way.

okay

**Comment by jjpprrrr** [comment]
Other than the sepolicy stuff, the tree looks good to me. I still don't understand why those debugfs sepolicy changes are needed, as venus (lahaina) seems completely fine without them. Anyway, @Hlcpereira feel free to proceed with the application. I will work with the maintainer to sort out sepolicy issues.

**Comment by Hlcpereira** [comment]
As per that feel free to open the PRs for both official_devices and wiki

**Comment by Hlcpereira** [comment]
Closing as per #2964
