### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Ad1tyaS1ngh** [PixelExperience/official_devices#2961]
## Device you want to apply for

Redmi K20 (davinci)

## Device tree sources

https://github.com/Ad1tyaS1ngh/device_xiaomi_davinci
https://github.com/Ad1tyaS1ngh/kernel_xiaomi_sm6150
https://github.com/Ad1tyaS1ngh/vendor_xiaomi_davinci

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

Ad1tyaS1ngh

### GitHub username

Ad1tyaS1ngh

**Comment by Hlcpereira** [comment]
Good morning/afternoon/evening.

Upon a look on the device sources we may ask you to remove the star wars popup sound effect (Although admittedly it would be cool to have lol)

Other than that maybe a clean up, as-in removing the reorder libs script is recommended as we have that already on the tools_extract-utils repo (https://github.com/PixelExperience/tools_extract-utils/commit/4793430e16f8ff462f8e1a42c5f165d7784cea49).

Other than these points, everything seems to be in order.

**Comment by Ad1tyaS1ngh** [comment]
> Good morning/afternoon/evening.
> 
> Upon a look on the device sources we may ask you to remove the star wars popup sound effect (Although admittedly it would be cool to have lol)
> 
> Other than that maybe a clean up, as-in removing the reorder libs script is recommended as we have that already on the tools_extract-utils repo ([PixelExperience/tools_extract-utils@4793430](https://github.com/PixelExperience/tools_extract-utils/commit/4793430e16f8ff462f8e1a42c5f165d7784cea49)).
> 
> Other than these points, everything seems to be in order.

Both the changes have been done.

**Comment by Hlcpereira** [comment]
Feel free to open the PRs for official_devices and wiki

**Comment by Ad1tyaS1ngh** [comment]
Done :)

**Comment by Hlcpereira** [comment]
Closing as per merge #2962
