### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by luke-apk** [PixelExperience/official_devices#2966]
## Device you want to apply for

beyond0lte,beyond1lte,beyond2lte,beyondx,d1,d2s,d2x

## Device tree sources

https://gitlab.com/expressluke-982x-t/pixelexperience/android_device_samsung_beyond0lte
https://gitlab.com/expressluke-982x-t/pixelexperience/android_device_samsung_beyond1lte
https://gitlab.com/expressluke-982x-t/pixelexperience/android_device_samsung_beyond2lte
https://gitlab.com/expressluke-982x-t/pixelexperience/android_device_samsung_beyondx
https://gitlab.com/expressluke-982x-t/pixelexperience/android_device_samsung_d1
https://gitlab.com/expressluke-982x-t/pixelexperience/android_device_samsung_d2s
https://gitlab.com/expressluke-982x-t/pixelexperience/android_device_samsung_d2x
https://github.com/ExpressLuke/android_kernel_samsung_exynos9820
https://github.com/ExpressLuke/proprietary_vendor_samsung
https://gitlab.com/expressluke-982x-t/pixelexperience/android_hardware_samsung

## Number of ROM's you maintain officially

0 - I have previously maintained Pixel Experience in the past for herolte/hero2lte

## Any Exceptions/special concern?

No

### Telegram username

@OGExpressLuke

### GitHub username

expressluke

**Comment by Hlcpereira** [comment]
So far everything seems to be in order. Feel free to open the PR for official_devices and wiki if any.

**Comment by luke-apk** [comment]
Thanks @Hlcpereira I have opened PRs for both repos as necessary.

**Comment by Hlcpereira** [comment]
Closing as per #2971
