### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by inferno0230** [PixelExperience/official_devices#2969]
## Device you want to apply for

OnePlus 9RT (martini)

## Device tree sources

https://github.com/inferno0230/device_oneplus_martini
https://github.com/inferno0230/kernel_oneplus_martini
https://github.com/inferno0230/vendor_oneplus_martini

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

Device requires sepolicy_vndr-legacy-um to build w/o errors which is currently not there in PE

### Telegram username

@inferno0230

### GitHub username

inferno0230

**Comment by Hlcpereira** [comment]
In regards to the vndr legacy sepolicy, as mentioned on #2952: We have planned in changing and/or updating them with the December security patch (now the January security patch).

Other than that everythins seems to be in order. The only suggestion would maybe disable the stackprotector in the kernel, although not an obligation to the device get accepted in the end of the day.

Feel free to open the PRs for official_devices and wiki if any.

**Comment by Hlcpereira** [comment]
Closing as per #2974
