### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by qwertyuiii-code** [PixelExperience/official_devices#2976]
## Device you want to apply for

Redmi 9T / Poco M3

## Device tree sources

https://github.com/qwertyuiii-code/device_xiaomi_chime-2/tree/thirtten_aosp
https://github.com/ShelbyHell/sunrise_kernel_juice/tree/topaz
https://github.com/qwertyuiii-code/vendor_xiaomi_chime-1

## Number of ROM's you maintain officially

1 (cherish os)

## Any Exceptions/special concern?

No

### Telegram username

chikoni_uwu

### GitHub username

qwertyuiii-code

**Comment by Hlcpereira** [comment]
Good morning/afternoon/evening

Thanks for applying, yet the device you applied is currently under maintainship by another person.

Best regards
