### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ManshuTyagi** [PixelExperience/official_devices#2979]
## Device you want to apply for

Realme 6/6i(Indian)/6s/7/Narzo/Narzo 20 Pro/Narzo 30 4G ( RM6785 )

## Device tree sources

https://github.com/ManshuTyagi/android_device_realme_RM6785.git
https://github.com/ManshuTyagi/android_kernel_realme_mt6785.git
https://github.com/ManshuTyagi/proprietary_vendor_realme.git

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

ManshuTyagi

### GitHub username

ManshuTyagi

**Comment by ZIDAN44** [comment]
Hello There!

Everything seems to be in order
Feel free to open the PRs for official_devices and wiki and let me know.

**Comment by ManshuTyagi** [comment]
Done
