### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Ipertatos** [PixelExperience/official_devices#2982]
## Device you want to apply for

Oneplus Nord (Avicii)

## Device tree sources

https://github.com/Ipertatos/device_oneplus_sm7250-common/tree/thirteen
https://github.com/Ipertatos/kernel_oneplus_sm7250

## Number of ROM's you maintain officially

Pixel Experience (for avicii)

## Any Exceptions/special concern?

No

### Telegram username

Ipertatos

### GitHub username

Ipertatos

**Comment by Hlcpereira** [comment]
Good morning/afternoon/evening.

Thanks for applying however the Oneplus Nord still is currently with a maintainer.

Best regards.
