### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Yohan-Black** [PixelExperience/official_devices#2998]
## Device you want to apply for

Alioth

## Device tree sources

https://github.com/Yohan-Black/android_device_xiaomi_alioth.git
https://github.com/Yohan-Black/android_device_xiaomi_sm8250-common.git
https://github.com/Yohan-Black/kernel_xiaomi_sm8250.git
https://github.com/Yohan-Black/android_vendor_xiaomi_alioth.git
https://github.com/Yohan-Black/android_vendor_xiaomi_sm8250-common.git
https://github.com/Yohan-Black/hardware_xiaomi.git

## Number of ROM's you maintain officially

1.

## Any Exceptions/special concern?

No

### Telegram username

@Yohan_Black

### GitHub username

Yohan-Black

**Comment by Hlcpereira** [comment]
Good morning/afternoon/evening.

Thanks for applying however before start reviewing the code it comes to attention that you are using a common-tree, of which is different of the current one being used, also a kernel and common vendor repositiory, besides the hardware_xiaomi repository, that if you are to be accepted, would also be ones in current use for other devices.

Please either use the current common device sources (common-tree, kernel and common-vendor) in PE-Devices and/or PE Gitlab and hardware_xiaomi on the PE main org with the necessary adaptations for the device you want to maintain (if any), or fully decommonize the device. 

As per our Code of Conduct, the devices that use the same repositories must use the same branch also.

Both ways were done in the past, and are completely accepted by us.

Once the decision was made please reapply.

Thank you.
