### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Yohan-Black** [PixelExperience/official_devices#3001]
## Device you want to apply for

Xiaomi Redmi K40/Poco F3/Mi 11X (alioth)

## Device tree sources

(Device Tree, PE repository fork)
https://github.com/Yohan-Black/android_device_xiaomi_alioth.git
(Device common, PE repository)
https://github.com/PixelExperience-Devices/device_xiaomi_sm8250-common.git
(Kernel PE repository)
https://github.com/PixelExperience-Devices/kernel_xiaomi_sm8250.git
(Vendor Alioth, PE repository GitLab)
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_alioth.git
(Vendor Common, PE repository GitLab)
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sm8250-common.git

## Number of ROM's you maintain officially

1. (PalyrimOS)

## Any Exceptions/special concern?

No

### Telegram username

@Yohan_Black

### GitHub username

Yohan-Black

**Comment by Varad-13** [comment]
I support this man +1

**Comment by ngguanrui74** [comment]
Hope you can be the new maintainer, I'm waiting for you
