### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Xpsoted** [PixelExperience/official_devices#3006]
## Device you want to apply for

LG V50 ThinQ

## Device tree sources

https://github.com/LG-V50ThinQ/device_lge_flashlmdd
https://github.com/LG-V50ThinQ/device_lge_flash-common
https://github.com/LG-V50ThinQ/device_lge_sm8150-common
https://github.com/LG-V50ThinQ/device_lge_common
https://github.com/LG-V50ThinQ/kernel_lge_sm8150
https://github.com/LG-V50ThinQ/vendor_lge

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

I have already build unoffical PixelExperience 2 months fot this device,all the feature works good

### Telegram username

skdushow

### GitHub username

Xpsoted

**Comment by jordan8277007** [comment]
Anyone using latest built of pixel experience rom (based on android 12) in Indian varient of OnePlus Nord 2?

**Comment by Hlcpereira** [comment]
Good morning/afternoon/evening

Thanks for applying however I unfortunately have to say that your application was rejected.

Why?

After a briefly evaluation, we see a lack of experience for a project of the size of PE. That doens't mean that you are rejected forever. Feel free to reapply in the future once you've got more experience.

Best regards
