### ISSUE TITLE
Application for moto edge 30 (dubai)

### ISSUE THREAD

**Issue by mukul2259** [PixelExperience/official_devices#3007]
## Device you want to apply for

moto edge 30 (dubai)

## Device tree sources

https://github.com/mukul2259/device_motorola_dubai
https://github.com/mukul2259/device_motorola_sm7325-common
https://github.com/mukul2259/kernel_motorola_sm7325
https://gitlab.com/mukul2259/vendor_motorola_dubai
https://gitlab.com/mukul2259/vendor_motorola_sm7325-common

## Number of ROM's you maintain officially

None

## Any Exceptions/special concern?

No

### Telegram username

@mukul2259

### GitHub username

@mukul2259

**Comment by Hasaber8** [comment]
- https://github.com/mukul2259/device_motorola_dubai/commit/c2b4a7ed751677f3242a89236fc09a47b19cb4c4 - Not needed
- https://github.com/mukul2259/device_motorola_sm7325-common/commit/e04fd69fa8fffffb3b45572fe2abf302b8e04959 - Don't you use MotoCam4?

**Comment by mukul2259** [comment]
- It is required for reserving space for GMS builds and was not meant to build gapps, as can be seen here: https://github.com/mukul2259/device_motorola_dubai/blob/3c1f8e7f761603e347476de73b31ec4c07d1004f/BoardConfig.mk#L44
I can swap to https://github.com/PixelExperience-Devices/device_oneplus_sm8250-common/commit/56ecf6322c34f49bac68b37f5887acd4fa2ac3eb for a better applicable fix since we ship with gapps by default.

- The application package name is still com.motorola.camera3, PFA the screenshot for reference
![image](https://user-images.githubusercontent.com/41151952/214652186-2f8ab062-54c3-4701-876b-ba44b892a81e.png)

**Comment by Hlcpereira** [comment]
In the case of the guard you can remove it, as there's no GApp-less version of PE. https://github.com/PixelExperience-Devices/device_xiaomi_sm8250-common/commit/7bf98f71c635cfc32577081c874bf4f4aaa6557f#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42L156. Either way It's a minor thing rather than anything else.

**Comment by mukul2259** [comment]
> In the case of the guard you can remove it, as there's no GApp-less version of PE. [PixelExperience-Devices/device_xiaomi_sm8250-common@7bf98f7#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42L156](https://github.com/PixelExperience-Devices/device_xiaomi_sm8250-common/commit/7bf98f71c635cfc32577081c874bf4f4aaa6557f#diff-7961072fe465c96523957cd817901821151f626d40d2f3df8f87f3e5d4fb0b42L156). Either way It's a minor thing rather than anything else.

Dropped here:
https://github.com/mukul2259/device_motorola_dubai
https://github.com/mukul2259/device_motorola_sm7325-common/commit/c121419defa5d57cdc72bb0849d51e7bf6508976

_Tested: Verified and boots_

**Comment by Hlcpereira** [comment]
All looks fine for me. I would have the point of noticing that the common-tree would be shared with the berlin maintainer, but as he decided to decommonize the point of matter is none. @Hasaber8 anything else to point out?

**Comment by Hasaber8** [comment]
Nope, LGTM

**Comment by Hlcpereira** [comment]
With that set in mind, please open the PR for both official_devices and wiki whenever possible.

**Comment by Hlcpereira** [comment]
@mukul2259 awaiting for wiki PR to proceed.

**Comment by mukul2259** [comment]
> @mukul2259 awaiting for wiki PR to proceed.

Here you go, https://github.com/PixelExperience/wiki/pull/311

**Comment by Hlcpereira** [comment]
Closing as per #3018
