### ISSUE TITLE
Application for OnePlus 6T (fajita)

### ISSUE THREAD

**Issue by snnbyyds** [PixelExperience/official_devices#3015]
## Device you want to apply for
```
OnePlus 6T (fajita)
```

## Device tree sources

https://github.com/snnbyyds/device_oneplus_fajita
https://github.com/snnbyyds/device_oneplus_sdm845-common
https://github.com/snnbyyds/kernel_oneplus_sdm845
https://github.com/snnbyyds/vendor_oneplus_fajita
https://github.com/snnbyyds/vendor_oneplus_sdm845-common

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
Yes.

First, modifications to hardware_qcom-caf_sdm845_display & hardware_qcom-caf_sdm845_audio are needed. The display HAL needs to be updated to make fingerprint reader work. We need to merge or cherry-pick changes from the one in Lineage OS. (This is my own fork. https://github.com/snnbyyds/hardware_qcom-caf_sdm845_display/commits/thirteen). The audio HAL would need 2 patches to make it build, which has been uploaded to gerrit. (See https://gerrit.pixelexperience.org/c/hardware_qcom-caf_sdm845_audio/+/22795 and https://gerrit.pixelexperience.org/c/hardware_qcom-caf_sdm845_audio/+/22796 ).

Second, I would prefer to use clang-r475365b tracked from crdroid gitlab, but if it is not permitted, I can use the default clang-r450784d or jjpprrrr's prelude clang.

Third, a thirteen-plus branch should be created in hardware_oneplus with livedisplay HAL added back.

### Telegram username
```
snnbyyds
```

### GitHub username
```
snnbyyds
```

**Comment by jjpprrrr** [comment]
HI! Thanks for the application.

The tree looks good to me. @Hlcpereira Feel free to proceed if you see fit.

As for the changes needed in sdm845 HALs, I will take a look and push them during the Feb release window.

We currently do not have a restriction on the kernel compiler, but I would suggest at least forking it to a repo you have control over to prevent accidental breakage if crdroid changes anything in their repo.

You can sort out the hardware_oneplus issues with other oneplus device maintainers once you join. Perhaps the livedisplay HAL can be added to thirteen branch directly, as long as you don't build it on thirteen? I'm fine either way.

**Comment by Hlcpereira** [comment]
@snnbyyds with that in mind and nothing else seems out of place for me feel free to open a PR for both official_devices and wiki

**Comment by snnbyyds** [comment]
> @snnbyyds with that in mind and nothing else seems out of place for me feel free to open a PR for both official_devices and wiki

OK, thank you very much!
I will wait for problems with sdm845 HALs and hardware_oneplus to be fixed. ;D

**Comment by Hlcpereira** [comment]
In regard to the 845 HALs you can push to gerrit whenever wishable. And in regards to hardware_oneplus it's was as @jjpprrrr mentioned, yet to make an effect you must be a maintainer of a device that needs the repo within the project as you'll have to negotiate with the other maintainers that use that repository.

**Comment by Hasaber8** [comment]
Whats wrong with hardware_oneplus?

**Comment by snnbyyds** [comment]
> Whats wrong with hardware_oneplus?

Livedisplay HAL needed to be added back for plus builds. Now I have uploaded it to gerrit

> In regard to the 845 HALs you can push to gerrit whenever wishable. And in regards to hardware_oneplus it's was as @jjpprrrr mentioned, yet to make an effect you must be a maintainer of a device that needs the repo within the project as you'll have to negotiate with the other maintainers that use that repository.

I have already uploaded the changes for hardware_qcom-caf_sdm845_audio.
For hardware_qcom-caf_sdm845_display, it seems that because I am merging a new caf tag, I need 'forge committer' permission. Thus I can't upload them. https://github.com/snnbyyds/hardware_qcom-caf_sdm845_display
```
sn@DESKTOP-KN1NCPK:~/hardware_qcom-caf_sdm845_display$ git push ssh://snnbyyds@gerrit.pixelexperience.org:29418/hardware_qcom-caf_sdm845_display HEAD:refs/for/thirteen
Enumerating objects: 70, done.
Counting objects: 100% (66/66), done.
Delta compression using up to 6 threads
Compressing objects: 100% (43/43), done.
Writing objects: 100% (46/46), 31.83 KiB | 7.96 MiB/s, done.
Total 46 (delta 21), reused 1 (delta 1), pack-reused 0
remote: Resolving deltas: 100% (21/21)
remote: Processing changes: refs: 1, done
remote: ERROR: commit 709ba15: email address code-review@localhost is not registered in your account, and you lack 'forge committer' permission.
remote: The following addresses are currently registered:
remote:    snnbyyds@gmail.com
remote: To register an email address, visit:
remote: https://gerrit.pixelexperience.org/settings#EmailAddresses
remote:
remote:
To ssh://gerrit.pixelexperience.org:29418/hardware_qcom-caf_sdm845_display
 ! [remote rejected]   HEAD -> refs/for/thirteen (commit 709ba15: invalid committer)
error: failed to push some refs to 'ssh://gerrit.pixelexperience.org:29418/hardware_qcom-caf_sdm845_display'
sn@DESKTOP-KN1NCPK:~/hardware_qcom-caf_sdm845_display$
```

**Comment by jjpprrrr** [comment]
Merging S tag means moving some vendor libs to the display HAL, like `libgralloc.qti`. Doesn't that cause name conflict with the one in vendor/qcom/opensource/display/gralloc? Or am I missing something?

**Comment by jjpprrrr** [comment]
Oh, the next commit reverted those libs. Then why even include the merge commit? As far as I can tell, we already have the rest of the commits from S tag? I will pick the rest of the commits.

**Comment by snnbyyds** [comment]
> Oh, the next commit reverted those libs. Then why even include the merge commit? As far as I can tell, we already have the rest of the commits from S tag? I will pick the rest of the commits.

I just want to catch up with the one in LineageOS. And it seems that `LA.UM.10.3.r1-00600-sdm845.0` actually has brought 2 or 3 more commits compared with `LA.UM.9.8.r1-04800-SDM710.0` . ;D
https://github.com/PixelExperience/hardware_qcom-caf_sdm845_display/compare/thirteen...snnbyyds:hardware_qcom-caf_sdm845_display:thirteen

**Comment by snnbyyds** [comment]
https://github.com/PixelExperience/official_devices/pull/3026

**Comment by Hlcpereira** [comment]
Closing as per PR #3026
