### ISSUE TITLE
New maintainer for Mi Pad 4

### ISSUE THREAD

**Issue by Alcatraz323** [PixelExperience/official_devices#3021]
## Device you want to apply for

Mi Pad 4(clover)

## Device tree sources

https://github.com/AlcatrazDev-Android-Devices/device_xiaomi_clover
https://github.com/AlcatrazDev-Android-Devices/kernel_xiaomi_clover
https://github.com/AlcatrazDev-Android-Devices/vendor_xiaomi_clover

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

Alcatraz323

### GitHub username

Alcatraz323

**Comment by Hlcpereira** [comment]
Closing as per #3029
