### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Amritorock** [PixelExperience/official_devices#3036]
## Device you want to apply for

Realme 5 Series (5/5i/5s)

## Device tree sources

https://github.com/Amritorock/device_realme_r5x
https://github.com/Amritorock/kernel_realme_r5x
https://github.com/Amritorock/vendor_realme_r5x

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

@Amritoooo

### GitHub username

@Amritorock

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying.

Unfortunately we have to reject your application at the moment.

"Why?"
The main reason has to do with prohibited implementations on the Parts packages (RealmeParts), which includes kcal and vibration strength control which are not allowed as per our code of conduct.

It also includes into the list the fact of the Dolby Atmos which as far as we could check it isn't a stock feature of the device.

There could be more points to be unveil aswell, such as generic sepolicy labeling.

The rejection doesn't mean however that if you apply at a near future you'll be rejected aswell. Feel free to apply whenever you've gathered more experience.

Best regards.
