### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kinhelm** [PixelExperience/official_devices#3047]
## Device you want to apply for

Redmi note 8 Pro (Begonia)

## Device tree sources

https://github.com/kinhelm/device_xiaomi_begonia
https://github.com/kinhelm/kernel_xiaomi_begonia
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_begonia

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?
Because ZIDAN44 change his phone, I build UNOFFICIAL PE-plus and up this [ xda thread ](https://forum.xda-developers.com/t/rom-13-begonia-pixel-experience-unofficial-plus-edition.4548085/)

### Telegram username

@loic_ent

### GitHub username

@kinhelm

**Comment by Hlcpereira** [comment]
Hello. Thanks for applying.

Unfortunately we have to reject your application at the moment.

"Why?"
The main reason has to do with a noticible lack of experience for the amount of responsability that comes with been part of the PixelExperience team.

That doesn't mean however that if you apply at a near future you'll be rejected aswell. Feel free to apply whenever you've gathered more experience.

Best regards.
