### ISSUE TITLE
New maintainer - alioth

### ISSUE THREAD

**Issue by lukasz1992** [PixelExperience/official_devices#3056]
## Device you want to apply for

alioth

## Device tree sources

https://github.com/lukasz1992/device_xiaomi_alioth
https://gitlab.com/lukasz1992-pe

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

- there is already shared kernel (apollo and munch) and device-common (apollo and munch)
- Device was previously maintained until 01.2023, known bugs were resolved and lzgmc finished maintenance
- I own the device, already have done three builds and use it on my main phone

### Telegram username

lukasz_1992

### GitHub username

lukasz1992

**Comment by lukasz1992** [comment]
Cancel

**Comment by contemplator1998** [comment]
Why was it closed? Would be awesome to have Łukasz as a maintainer.

**Comment by lukasz1992** [comment]
All problems solved - can support it now:
- already backported drivers from the most recent image
- would be good to provide security fixes for users

**Comment by ZIDAN44** [comment]
Hello there ! Thanks for applying.

Unfortunately we have to reject your application at the moment.

"Why?"
The main reason has to do with a noticible lack of experience for the amount of responsability that comes with been part of the PixelExperience team.

That doesn't mean however that if you apply at a near future you'll be rejected aswell. Feel free to apply whenever you've gathered more experience.

Best regards.
