### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Royna2544** [PixelExperience/official_devices#3059]
## Device you want to apply for

Galaxy A51 4G (a51)

## Device tree sources

Kernel: https://github.com/A51-Development/kernel_samsung_universal9611
Device Common: https://github.com/A51-Development/device_samsung_universal9611-common
Device: https://github.com/A51-Development/device_samsung_a51/tree/thirteen
Vendor: https://github.com/A51-Development/vendor_samsung_universal9611-common 
Vendor common: https://github.com/A51-Development/vendor_samsung_a51

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

@roynatech

### GitHub username

@roynatech2544

**Comment by Hlcpereira** [comment]
Hello. After a verification of the sources, nothing seems to be wrong, despite minor details are bound to be changed anyway.

With that in mind and no one else to point anything wrong, feel free to open the PRs for both wiki and official_devices
