### ISSUE TITLE
New maintainer - Xiaomi POCO F1 beryllium

### ISSUE THREAD

**Issue by aravindvnair99** [PixelExperience/official_devices#3062]
## Device you want to apply for

Xiaomi POCO F1

## Device tree sources

https://github.com/PixelOS-Devices/device_xiaomi_beryllium
https://github.com/PixelOS-Devices/vendor_xiaomi_beryllium
https://github.com/PixelOS-Devices/device_xiaomi_sdm845-common
https://github.com/sajidshahriar72543/pe-fork

## Number of ROM's you maintain officially

1. PixelOS AOSP

## Any Exceptions/special concern?

Nil

### Telegram username

@paperboy22

### GitHub username

@sajidshahriar72543

**Comment by aravindvnair99** [comment]
Created this ticket on behalf of @sajidshahriar72543 as previous ticket validation failed - https://github.com/PixelExperience/official_devices/issues/3061

**Comment by sajidshahriar72543** [comment]
Thanks @aravindvnair99 for helping

**Comment by aravindvnair99** [comment]
PE team - you have a bug in @pixelexperiencebot where it tags the wrong person after parsing. I would suggest replacing Telegram username with Telegram link instead of putting it as username as it tags via GitHub instead. This is a problem for those who have different usernames on GitHub and Telegram as it tags the wrong person.

**Comment by aravindvnair99** [comment]
@jjpprrrr any updates on this?

**Comment by jjpprrrr** [comment]
Thanks for the application. The sdm845-common seems to be based on the lineage tree, not the current one on PE. The sdm845-common on PE is already used by polaris and dipper, so if you decide to not use that sdm845-common, you need to merge your own common tree into device/xiaomi/beryllium.

**Comment by sajidshahriar72543** [comment]
> Thanks for the application. The sdm845-common seems to be based on the lineage tree, not the current one on PE. The sdm845-common on PE is already used by polaris and dipper, so if you decide to not use that sdm845-common, you need to merge your own common tree into device/xiaomi/beryllium.

Thanks for your response.
Here is the decommonized tree link: 
https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commits/thirteen

**Comment by aravindvnair99** [comment]
@jjpprrrr any updates on this?

**Comment by zjunior06** [comment]
> @jjpprrrr any updates on this?

Not worry, lol.

**Comment by aravindvnair99** [comment]
@jjpprrrr any updates on this?

**Comment by jjpprrrr** [comment]
> > Thanks for the application. The sdm845-common seems to be based on the lineage tree, not the current one on PE. The sdm845-common on PE is already used by polaris and dipper, so if you decide to not use that sdm845-common, you need to merge your own common tree into device/xiaomi/beryllium.
> 
> Thanks for your response. Here is the decommonized tree link: https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commits/thirteen

Hi. What happened to the decommonized tree?

**Comment by sajidshahriar72543** [comment]
> > > Thanks for the application. The sdm845-common seems to be based on the lineage tree, not the current one on PE. The sdm845-common on PE is already used by polaris and dipper, so if you decide to not use that sdm845-common, you need to merge your own common tree into device/xiaomi/beryllium.
> > 
> > 
> > Thanks for your response. Here is the decommonized tree link: https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commits/thirteen
> 
> Hi. What happened to the decommonized tree?

Sorry I made it private yesterday. It should be available now.

**Comment by jjpprrrr** [comment]
Is there a specific reason to disable sound effects by default? If not, please do not change the default ROM behavior of PE unless it is absolutely necessary for your device.

https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commit/d783293e2a09bdacc1a0b90cf8c7b1c7e5f985f6

I can see other commits changing the system default behavior as well.

https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commit/75d1e020bb43aaeb7889682713d8fd8213c40bba

Can you point out where this prop is used in the current PE source code? I cannot find anything after grepping the whole source directory. It is not a good practice if you blindly pick a commit without actually verifying whether it makes a difference or not.

https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commit/0dba279f2945e31d1c97c0e17fb0e9505549cf6b

Whether Night Light is available or not is determined by the config below.

`<bool name="config_nightDisplayAvailable">@bool/config_setColorTransformAccelerated</bool>`

I'm not sure why you find it necessary to explicitly enable it again. Is this another blind cherry-pick?

https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commit/24f3fe8d0031b89ea77d1001218985ef4e7bfef6

Why is this prop added twice?

https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commit/419ada9b293e92690634a6c28083579ac05c40af
https://github.com/sajidshahriar72543/device_xiaomi_beryllium-decom/commit/83f7b041704830eff79fdcb0587ea8401963f140

Unfortunately, I do not feel comfortable enough at the moment to accept you as an official PE maintainer for beryllium based on the issues I have found so far. However, this is by no means a final verdict. I can see potential in your work, and I hope you pay more attention to the commits you pick and review the changes carefully. Feel free to re-apply in a few months if you wish. Thank you again for your application.
