### ISSUE TITLE
New maintainer - Xiaomi Mi 11 Lite 5G

### ISSUE THREAD

**Issue by PawiX25** [PixelExperience/official_devices#3071]
## Device you want to apply for

Xiaomi Mi 11 Lite 5G

## Device tree sources

Everything I use is available at: https://github.com/orgs/RenoirPixelExperienceTrees/repositories

## Number of ROM's you maintain officially

0 - I have been building unofficially and have not applied for maintaining any ROMs officially.

## Any Exceptions/special concern?

No

### Telegram username

@pawix25 

### GitHub username

PawiX25

**Comment by jjpprrrr** [comment]
Hi. Thanks for the application.

The CoC does not allow granting write access to a generic sysfs node. Generally, you should try to label a node first and then grant write permission to that label only.
https://github.com/RenoirPixelExperienceTrees/device_xiaomi_sm8350-common/blob/thirteen/sepolicy/vendor/battery.te#L28

I don't have renoir, but on sm8350 devices that line was not necessary.
https://github.com/PixelExperience-Devices/device_xiaomi_sm8350-common/commit/5431c7a996d0a747a4d11703a9d9a268897202d8

The issue above is just an example. Please go through your tree again and make sure it does not contain other CoC violations. Thank you.

**Comment by jjpprrrr** [comment]
In addition to that, please push your changes to rename sm8350-common to sm7350-common, as we discussed on telegram.

**Comment by PawiX25** [comment]
I did that yesterday :)
