### ISSUE TITLE
Resurrection of Mi11 Pro (mars)

### ISSUE THREAD

**Issue by FlowerSea0208** [PixelExperience/official_devices#3073]
## Device you want to apply for
Mi 11 Pro (mars)

## Device tree sources

https://github.com/FlowerSea0208/device_xiaomi_mars/tree/thirteen-new
https://github.com/FlowerSea0208/device_xiaomi_sm8350-common/tree/thirteen-new
https://github.com/FlowerSea0208/kernel_xiaomi_mars
https://gitlab.com/crdroidandroid/proprietary_vendor_xiaomi_mars/-/tree/13.0

## Number of ROM's you maintain officially
2

## Any Exceptions/special concern?
No
I plan to bring mars back and maintain it until the original maintainer picks up the device again

### Telegram username
```
FlowerSea0208
```

### GitHub username
```
FlowerSea0208
```

**Comment by jjpprrrr** [comment]
Hi. The trees look good to me. Personally I do not agree with the commits you added to your sm8350-common, but we can work that out after you join PE. Feel free to submit PR to official_devices repo and wiki repo.

I'm closing this issue.
