### ISSUE TITLE
 New maintainer - Poco F3 (alioth)

### ISSUE THREAD

**Issue by GrettoRosella** [PixelExperience/official_devices#3079]
### Device you want to apply for

Poco F3 (Alioth)

### Device Tree Sources

https://github.com/GrettoRosella/android_device_xiaomi_alioth

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

Nothing

### Telegram username

GrettoRosella

### GitHub username

GrettoRosella

**Comment by ZIDAN44** [comment]
Hello there! Thanks for applying.

Pls show other sources too (Kernel, vendor, ETC)

**Comment by GrettoRosella** [comment]
> Hello there! Thanks for applying.
> 
> Pls show other sources too (Kernel, vendor, ETC)

hello

kernel : https://github.com/ArrowOS-MiPa-Edition/android_kernel_xiaomi_alioth
vendor : https://github.com/GrettoRosella/proprietary_vendor_xiaomi_alioth

**Comment by ZIDAN44** [comment]
Sorry for keep you waiting.

Overall trees looks good  to me. Feel free to open the PRs for both wiki and official_devices
