### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by Unnho** [PixelExperience/official_devices#3080]
### Device you want to apply for

Motorola One Action (troika)

### Device Tree Sources

https://github.com/Unnho/android_kernel_motorola_exynos9610.git
https://gitlab.com/Unnho/proprietary_vendor_motorola_troika.git
https://gitlab.com/Unnho/proprietary_vendor_motorola_exynos9610-common.git
https://github.com/Unnho/android_hardware_motorola.git
https://github.com/Unnho/android_hardware_samsung.git
https://github.com/Unnho/android_hardware_samsung_slsi_fm.git
https://github.com/Unnho/android_hardware_samsung_slsi_libbt.git
https://github.com/Unnho/android_hardware_samsung_slsi_scsc_wifibt_wifi_hal.git
https://github.com/Unnho/android_device_samsung_slsi_sepolicy.git
https://github.com/Unnho/android_device_motorola_troika.git
https://github.com/Unnho/android_device_motorola_exynos9610-common.git
https://github.com/Unnho/android_hardware_samsung_slsi_scsc_wifibt_wpa_supplicant_lib.git

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

I'm new in development I started building from 2021
I was never a official Maintainer please make me one

### Telegram username

t.me/nevermindablegod

### GitHub username

Unnho

**Comment by jro1979oliver** [comment]
We ask applicants to create their own fork with their own modifications on their personal github. From what I see you are using the lineage trees. Make your fork and edit this issue please

**Comment by Unnho** [comment]
Ok Thanks

**Comment by Unnho** [comment]
Hello I edited the issue please process it

**Comment by ZIDAN44** [comment]
> Hello I edited the issue please process it

But where is your own modifications/commits for building PE ?

**Comment by Unnho** [comment]
Hello Thanks for your assistance but I will Apply for it later so I'm closing the issue
