### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by RitikX003** [PixelExperience/official_devices#3085]
### Device you want to apply for

OnePlus NordCE 5G (Ebba)

### Device Tree Sources

https://gitlab.com/opnordce/android_device_oneplus_ebba

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

There's no PE rom for this device. 

### Telegram username

ritikjain_rj

### GitHub username

RitikX003

**Comment by jro1979oliver** [comment]
This device tree it's not modified for PE compiling, neither updated since 2022. We need a device tree and a vendor tree, as well as the kernel. I am closing this issue until the requirements are satisfied
