### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AnilShebin** [PixelExperience/official_devices#3087]
### Device you want to apply for

Realme 5 Pro (RMX1971)

### Device Tree Sources

https://github.com/AnilShebin/device_realme_RMX1971
https://github.com/AnilShebin/device_realme_sdm710-common
https://github.com/AnilShebin/kernel_realme_RMX1971
https://github.com/AnilShebin/vendor_realme_sdm710-common
https://gitlab.com/AnilShebin/vendor_realme_rmx1971

### Number of ROM's you maintain officially

2

### Any Exceptions/special concern?

Nil

### Telegram username

@AnilShebin

### GitHub username

https://github.com/AnilShebin

**Comment by jro1979oliver** [comment]
There are some storage issue? We can't allow this on PixelExperience:
https://github.com/AnilShebin/device_realme_RMX1971/commit/e0c5a3bfc4ebe00a488ac7e72de1c0cc3424fbe6

**Comment by AnilShebin** [comment]
By removing the commit, the rom will compile fine. We just added to reduce bloatware on the user's request

**Comment by jro1979oliver** [comment]
Welcome to PixelExperience
