### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JustANormalTinker** [PixelExperience/official_devices#3089]
### Device you want to apply for

Redmi Note 5 Pro (Whyred)

### Device Tree Sources

https://github.com/PixelExperience-Devices/device_xiaomi_whyred
https://github.com/PixelExperience-Devices/device_xiaomi_sdm660-common

### Number of ROM's you maintain officially

None

### Any Exceptions/special concern?

My PE normal build has no encryption but the PE+ one does, thats it, and it should be easy to add it

### Telegram username

NopeNopeGuy

### GitHub username

JustANormalTinker

**Comment by jro1979oliver** [comment]
We need your personal forks to evaluate your personal skills for mainteinance. The trees you linked are unmodified from our sources. Closing for now, when done with forks, please reopen
