### ISSUE TITLE
Ganesh Jadhav 

### ISSUE THREAD

**Issue by Jadhavggg** [PixelExperience/official_devices#3091]
### Device you want to apply for

OnePlus Nord Ce 2 5G

### Device Tree Sources

No one Make Device tree

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

No just Want Roms for this device 

### Telegram username

@not_ganesh

### GitHub username

chimeganeshjadhav

**Comment by jro1979oliver** [comment]
This is not a request channel. Closing
