### ISSUE TITLE
New maintainer - OnePlus 6 (enchilada)

### ISSUE THREAD

**Issue by snnbyyds** [PixelExperience/official_devices#3092]
### Device you want to apply for

OnePlus 6 (enchilada)

### Device Tree Sources

https://github.com/snnbyyds/device_oneplus_enchilada
https://github.com/PixelExperience-Devices/device_oneplus_sdm845-common
https://github.com/PixelExperience-Devices/kernel_oneplus_sdm845
https://github.com/snnbyyds/proprietary_vendor_oneplus_enchilada
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_oneplus_sdm845-common

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

No.

### Telegram username

snnbyyds

### GitHub username

snnbyyds

**Comment by jjpprrrr** [comment]
I know you're already maintaining fajita. Do you have enchilada? Or how do you plant o test the build?

**Comment by snnbyyds** [comment]
> I know you're already maintaining fajita. Do you have enchilada? Or how do you plant o test the build?

As mentioned in maintainers_requirements.md, "Devices that have minimal hardware difference from yours are allowed to be maintained, as long as you maintain your own device too." Enchilada and fajita do not have much difference. Though I don't own the device, I can still find someone who own the device to test builds before releasing an update to ensure device functionality.
