### ISSUE TITLE
Maintenship for xaga

### ISSUE THREAD

**Issue by saikoushiknalubola** [PixelExperience/official_devices#3096]
### Device you want to apply for

Redmi k50i ( xagain)

### Device Tree Sources

https://github.com/wbs306/device_xiaomi_xaga
https://github.com/YadavMohit19/device_xiaomi_xaga

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

Pls provide pe for xaga and the beauty of mtk 8100

### Telegram username

t.me/Dam0nsalva

### GitHub username

dam0nsalva

**Comment by ZIDAN44** [comment]
Hello. Thanks for applying.

Unfortunately we have to reject your application at the moment.

"Why?"
The main reason has to do with a noticible lack of experience for the amount of responsability that comes with been part of the PixelExperience team.

That doesn't mean however that if you apply at a near future you'll be rejected aswell. Feel free to apply whenever you've gathered more experience.

Best regards.
