### ISSUE TITLE
New maintainer - OnePlus Nord N200 5G

### ISSUE THREAD

**Issue by lzgmc** [PixelExperience/official_devices#3104]
### Device you want to apply for

OnePlus Nord N200 5G

### Device Tree Sources

https://github.com/lzgmc/device_oneplus_dre
https://github.com/lzgmc/kernel_oneplus_sm4350-1
https://github.com/TheMuppets/proprietary_vendor_oneplus_dre

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

This device requires certain modifications to PixelExperience's source code:
The [AOSP kernel build tools](https://android.googlesource.com/kernel/prebuilts/build-tools) need to be tracked in the manifest to build the kernel. This repo could be tracked from AOSP ([LineageOS' implementation](https://github.com/LineageOS/android/blob/4609897eb5ba31bcef30376630611e1a4a375d68/snippets/lineage.xml#L65)) or forked to the PixelExperience source tree.
The hardware/oplus repository needs patches. [See my fork](https://github.com/PixelExperience/hardware_oplus/compare/thirteen...lzgmc:hardware_oplus:thirteen).

### Telegram username

lzgmc

### GitHub username

lzgmc

**Comment by Hasaber8** [comment]
Please push the necessary changes to Gerrit
