### ISSUE TITLE
New maintainer for Xiaomi 11 Lite NE 5G

### ISSUE THREAD

**Issue by dasshubham762** [PixelExperience/official_devices#3107]
### Device you want to apply for

Xiaomi 11 Lite NE 5G (lisa)

### Device Tree Sources

https://github.com/dasshubham762/device_xiaomi_lisa
https://github.com/dasshubham762/kernel_xiaomi_lisa
https://gitlab.com/dasshubham762/vendor_xiaomi_lisa
https://github.com/dasshubham762/vendor_xiaomi_camera-lisa

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

I would like to have Miui Camera inbuilt with this ROM. The app works perfectly fine and all the features work perfectly. It requires two commits in frameworks/base which I'll push to gerrit.

### Telegram username

dasshubham762

### GitHub username

dasshubham762

**Comment by jro1979oliver** [comment]
All right, just do the PR on the wiki and official devices and success
