### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by zlewchan** [PixelExperience/official_devices#3109]
### Device you want to apply for

Xiaomi Mi MIX 2 (chiron)

### Device Tree Sources

https://github.com/x0x-minefield/android_device_xiaomi_chiron
https://github.com/x0x-minefield/android_device_xiaomi_msm8998-common
https://github.com/x0x-minefield/android_vendor_xiaomi_chiron
https://github.com/x0x-minefield/android_vendor_xiaomi_msm8998-common
https://github.com/x0x-minefield/android_kernel_xiaomi_msm8998

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

No.

### Telegram username

x0x00044

### GitHub username

x0x00044

**Comment by jro1979oliver** [comment]
Hi dear, I couldn't find you on telegram to finish this application, can you dm me?
