### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Kyuofox** [PixelExperience/official_devices#3117]
### Device you want to apply for

Redmi K30 Pro / POCO F2 Pro (lmi)

### Device Tree Sources

device tree: https://github.com/Kyuofox-Studio/android_device_xiaomi_lmi
vendor tree: https://github.com/Kyuofox-Studio/android_vendor_xiaomi_lmi
kenrel tree: https://github.com/Kyuofox-Studio/android_kernel_xiaomi_lmi

### Number of ROM's you maintain officially

3

### Any Exceptions/special concern?

The current maintainer of lmi is too similar to buildbot

### Telegram username

Kyuofox

### GitHub username

Kyuofox

**Comment by jro1979oliver** [comment]
Come back when you respect others work. Cheers
