### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chriscfilho** [PixelExperience/official_devices#3123]
### Device you want to apply for

Samsung Galaxy M52 (m52xq)

### Device Tree Sources

https://github.com/eugostodetortas/android_device_samsung_sm7325-common
https://github.com/eugostodetortas/android_device_samsung_m52xq
https://github.com/Simon1511/android_vendor_samsung_sm7325-common
https://github.com/Simon1511/android_vendor_samsung_m52xq
https://github.com/Simon1511/android_kernel_samsung_sm7325

### Number of ROM's you maintain officially

0 (zero)

### Any Exceptions/special concern?

No

### Telegram username

https://t.me/eugostodetortas (@eugostodetortas) 

### GitHub username

eugostodetortas

**Comment by jro1979oliver** [comment]
We need your own repos to check application
