### ISSUE TITLE
New maintainer for Nokia 6.1 - [PL2]

### ISSUE THREAD

**Issue by userariii** [PixelExperience/official_devices#3125]
### Device you want to apply for

Nokia 6.1 [PL2]

### Device Tree Sources

DT: https://github.com/userariii/android_device_nokia_PL2.git
DTC: https://github.com/userariii/android_device_nokia_sdm660-common.git
VT: https://github.com/userariii/proprietary_vendor_nokia_PL2.git
VTC: https://github.com/userariii/proprietary_vendor_nokia_sdm660-common.git
KT: https://github.com/userariii/android_kernel_nokia_sdm660.git

### Number of ROM's you maintain officially

2 ROMs

### Any Exceptions/special concern?

Maintained 2 ROMs for "miatoll" officially SuperiorOS & SpiceOS, and unofficially maintained Pixelexperience for miatoll & PL2 with some customizations.

### Telegram username

https://t.me/CRUECY

### GitHub username

https://github.com/userariii

**Comment by jro1979oliver** [comment]
You should not track hals from outside Pixel org. I can't make sure it will work in our sources, also there are some incompatible lineage stuffs still remaining on the trees

**Comment by userariii** [comment]
Regarding HALs it can be track from Pixel org. i.e: hardware/qcom-caf/msm8998
&
Removed unnecessary Lineage HALs & overlays.
@jro1979oliver Please look into the tree's over again & let me know if anything else I need to fix.

**Comment by jro1979oliver** [comment]
> Regarding HALs it can be track from Pixel org. i.e: hardware/qcom-caf/msm8998 & Removed unnecessary Lineage HALs & overlays. @jro1979oliver Please look into the tree's over again & let me know if anything else I need to fix.

Feel free to reopen the application

**Comment by jro1979oliver** [comment]
[This](https://github.com/userariii/android_device_nokia_sdm660-common/commit/43645169f4a81fca8061bf90ba19fc439c45a29e) does nothing on PE
[This](https://github.com/userariii/android_device_nokia_PL2/commit/60384a728857d922d5b023e2eda07cafffb858df) will lead device without NFC on PE
Also [this](https://github.com/userariii/android_device_nokia_PL2/blob/thirteen/BoardConfig.mk#L49) is a no go on PE, I saw on Lineage. It's one official supported los device? Is there a plausible reason to ignore neverallows?

**Comment by userariii** [comment]
1) Fixed above 2 problems 
& 
2) Regarding NEVERALLOW the commit is from the [official lineage team](https://github.com/LineageOS/android_device_nokia_PL2/commit/471abae7b76c4ef3b49c5129a673a155450f66b1), the builds are officially supported & our device pass the CTS in user build.

**Comment by jro1979oliver** [comment]
Ok, now let's proceed with the PR and the rest. Welcome
