### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jaymistry258** [PixelExperience/official_devices#3127]
### Device you want to apply for

Poco X2 / Redmi K30 (phoenix)

### Device Tree Sources

https://github.com/jaymistry258/device_xiaomi_phoenix.git

https://github.com/jaymistry258/vendor_xiaomi_phoenix.git

https://github.com/jaymistry258/vendor_xiaomi_phoenix.git

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

I want to join Pixel Experience Official Membership.

### Telegram username

jaymistry258

### GitHub username

jaymistry258

**Comment by jro1979oliver** [comment]
There are some issues with the bringup for Pixel as I see. Reopen when it's fixed
