### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Willylakshit** [PixelExperience/official_devices#3131]
### Device you want to apply for

Realme C3 (RMX2020)

### Device Tree Sources

https://github.com/Willylakshit/android_device_realme_RMX2020
https://github.com/SuperiorOS-Devices/kernel_realme_RMX2020
https://github.com/SuperiorOS-Devices/vendor_realme_RMX2020
https://github.com/SuperiorOS-Devices/vendor_realme_RMX2020-ims
https://github.com/ArrowOS/android_device_mediatek_sepolicy_vndr
https://github.com/LineageOS/android_hardware_mediatek

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

Nil

### Telegram username

WillyS69

### GitHub username

Willylakshit

**Comment by jro1979oliver** [comment]
Hi dear. The hardware repos must belong to PixelExperience org, otherwhise, link the patches you need to be pushed to our source in order to be compliant with our CoC

**Comment by Willylakshit** [comment]
Just sync android _hardware_mediatek

**Comment by jro1979oliver** [comment]
> Just sync android _hardware_mediatek

Please, elaborate this...
And btw, I saw this device has more variants
32GB 2GB RAM, 32GB 3GB RAM, 64GB 3GB RAM, 64GB 4GB RAM.
At [Device Requirements](https://github.com/PixelExperience/docs/blob/master/device_requirements.md) we enforce devices with a minimal of 3GB RAM. How do you avoid installing in the variant with less resources?

**Comment by Willylakshit** [comment]
android_hardware_mediatek repo is not synced according to lineage os which i use and please check device properly the 2 gb variant is known as realme C3i which is codenamed RMX2021 and not supported in source .Only RMX2020,RMX2027 supported which are realme C3, realme Narzo 10A respectively

**Comment by jro1979oliver** [comment]
> android_hardware_mediatek repo is not synced according to lineage os which i use and please check device properly the 2 gb variant is known as realme C3i which is codenamed RMX2021 and not supported in source .Only RMX2020,RMX2027 supported which are realme C3, realme Narzo 10A respectively

calm dude, I checked online and saw that identified as your family, that's why I asked. Hardware mediatek in our source doesn't need to be inline with lineage, needs to be inline with our devices needs, so that's the reason I asked.

**Comment by Willylakshit** [comment]
ive checked  current hardware repo in pe and it will work fine with the device 
 Also current mediatek_vendor_sepolicy_vndr repo in pe is not compatible with device
