### ISSUE TITLE
New maintainer for Mi A3

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#3133]
### Device you want to apply for

Xiaomi Mi A3

### Device Tree Sources

Device Tree: 
https://github.com/Noctowl709/device_xiaomi_laurel_sprout
Vendor Tree:
https://github.com/Noctowl709/vendor_xiaomi_laurel_sprout
Kernel Tree:
https://github.com/Noctowl709/kernel_xiaomi_laurel_sprout

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

Maintained Pixel Plus for A2 for almost a year , Arrow os for MI A3

### Telegram username

https://t.me/lzyfrank

### GitHub username

https://github.com/Noctowl709

**Comment by jro1979oliver** [comment]
I saw you lack some experience on solving build issues. Feel free to come back later and reopen this

**Comment by ghost** [comment]
@jro1979oliver sir can u please assist about wat build issues are u referring to?
