### ISSUE TITLE
New maintainer For Redmi Note 12 4G (tapas / topaz)

### ISSUE THREAD

**Issue by StereoBlade12** [PixelExperience/official_devices#3147]
### Device you want to apply for

Redmi Note 12 4G (tapas / topaz)

### Device Tree Sources

The Tree Sources

https://github.com/Agatha-Prjkt/device_xiaomi_topaz

Vender Xiaomi Tapas / Topaz

https://gitlab.com/agathasenpai/vendor_xiaomi_topaz

### Number of ROM's you maintain officially

2

### Any Exceptions/special concern?

No

### Telegram username

govyany

### GitHub username

StereoBlade12

**Comment by jro1979oliver** [comment]
Dude, I'm sorry but this trees doesn't belong to you and at first glance I saw the above image, which is a CoC violation. Build,  test,  gain knowledge and then come back
![image](https://github.com/PixelExperience/official_devices/assets/46964018/7f8a2e77-5ccb-497f-8047-7dd779bc34b9)
