### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Jackieboi24** [PixelExperience/official_devices#3151]
### Device you want to apply for

Redmi note 12 4G (tapas)

### Device Tree Sources

Trees are cool 

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

No

### Telegram username

Jackieboi24

### GitHub username

Jackieboi24

**Comment by StereoBlade12** [comment]
😂😂😂

**Comment by StereoBlade12** [comment]
Trees Are Cool 😂😂😂
