### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by zlewchan** [PixelExperience/official_devices#3157]
### Device you want to apply for

Nothing Phone (1) (Spacewar)

### Device Tree Sources

https://github.com/x0x00044/device_nothing_Spacewar
https://github.com/x0x00044/vendor_nothing_Spacewar
https://github.com/x0x00044/kernel_nothing_sm7325
https://github.com/nothing-sm7325/android_packages_apps_ParanoidGlyph

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

No.

### Telegram username

x0x00044

### GitHub username

x0x00044

**Comment by jro1979oliver** [comment]
You're welcome to open the relative PR and start the nothing restarting
