### ISSUE TITLE
request for galaxy a8 2018

### ISSUE THREAD

**Issue by DaviVole** [PixelExperience/official_devices#3163]
### Device you want to apply for

Galaxy A8 (2018) (jackpotlte)

### Device Tree Sources

https://github.com/AndroidBlobs/device_samsung_jackpotlte

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

well, there are few roms for this phone which has great potential and which can still reach the levels of some already supported xiaomi, a very normal rom pixel experience would be fine.

### Telegram username

@DaviVole

### GitHub username

DaviVole

**Comment by jro1979oliver** [comment]
This is a dummy device tree, no chances to build as it is
