### ISSUE TITLE
Resurrection of Xiaomi Mi 11i / Xiaomi Mi11X Pro / Redmi K40 Pro / Pro+ (haydn)

### ISSUE THREAD

**Issue by sadoyui** [PixelExperience/official_devices#3165]
### Device you want to apply for

Xiaomi Mi 11i / Xiaomi Mi11X Pro / Redmi K40 Pro / Pro+ (haydn)

### Device Tree Sources

https://github.com/haydn-development/device_xiaomi_haydn
https://github.com/haydn-development/kernel_xiaomi_haydn
https://github.com/haydn-development/vendor_xiaomi_haydn

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

WIP now

### Telegram username

@William_sadoyui

### GitHub username

github.com/sadoyui

**Comment by jro1979oliver** [comment]
As you said in special concerns, this is still a wip so I ask you to apply it when everything is in accordance with the CoC. Good job, good luck and reopen as soon as everything is ready
