### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kartik-commits** [PixelExperience/official_devices#3169]
### Device you want to apply for

[POCO X5 Pro 5G](https://www.gsmarena.com/xiaomi_poco_x5_pro-12094.php) / [Redmi Note 12 Pro Speed Edition](https://www.gsmarena.com/xiaomi_redmi_note_12_pro_speed-12045.php)

### Device Tree Sources

    
    Device Tree ↓ 
https://github.com/kartik-commits/device_xiaomi_redwood

    Common Tree ↓
https://github.com/kartik-commits/device_xiaomi_sm7325-common

    Kernel Tree ↓
https://github.com/kartik-commits/atomX
    
    Unofficial OTA releases ↓ 
https://github.com/kartik-commits/ota_pixelexperience

    Vendor Trees ↓
https://github.com/kartik-commits/vendor_xiaomi_redwood
https://github.com/kartik-commits/vendor_xiaomi_sm7325-common

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

I have been building PE and PE+ for almost 2 months.
Meanwhile many problems and bugs are solved but Fast Charging for 67 watts is not working because of incomplete kernel source of Xiaomi.
    I request you to accept my maintainer-ship, I will guarantee my complete perseverance.

### Telegram username

https://t.me/kartik_ane_nenu

### GitHub username

@kartik-commits

**Comment by thepriyanshujangid** [comment]
Finally redwood Official

**Comment by ghost** [comment]
Waited for pixel experience since the day bought this device :) exited to try offical build!!

**Comment by Tarunabcd31** [comment]
Finally 😃

**Comment by jro1979oliver** [comment]
Why I'm getting a 404 on kernel link?
And where is the vendor tree? 
What I must point on device tree / common tree:
There some sort of no effects choice of props and the commit messages sometimes referred to Xiaomi Lisa and others to any device... 
Some lack of authorship.
I'm not closing this now waiting for you to address my claims and good luck

**Comment by jro1979oliver** [comment]
> Why I'm getting a 404 on kernel link? And where is the vendor tree? What I must point on device tree / common tree: There some sort of no effects choice of props and the commit messages sometimes referred to Xiaomi Lisa and others to any device... Some lack of authorship. I'm not closing this now waiting for you to address my claims and good luck

Update: now I can access kernel

**Comment by kartik-commits** [comment]
> > Why I'm getting a 404 on kernel link? And where is the vendor tree? What I must point on device tree / common tree: There some sort of no effects choice of props and the commit messages sometimes referred to Xiaomi Lisa and others to any device... Some lack of authorship. I'm not closing this now waiting for you to address my claims and good luck
> 
> Update: now I can access kernel

Sorry for the honest mistakes, I'm a new developer. 
I have updated Kernel and added Vendor blobs.
And I will revert every dirty commit and add them back with appropriate authorship. I request you to please ase give me some time.

**Comment by jro1979oliver** [comment]
> > > Why I'm getting a 404 on kernel link? And where is the vendor tree? What I must point on device tree / common tree: There some sort of no effects choice of props and the commit messages sometimes referred to Xiaomi Lisa and others to any device... Some lack of authorship. I'm not closing this now waiting for you to address my claims and good luck
> > 
> > 
> > Update: now I can access kernel
> 
> Sorry for the honest mistakes, I'm a new developer. I have updated Kernel and added Vendor blobs. And I will revert every dirty commit and add them back with appropriate authorship. I request you to please ase give me some time.

Take your time... I see there are some mistakes but nothing major and I saw you addressing every CoC breakers with care. As I said earlier, good luck

**Comment by kartik-commits** [comment]
> Why I'm getting a 404 on kernel link? And where is the vendor tree? What I must point on device tree / common tree: There some sort of no effects choice of props and the commit messages sometimes referred to Xiaomi Lisa and others to any device... Some lack of authorship. I'm not closing this now waiting for you to address my claims and good luck

Any special tip for me brother, I haven't maintained anything officially yet so don't know some diplomatic things. You seems experienced that's why asking.

**Comment by jro1979oliver** [comment]
welcome and good luck
