### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by asriadirahim** [PixelExperience/official_devices#3178]
### Device you want to apply for

Google Pixel 2/2XL (walleye/taimen)

### Device Tree Sources

Device Tree
https://github.com/PixelExperience-Devices/device_google_walleye
https://github.com/PixelExperience-Devices/device_google_taimen
https://github.com/PixelExperience-Devices/device_google_wahoo

Kernel Tree
https://github.com/PixelExperience-Devices/kernel_google_wahoo

Vendor Tree
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_google_walleye
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_google_taimen

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

No

### Telegram username

@asriadirahim

### GitHub username

asriadirahim

**Comment by PixelBoot** [comment]
All good from my end, welcome onboard!
