### ISSUE TITLE
Redmi Note 12 4G (tapas/topaz)

### ISSUE THREAD

**Issue by StereoBlade12** [PixelExperience/official_devices#3210]
### Device you want to apply for

Redmi Note 12 4G (tapas/topaz)

### Device Tree Sources

Device Tree:
https://github.com/Agatha-Prjkt/device_xiaomi_topaz

Device Vendor:

https://gitlab.com/agathasenpai/vendor_xiaomi_topaz

Device Kernel:

https://gitlab.com/agathasenpai/device_xiaomi_topaz-kernel

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

No

### Telegram username

StereoBlade16

### GitHub username

StereoBlade12

**Comment by RisenID** [comment]
Device applications are not open for a14 yet.
