### ISSUE TITLE
Rohitsinh 

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#3211]
### Device you want to apply for

Redmi note 12 5g/poco x5 5g (sunstone + moonstone= stone)

### Device Tree Sources

https://github.com/Stone-Trees

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

No

### Telegram username

Rohitsinh

### GitHub username

Luffy-2510

**Comment by RisenID** [comment]
Applications are currently closed for A14, we look forward to seeing your application in a few months.
