### ISSUE TITLE
JYR_RC

### ISSUE THREAD

**Issue by JYRRC** [PixelExperience/official_devices#3212]
### Device you want to apply for

Redmi note 12 Turbo-POCO F5

### Device Tree Sources

https://github.com/JYRRC/device_xiaomi_marble/tree/fourteen

https://github.com/JYRRC/vendor_xiaomi_marble/tree/fourteen

https://github.com/JYRRC/device_xiaomi_marble-kernel/tree/thirteen

### Number of ROM's you maintain officially

Two

### Any Exceptions/special concern?

None

### Telegram username

t.me/JYR_RC

### GitHub username

https://github.com/JYRRC

**Comment by RisenID** [comment]
Applications are currently closed for A14, we look forward to seeing your application in a few months.

**Comment by JYRRC** [comment]
Okay I'll do it, thanks.
