### ISSUE TITLE
New maintainer Rohitsinh 

### ISSUE THREAD

**Issue by ghost** [PixelExperience/official_devices#3213]
### Device you want to apply for

Redmi note 12 5g/poco x5 5g (sunstone + moonstone= stone)

### Device Tree Sources

Device Tree :-  https://github.com/Stone-Trees/device_xiaomi_stone
Common Tree :- https://github.com/Stone-Trees/device_xiaomi_sm6375-common.git
Stone-kernel:- https://github.com/Stone-Trees/xiaomi_stone-kernel.git
Vendor tree :- https://github.com/Stone-Trees/vendor_xiaomi.git
Kernel Tree :- https://github.com/Agatha-Prjkt/kernel_xiaomi_sm6375.git

👉Our Tree Is ready For A14

👉Pixel experience Android 14 (U) Build.  XDA Link
 XDA Link:-
https://xdaforums.com/t/pixelexperience-unofficial-rom-u-stone-pixelexperience-unofficial-android-14-u.4639324/

👉 Privious A13 Build:- https://telegram.me/rohitsinhprjkt/27

### Number of ROM's you maintain officially

Ya,( 1 Rom Firedroid)

### Any Exceptions/special concern?

No 

### Telegram username

Rohitsinh

### GitHub username

Luffy-2510

**Comment by RisenID** [comment]
Just last week in your application #3211 you were informed that applications are not open yet. Please do not apply again till applications are open. Failure to do this will result in some sort of further action from our side.
You can monitor https://blog.pixelexperience.org/ to be informed of when we will open applications.
