### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Tkiliay** [PixelExperience/official_devices#3219]
### Device you want to apply for

Redmi K40(alioth)

### Device Tree Sources

https://github.com/Tkiliay/android_kernel_xiaomi_sm8250
https://github.com/Tkiliay/device_xiaomi_sm8250-common
https://github.com/Tkiliay/device_xiaomi_alioth
https://github.com/Tkiliay/proprietary_vendor_xiaomi_alioth
https://github.com/Tkiliay/proprietary_vendor_xiaomi_sm8250-common

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

Due to my studies, messages may be replied later.

### Telegram username

@Tkiliay

### GitHub username

Tkiliay

**Comment by RisenID** [comment]
Applications are currently closed for A14, we look forward to seeing your application in a few months.
