### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ahmedtohamy1** [PixelExperience/official_devices#3226]
### Device you want to apply for

Mi 10T (apollo)

### Device Tree Sources

https://github.com/Apollo-Trees/device_xiaomi_apollo
https://github.com/Apollo-Trees/device_xiaomi_sm8250-common
https://github.com/Apollo-Trees/vendor_xiaomi_apollo
https://github.com/Apollo-Trees/vendor_xiaomi_sm8250-common

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

Nothing special.

### Telegram username

@ahmed_tohamy

### GitHub username

Ahmedtohamy1

**Comment by RisenID** [comment]
Applications are currently closed for A14, we look forward to seeing your application in a few months.
