### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by GRajin** [PixelExperience/official_devices#3228]
### Device you want to apply for

Motorola Moto G9 (guamp)

### Device Tree Sources

https://github.com/moto-guamp/android_device_motorola_guamp
https://github.com/moto-guamp/android_device_motorola_sm6225-common.git
https://github.com/moto-guamp/android_kernel_motorola_sm6225.git
https://github.com/moto-guamp/proprietary_vendor_motorola_guamp.git
https://github.com/moto-guamp/proprietary_vendor_motorola_sm6225-common.git

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

The pixel experience source already has GPS and audio files for bengal devices. So, while compiling, I removed the sources from PE. I will remove those from the device sources in my next test. Other peripherals are working fine.

### Telegram username

rajinTechie

### GitHub username

GRajin

**Comment by GRajin** [comment]
Here are some pics of the build
![1](https://github.com/PixelExperience/official_devices/assets/41743289/cc9af91c-1dcb-4668-834c-89917de3c681)
![2](https://github.com/PixelExperience/official_devices/assets/41743289/c97c469c-6cfe-486f-b4cd-90f8038acf41)
![3](https://github.com/PixelExperience/official_devices/assets/41743289/f25427b8-1994-425f-aa23-fc324b4fce6b)

**Comment by RisenID** [comment]
Applications for A13 are completely closed, and applications for a14 are not open yet.

**Comment by GRajin** [comment]
Okay!! I will reapply again when it is opened! Thank you.
