### ISSUE TITLE
New maintainer for Mi10T/pro apollo

### ISSUE THREAD

**Issue by amirxon2004** [PixelExperience/official_devices#3229]
### Device you want to apply for

Mi 10T/pro Apollo

### Device Tree Sources

https://github.com/PiotrZPL/device_xiaomi_apollo
https://github.com/PiotrZPL/vendor_xiaomi_apollo
https://github.com/EmanuelCN/kernel_xiaomi_sm8250

### Number of ROM's you maintain officially

Pe 14 staging - 1  https://xdaforums.com/t/rom-updated-unofficial-a14-alpha-pixel-experience-for-xiaomi-mi-10t-mi-10t-pro-redmi-k30s-ultra-apollo-apollopro.4646161/

### Any Exceptions/special concern?

nope

### Telegram username

@Zhong_Li_Daddy

### GitHub username

amirxon2004

**Comment by RisenID** [comment]
Applications are currently closed for A14, we look forward to seeing your application in a few months.

**Comment by amirxon2004** [comment]
> Applications are currently closed for A14, we look forward to seeing your application in a few months.
I can build android 13 plus too.
