### ISSUE TITLE
GXC2356

### ISSUE THREAD

**Issue by GXC2356** [PixelExperience/official_devices#3230]
### Device you want to apply for

Poco X3 Pro (vayu)

### Device Tree Sources

https://github.com/SkylineUI-Devices/device_xiaomi_vayu.git

https://github.com/SkylineUI-Devices/vendor_xiaomi_vayu.git

https://github.com/SkylineUI-Devices/kernel_xiaomi_vayu.git

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

![68747470733a2f2f66646e322e67736d6172656e612e636f6d2f76762f706963732f7869616f6d692f7869616f6d692d706f636f2d78332d70726f2d312e6a7067](https://github.com/PixelExperience/official_devices/assets/108477326/adaf97c4-e62e-41e2-8e11-ee7cd1591ea4)

I want to take official from Android 14

My unofficial builds:
https://t.me/GXC_channel

### Telegram username

@GXC2356

### GitHub username

@GXC2356

**Comment by RisenID** [comment]
Applications are currently closed for A14, we look forward to seeing your application in a few months.
