### ISSUE TITLE
Official maintenance for Poco X3 pro

### ISSUE THREAD

**Issue by GXC2356** [PixelExperience/official_devices#3262]
### Device you want to apply for

Poco X3 Pro (vayu)

### Device Tree Sources

https://github.com/SkylineUI-Devices/device_xiaomi_vayu.git

https://github.com/SkylineUI-Devices/vendor_xiaomi_vayu.git

https://github.com/SkylineUI-Devices/kernel_xiaomi_vayu.git

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

I have built pe 14 unofficial before

https://t.me/GXC_channel/32

https://t.me/GXC_channel/33

https://t.me/GXC_channel/34

### Telegram username

GXC2356

### GitHub username

@GXC2356

**Comment by RisenID** [comment]
Applications are currently closed for A14, we look forward to seeing your application in a couple months.
